In [2]:
library("lme4")
library("margins")
library("stargazer")
library("emmeans")
library("ggeffects")
library("broom")
library("broom.mixed")
library("MASS")
library("pscl")
library("fixest")
library("marginaleffects")
library("modelsummary")
library("glmmTMB")
library("dplyr")

In [3]:
packageVersion("marginaleffects")

[1] ‘0.25.1’

In [4]:
main_path <- "/home/20250114zmz_kd/"
data <- read.csv(paste0(main_path, "GraduationPaper/RevisetoJournal/9991-MergedData_similarity.csv"))
dim(data)

[1] 317275    103

In [5]:
print(names(data))

  [1] "X"
  [2] "work_id"
  [3] "PublishedYear"
  [4] "Facility"
  [5] "num_fac"
  [6] "paper_type"
  [7] "paper_language"
  [8] "novel_uzzi"
  [9] "novel_uzzi_bin"
 [10] "num_fac_scientist"
 [11] "ratio_fac_scientist"
 [12] "bin_fac_scientist"
 [13] "text_fac_scientist"
 [14] "fac_scientist_team"
 [15] "num_leader"
 [16] "ratio_leader"
 [17] "bin_leader"
 [18] "fac_scientist_lead_relratio"
 [19] "fac_scientist_lead_num"
 [20] "fac_scientist_lead_ratio"
 [21] "fac_scientist_lead_bin"
 [22] "fac_scientist_lead_text"
 [23] "CoType"
 [24] "CoType_Collaboration"
 [25] "CoType_Participation"
 [26] "CoType_Service"
 [27] "lnnum_author"
 [28] "lnnum_inst"
 [29] "lnnum_country"
 [30] "international"
 [31] "lnnum_reference"
 [32] "open_access"
 [33] "RaoStirling"
 [34] "SDG"
 [35] "lntimescited5"
 [36] "lntimescited10"
 [37] "lntimescitedall"
 [38] "lnab_length"
 [39] "lnmean_career_age"
 [40] "lnex_ld_avg_avgimpact"
 [41] "lnex_ld_avg_insthindex"
 [42] "ex_ld_bin_gs"
 [43] "ex_ld_ratio_gs"
 [44] "ex_ld_bin_sameC"
 [45] "ex_ld_ratio_sameC"
 [46] "lnex_ld_avg_before_year_prod_fac"
 [47] "lnex_ld_avg_before_year_with_ih"
 [48] "ex_ld_ratio_before_year_with_ih_bin"
 [49] "ex_ld_max_before_year_with_ih_bin"
 [50] "lnex_ld_avg_before_year_participation"
 [51] "ex_ld_ratio_before_year_participation_bin"
 [52] "ex_ld_max_before_year_participation_bin"
 [53] "lnex_ld_avg_before_year_co_lead"
 [54] "ex_ld_ratio_before_year_co_lead_bin"
 [55] "ex_ld_max_before_year_co_lead_bin"
 [56] "Agricultural.and.Biological.Sciences"
 [57] "Arts.and.Humanities"
 [58] "Biochemistry..Genetics.and.Molecular.Biology"
 [59] "Business..Management.and.Accounting"
 [60] "Chemical.Engineering"
 [61] "Chemistry"
 [62] "Computer.Science"
 [63] "Decision.Sciences"
 [64] "Dentistry"
 [65] "Earth.and.Planetary.Sciences"
 [66] "Economics..Econometrics.and.Finance"
 [67] "Energy"
 [68] "Engineering"
 [69] "Environmental.Science"
 [70] "Health.Professions"
 [71] "Immunology.and.Microbiology"
 [72] "Materials.Science"
 [73] "Mathematics"
 [74] "Medicine"
 [75] "Neuroscience"
 [76] "Nursing"
 [77] "Pharmacology..Toxicology.and.Pharmaceutics"
 [78] "Physics.and.Astronomy"
 [79] "Psychology"
 [80] "Social.Sciences"
 [81] "Veterinary"
 [82] "domain_Health.Sciences"
 [83] "domain_Life.Sciences"
 [84] "domain_Physical.Sciences"
 [85] "domain_Social.Sciences"
 [86] "sum"
 [87] "num_author"
 [88] "num_inst"
 [89] "num_country"
 [90] "num_reference"
 [91] "timescited5"
 [92] "timescited10"
 [93] "timescitedall"
 [94] "ab_length"
 [95] "mean_career_age"
 [96] "ex_ld_avg_avgimpact"
 [97] "ex_ld_avg_insthindex"
 [98] "ex_ld_avg_before_year_prod_fac"
 [99] "ex_ld_avg_before_year_with_ih"
[100] "ex_ld_avg_before_year_co_lead"
[101] "ex_ld_avg_before_year_participation"
[102] "knowledge_proximity_mean"
[103] "knowledge_proximity_max"

In [6]:
colSums(is.na(data))

                                           X
                                           0
                                     work_id
                                           0
                               PublishedYear
                                           0
                                    Facility
                                           0
                                     num_fac
                                           0
                                  paper_type
                                           0
                              paper_language
                                           0
                                  novel_uzzi
                                        2532
                              novel_uzzi_bin
                                           0
                           num_fac_scientist
                                           0
                         ratio_fac_scientist
                                           0
                           bin_fac_scientist
                                           0
                          text_fac_scientist
                                           0
                          fac_scientist_team
                                           0
                                  num_leader
                                           0
                                ratio_leader
                                           0
                                  bin_leader
                                           0
                 fac_scientist_lead_relratio
                                           0
                      fac_scientist_lead_num
                                           0
                    fac_scientist_lead_ratio
                                           0
                      fac_scientist_lead_bin
                                           0
                     fac_scientist_lead_text
                                           0
                                      CoType
                                           0
                        CoType_Collaboration
                                           0
                        CoType_Participation
                                           0
                              CoType_Service
                                           0
                                lnnum_author
                                           0
                                  lnnum_inst
                                           0
                               lnnum_country
                                           0
                               international
                                           0
                             lnnum_reference
                                           0
                                 open_access
                                           0
                                 RaoStirling
                                           0
                                         SDG
                                           0
                               lntimescited5
                                       14695
                              lntimescited10
                                       12880
                             lntimescitedall
                                           0
                                 lnab_length
                                           0
                           lnmean_career_age
                                           0
                       lnex_ld_avg_avgimpact
                                           0
                      lnex_ld_avg_insthindex
                                           0
                                ex_ld_bin_gs
                                           0
                              ex_ld_ratio_gs
                                           0
                             ex_ld_bin_sameC
                                           0
                           ex_ld_ratio_sameC
                                           0
            lnex_ld_avg_before_year_prod_fac
                                           0
             lnex_ld_avg_before_year_with_ih
                                           0
         ex_ld_ratio_before_year_with_ih_bin
                                           0
           ex_ld_max_before_year_with_ih_bin
                                           0
       lnex_ld_avg_before_year_participation
                                           0
   ex_ld_ratio_before_year_participation_bin
                                           0
     ex_ld_max_before_year_participation_bin
                                           0
             lnex_ld_avg_before_year_co_lead
                                           0
         ex_ld_ratio_before_year_co_lead_bin
                                           0
           ex_ld_max_before_year_co_lead_bin
                                           0
        Agricultural.and.Biological.Sciences
                                           0
                         Arts.and.Humanities
                                           0
Biochemistry..Genetics.and.Molecular.Biology
                                           0
         Business..Management.and.Accounting
                                           0
                        Chemical.Engineering
                                           0
                                   Chemistry
                                           0
                            Computer.Science
                                           0
                           Decision.Sciences
                                           0
                                   Dentistry
                                           0
                Earth.and.Planetary.Sciences
                                           0
         Economics..Econometrics.and.Finance
                                           0
                                      Energy
                                           0
                                 Engineering
                                           0
                       Environmental.Science
                                           0
                          Health.Professions
                                           0
                 Immunology.and.Microbiology
                                           0
                           Materials.Science
                                           0
                                 Mathematics
                                           0
                                    Medicine
                                           0
                                Neuroscience
                                           0
                                     Nursing
                                           0
  Pharmacology..Toxicology.and.Pharmaceutics
                                           0
                       Physics.and.Astronomy
                                           0
                                  Psychology
                                           0
                             Social.Sciences
                                           0
                                  Veterinary
                                           0
                      domain_Health.Sciences
                                           0
                        domain_Life.Sciences
                                           0
                    domain_Physical.Sciences
                                           0
                      domain_Social.Sciences
                                           0
                                         sum
                                           0
                                  num_author
                                           0
                                    num_inst
                                           0
                                 num_country
                                           0
                               num_reference
                                           0
                                 timescited5
                                       14695
                                timescited10
                                       12880
                               timescitedall
                                           0
                                   ab_length
                                           0
                             mean_career_age
                                           0
                         ex_ld_avg_avgimpact
                                           0
                        ex_ld_avg_insthindex
                                           0
              ex_ld_avg_before_year_prod_fac
                                           0
               ex_ld_avg_before_year_with_ih
                                           0
               ex_ld_avg_before_year_co_lead
                                           0
         ex_ld_avg_before_year_participation
                                           0
                    knowledge_proximity_mean
                                           0
                     knowledge_proximity_max
                                           0

In [7]:
# 把所有无限值替换成 NA
data[sapply(data, is.infinite)] <- NA

In [8]:
# data <- data %>% filter(!is.na(mean_career_age))
# data <- data %>% filter(!is.na(frac_hype_words))
# data <- data %>% filter(!is.na(source_hindex))
# data <- data %>% filter(!is.na(open_access))
# dim(data)

In [9]:
# 找出所有包含无限值的行和列
inf_mask <- sapply(data, function(col) is.infinite(col))
rows_with_inf <- apply(inf_mask, 1, any)  # 哪些行至少有一个Inf
cols_with_inf <- colnames(data)[apply(inf_mask, 2, any)]  # 哪些列有Inf

# 打印包含无限值的行数和列名
cat("包含无限值的行数:", sum(rows_with_inf), "\n")
cat("包含无限值的列名:", paste(cols_with_inf, collapse = ", "), "\n")

# 查看这些行具体内容
data_filt_with_inf <- data[rows_with_inf, c(cols_with_inf), drop=FALSE]
print(data_filt_with_inf)

包含无限值的行数: 0
包含无限值的列名:
data frame with 0 columns and 0 rows

In [10]:
data$Facility <- as.factor(data$Facility)

In [11]:
data$CoType <- factor(data$CoType)
data <- within(data, CoType <- relevel(CoType, ref = 'Service'))
data$paper_type <- factor(data$paper_type)
data <- within(data, paper_type <- relevel(paper_type, ref = 'review'))
data$text_fac_scientist <- factor(data$text_fac_scientist)
data <- within(data, text_fac_scientist <- relevel(text_fac_scientist, ref = 'NonStaffPart'))
data$fac_scientist_lead_text <- factor(data$fac_scientist_lead_text)
data <- within(data, fac_scientist_lead_text <- relevel(fac_scientist_lead_text, ref = 'NonStaffLead'))
data$open_access <- factor(data$open_access)
data <- within(data, open_access <- relevel(open_access, ref = 'False'))
data$SDG <- factor(data$SDG)
data <- within(data, SDG <- relevel(SDG, ref = 'False'))
data$ex_ld_bin_sameC <- factor(data$ex_ld_bin_sameC)
data <- within(data, ex_ld_bin_sameC <- relevel(ex_ld_bin_sameC, ref = 'NonSame'))
data$ex_ld_bin_gs <- factor(data$ex_ld_bin_gs)
data <- within(data, ex_ld_bin_gs <- relevel(ex_ld_bin_gs, ref = 'GlobalSouth'))
data$ex_ld_max_before_year_with_ih_bin <- factor(data$ex_ld_max_before_year_with_ih_bin)
data <- within(data, ex_ld_max_before_year_with_ih_bin <- relevel(ex_ld_max_before_year_with_ih_bin, ref = 'False'))
data$ex_ld_max_before_year_participation_bin <- factor(data$ex_ld_max_before_year_participation_bin)
data <- within(data, ex_ld_max_before_year_participation_bin <- relevel(ex_ld_max_before_year_participation_bin, ref = 'False'))
data$ex_ld_max_before_year_co_lead_bin <- factor(data$ex_ld_max_before_year_co_lead_bin)
data <- within(data, ex_ld_max_before_year_co_lead_bin <- relevel(ex_ld_max_before_year_co_lead_bin, ref = 'False'))
data$international <- factor(data$international)
data <- within(data, international <- relevel(international, ref = 'domestic'))

In [12]:
paper_level <- "lnnum_author + international + lnnum_reference + num_fac + SDG + lnmean_career_age"
ex_controls <- "lnex_ld_avg_avgimpact + lnex_ld_avg_insthindex + ex_ld_bin_gs + ex_ld_bin_sameC + knowledge_proximity_mean"
moderating <- "lnex_ld_avg_before_year_prod_fac + ex_ld_max_before_year_with_ih_bin"
moderating2 <- "lnex_ld_avg_before_year_prod_fac + ex_ld_max_before_year_participation_bin"
moderating3 <- "lnex_ld_avg_before_year_prod_fac + ex_ld_max_before_year_co_lead_bin"
disciplines <- "Agricultural.and.Biological.Sciences + Arts.and.Humanities + Biochemistry..Genetics.and.Molecular.Biology + Business..Management.and.Accounting + Chemical.Engineering + 
 Chemistry + Computer.Science + Decision.Sciences + Dentistry + Earth.and.Planetary.Sciences + 
Economics..Econometrics.and.Finance + Energy + Engineering + Environmental.Science + Health.Professions + 
Immunology.and.Microbiology + Materials.Science + Mathematics + Medicine + Neuroscience + Nursing +
Pharmacology..Toxicology.and.Pharmaceutics + Physics.and.Astronomy + Psychology + Social.Sciences + Veterinary "

In [13]:
paper_vars <- c("lnnum_author", "international", "lnnum_reference", "num_fac", "SDG", "lnmean_career_age")
ex_vars <- c("lnex_ld_avg_avgimpact", "lnex_ld_avg_insthindex", "ex_ld_bin_gs", "ex_ld_bin_sameC", "knowledge_proximity_mean")
moderating_var <- c("lnex_ld_avg_before_year_prod_fac", "ex_ld_max_before_year_with_ih_bin")
moderating2_var <- c("lnex_ld_avg_before_year_prod_fac", "ex_ld_max_before_year_participation_bin")
moderating3_var <- c("lnex_ld_avg_before_year_prod_fac", "ex_ld_max_before_year_co_lead_bin")
disciplines_vars <- c("Agricultural.and.Biological.Sciences", "Arts.and.Humanities", "Biochemistry..Genetics.and.Molecular.Biology", "Business..Management.and.Accounting",
                 "Chemical.Engineering", "Chemistry", "Computer.Science", "Decision.Sciences", "Dentistry",
                 "Earth.and.Planetary.Sciences", "Economics..Econometrics.and.Finance", "Energy", "Engineering",
                 "Environmental.Science + Health.Professions", "Immunology.and.Microbiology", "Materials.Science", "Mathematics",
                 "Medicine", "Neuroscience", "Nursing", "Pharmacology..Toxicology.and.Pharmaceutics", "Physics.and.Astronomy",
                 "Psychology", "Social.Sciences", "Veterinary")

# H1:With > Without

In [14]:
fml <- as.formula(
  paste0("novel_uzzi ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_total_bin <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], vcov = "hetero")
summary(model_total_bin)

NOTE: 98 observations removed because of NA values (LHS: 98).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 294,781
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    t value
text_fac_scientistStaffPart                   -7.47791   0.646703 -11.563136
lnnum_author                                  21.57048   0.754618  28.584639
internationalinternational                     3.20532   0.674055   4.755278
lnnum_reference                              -17.97535   1.211354 -14.839064
num_fac                                      -11.74277   0.290126 -40.474715
SDGTrue                                       -1.53994   0.553439  -2.782501
lnmean_career_age                              1.49432   1.023511   1.459999
lnex_ld_avg_avgimpact                          7.79411   0.488205  15.964826
lnex_ld_avg_insthindex                         2.45220   0.509605   4.811975
ex_ld_bin_gsGlobalNorth                       -9.22934   1.175214  -7.853324
ex_ld_bin_sameCSame                            4.79092   0.646168   7.414359
knowledge_proximity_mean                     218.57515  11.348688  19.259948
lnex_ld_avg_before_year_prod_fac               1.43461   0.416436   3.444977
ex_ld_max_before_year_with_ih_binTrue        -27.82631   0.961268 -28.947510
Agricultural.and.Biological.Sciences         -31.71480   0.649167 -48.854590
Arts.and.Humanities                          -46.16789   6.549515  -7.049055
Biochemistry..Genetics.and.Molecular.Biology -44.12745   0.759651 -58.089130
Business..Management.and.Accounting           24.17376   4.889414   4.944102
Chemical.Engineering                         -17.69432   0.741521 -23.862200
Chemistry                                    -16.71902   0.711974 -23.482610
Computer.Science                             -32.90224   2.192020 -15.010008
Decision.Sciences                              6.10028  54.139442   0.112677
Dentistry                                    -33.20396   3.318084 -10.006968
Earth.and.Planetary.Sciences                 -28.86587   1.286744 -22.433258
Economics..Econometrics.and.Finance           -5.20432  14.959945  -0.347884
Energy                                       -17.71863   0.573619 -30.889179
Engineering                                  -24.26861   0.758358 -32.001521
Environmental.Science                        -15.45710   1.018657 -15.174005
Health.Professions                           -40.79418   3.776607 -10.801808
Immunology.and.Microbiology                  -33.15760   0.763706 -43.416736
Materials.Science                            -25.71428   0.774811 -33.187789
Mathematics                                    8.17777  10.263955   0.796747
Medicine                                     -37.79192   0.797786 -47.370973
Neuroscience                                 -27.75404   0.749320 -37.038950
Nursing                                      -29.05924   0.824972 -35.224500
Pharmacology..Toxicology.and.Pharmaceutics   -23.25202   1.154756 -20.135884
Physics.and.Astronomy                         22.21866   0.832935  26.675130
Psychology                                   -27.54708   3.492979  -7.886415
Social.Sciences                              -18.50660   7.697516  -2.404231
Veterinary                                   -31.20510   3.031277 -10.294373
                                               Pr(>|t|)
text_fac_scientistStaffPart                   < 2.2e-16 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.9827e-06 ***
lnnum_reference                               < 2.2e-16 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                      5.3945e-03 **
lnmean_career_age                            1.4429e-01
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       1.4952e-06 ***
ex_ld_bin_gsGlobalNorth                      4.0650e-15 ***
ex_ld_bin_sameCSame                          1.2254e-13 ***
knowledge_proximity_mean                      < 2.2e-16 ***
lnex_ld_avg_before_year_prod_fac             5.7119e-04 ***
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                          1.8053e-12 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          7.6538e-07 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            9.1029e-01
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.2793e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                             < 2.2e-16 ***
Mathematics                                  4.2560e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   3.1205e-15 ***
Social.Sciences                              1.6207e-02 *
Veterinary                                    < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 145.1     Adj. R2: 0.061101
              Within R2: 0.060163

In [15]:
# 每组 reg_class 的平均预测概率
pred_bin <- avg_predictions(model_total_bin, variables = "text_fac_scientist")
pred_bin

  text_fac_scientist estimate std.error statistic p.value      s.value
1 NonStaffPart       36.44608 11.01445  3.308932  0.0009365265 10.060393
2 StaffPart          28.96816 10.88206  2.662012  0.0077675105  7.008332
  conf.low  conf.high
1 14.858144 58.03401
2  7.639726 50.29660

In [16]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_pred.csv")
# write.csv(pred_bin, fname, row.names = FALSE)

In [17]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_total_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                       & -7.48$^{***}$\\
                                                       & (0.647)\\
   lnnum\_author                                       & 21.6$^{***}$\\
                                                       & (0.755)\\
   internationalinternational                          & 3.21$^{***}$\\
                                                       & (0.674)\\
   lnnum\_reference                                    & -18.0$^{***}$\\
                                                       & (1.21)\\
   num\_fac                                            & -11.7$^{***}$\\
                                                       & (0.290)\\
   SDGTrue                                             & -1.54$^{***}$\\
                                                       & (0.553)\\
   lnmean\_career\_age                                 & 1.49\\
                                                       & (1.02)\\
   lnex\_ld\_avg\_avgimpact                            & 7.79$^{***}$\\
                                                       & (0.488)\\
   lnex\_ld\_avg\_insthindex                           & 2.45$^{***}$\\
                                                       & (0.510)\\
   ex\_ld\_bin\_gsGlobalNorth                          & -9.23$^{***}$\\
                                                       & (1.18)\\
   ex\_ld\_bin\_sameCSame                              & 4.79$^{***}$\\
                                                       & (0.646)\\
   knowledge\_proximity\_mean                          & 218.6$^{***}$\\
                                                       & (11.3)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & 1.43$^{***}$\\
                                                       & (0.416)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & -27.8$^{***}$\\
                                                       & (0.961)\\
   Agricultural.and.Biological.Sciences                & -31.7$^{***}$\\
                                                       & (0.649)\\
   Arts.and.Humanities                                 & -46.2$^{***}$\\
                                                       & (6.55)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -44.1$^{***}$\\
                                                       & (0.760)\\
   Business..Management.and.Accounting                 & 24.2$^{***}$\\
                                                       & (4.89)\\
   Chemical.Engineering                                & -17.7$^{***}$\\
                                                       & (0.742)\\
   Chemistry                                           & -16.7$^{***}$\\
                                                       & (0.712)\\
   Computer.Science                                    & -32.9$^{***}$\\
                                                       & (2.19)\\
   Decision.Sciences                                   & 6.10\\
                                                       & (54.1)\\
   Dentistry                                           & -33.2$^{***}$\\
                                                       & (3.32)\\
   Earth.and.Planetary.Sciences                        & -28.9$^{***}$\\
                                                       & (1.29)\\
   Economics..Econometrics.and.Finance                 & -5.20\\
                                                       & (15.0)\\
   Energy                                              & -17.7$^{***}$\\
                                                       & (0.574)\\
   Engineering                                         & -24.3$^{***}$\\
                                                       & (0.758)\\
   Immunology.and.Microbiology                         & -33.2$^{***}$\\
                                                       & (0.764)\\
   Materials.Science                                   & -25.7$^{***}$\\
                                                       & (0.775)\\
   Mathematics                                         & 8.18\\
                                                       & (10.3)\\
   Medicine                                            & -37.8$^{***}$\\
                                                       & (0.798)\\
   Neuroscience                                        & -27.8$^{***}$\\
                                                       & (0.749)\\
   Nursing                                             & -29.1$^{***}$\\
                                                       & (0.825)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & -23.3$^{***}$\\
                                                       & (1.15)\\
   Physics.and.Astronomy                               & 22.2$^{***}$\\
                                                       & (0.833)\\
   Psychology                                          & -27.5$^{***}$\\
                                                       & (3.49)\\
   Social.Sciences                                     & -18.5$^{**}$\\
                                                       & (7.70)\\
   Veterinary                                          & -31.2$^{***}$\\
                                                       & (3.03)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 294,781\\
   R$^2$                                               & 0.06139\\
   Within R$^2$                                        & 0.06016\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [18]:
margins_eff_bin <- avg_comparisons(model_total_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_bin

  term               contrast                             estimate  std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 0.7948226 0.06039282
  statistic p.value      s.value  conf.low  conf.high predicted_lo predicted_hi
1 13.16088  1.473609e-39 128.9958 0.6764548 0.9131903 27.95618     20.47826
  predicted
1 27.95618

In [19]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_comp_ratio.csv")
# write.csv(margins_eff_bin, fname, row.names = FALSE)

# H1 different disciplines

In [20]:
fml <- as.formula(
  paste0("novel_uzzi ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ps_bin <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==1), ], vcov = "hetero")
summary(model_ps_bin)

NOTE: 92 observations removed because of NA values (LHS: 92).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 253,483
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error    t value
text_fac_scientistStaffPart                   -8.465628   0.706548 -11.981669
lnnum_author                                  23.984848   0.819365  29.272481
internationalinternational                     4.053309   0.785982   5.156998
lnnum_reference                              -19.358400   1.338243 -14.465534
num_fac                                      -13.397625   0.331024 -40.473233
SDGTrue                                       -0.611081   0.638804  -0.956603
lnmean_career_age                              2.305741   1.179369   1.955063
lnex_ld_avg_avgimpact                         10.930593   0.612292  17.851924
lnex_ld_avg_insthindex                         2.045770   0.590034   3.467207
ex_ld_bin_gsGlobalNorth                       -9.069383   1.289815  -7.031538
ex_ld_bin_sameCSame                            5.013478   0.758047   6.613681
knowledge_proximity_mean                     256.557666  13.114926  19.562265
lnex_ld_avg_before_year_prod_fac               0.967652   0.466171   2.075743
ex_ld_max_before_year_with_ih_binTrue        -34.968133   1.227453 -28.488379
Agricultural.and.Biological.Sciences         -35.420534   0.866568 -40.874503
Arts.and.Humanities                          -57.256889   3.296390 -17.369574
Biochemistry..Genetics.and.Molecular.Biology -47.795338   0.787938 -60.658770
Business..Management.and.Accounting           20.796367   4.895918   4.247695
Chemical.Engineering                         -21.611507   0.792799 -27.259768
Chemistry                                    -22.485291   0.821360 -27.375675
Computer.Science                             -41.181030   2.315428 -17.785495
Decision.Sciences                              2.904541  56.630429   0.051289
Dentistry                                    -38.621359   2.416607 -15.981648
Earth.and.Planetary.Sciences                 -33.675006   1.337308 -25.181195
Economics..Econometrics.and.Finance           -8.301779  15.040994  -0.551944
Energy                                       -23.063886   0.656618 -35.125277
Engineering                                  -30.688390   0.865806 -35.444888
Environmental.Science                        -24.917783   1.195287 -20.846693
Health.Professions                           -43.754385   4.713624  -9.282537
Immunology.and.Microbiology                  -35.621227   1.552178 -22.949191
Materials.Science                            -31.932185   0.926789 -34.454630
Mathematics                                    1.711152  10.276892   0.166505
Medicine                                     -37.257734   1.380658 -26.985492
Neuroscience                                 -35.639594   1.387811 -25.680428
Nursing                                      -40.038620   1.204576 -33.238772
Pharmacology..Toxicology.and.Pharmaceutics   -28.331693   1.848817 -15.324227
Physics.and.Astronomy                         15.287800   0.857271  17.833091
Psychology                                   -10.750116   6.374392  -1.686454
Social.Sciences                              -25.213089   9.122620  -2.763799
Veterinary                                   -37.136896   7.557599  -4.913849
                                               Pr(>|t|)
text_fac_scientistStaffPart                   < 2.2e-16 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   2.5113e-07 ***
lnnum_reference                               < 2.2e-16 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                      3.3877e-01
lnmean_career_age                            5.0577e-02 .
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       5.2598e-04 ***
ex_ld_bin_gsGlobalNorth                      2.0478e-12 ***
ex_ld_bin_sameCSame                          3.7562e-11 ***
knowledge_proximity_mean                      < 2.2e-16 ***
lnex_ld_avg_before_year_prod_fac             3.7919e-02 *
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          2.1606e-05 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            9.5909e-01
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          5.8099e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                             < 2.2e-16 ***
Mathematics                                  8.6776e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   9.1710e-02 .
Social.Sciences                              5.7137e-03 **
Veterinary                                   8.9361e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 154.8     Adj. R2: 0.064039
              Within R2: 0.063115

In [21]:
# margins_eff_ps_bin <- avg_comparisons(model_ps_bin, variables = "text_fac_scientist", comparison = 'ratio')
# margins_eff_ps_bin

In [22]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_ps_comp_ratio.csv")
# write.csv(margins_eff_ps_bin, fname, row.names = FALSE)

In [23]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ps_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                       & -8.47$^{***}$\\
                                                       & (0.707)\\
   lnnum\_author                                       & 24.0$^{***}$\\
                                                       & (0.819)\\
   internationalinternational                          & 4.05$^{***}$\\
                                                       & (0.786)\\
   lnnum\_reference                                    & -19.4$^{***}$\\
                                                       & (1.34)\\
   num\_fac                                            & -13.4$^{***}$\\
                                                       & (0.331)\\
   SDGTrue                                             & -0.611\\
                                                       & (0.639)\\
   lnmean\_career\_age                                 & 2.31$^{*}$\\
                                                       & (1.18)\\
   lnex\_ld\_avg\_avgimpact                            & 10.9$^{***}$\\
                                                       & (0.612)\\
   lnex\_ld\_avg\_insthindex                           & 2.05$^{***}$\\
                                                       & (0.590)\\
   ex\_ld\_bin\_gsGlobalNorth                          & -9.07$^{***}$\\
                                                       & (1.29)\\
   ex\_ld\_bin\_sameCSame                              & 5.01$^{***}$\\
                                                       & (0.758)\\
   knowledge\_proximity\_mean                          & 256.6$^{***}$\\
                                                       & (13.1)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & 0.968$^{**}$\\
                                                       & (0.466)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & -35.0$^{***}$\\
                                                       & (1.23)\\
   Agricultural.and.Biological.Sciences                & -35.4$^{***}$\\
                                                       & (0.867)\\
   Arts.and.Humanities                                 & -57.3$^{***}$\\
                                                       & (3.30)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -47.8$^{***}$\\
                                                       & (0.788)\\
   Business..Management.and.Accounting                 & 20.8$^{***}$\\
                                                       & (4.90)\\
   Chemical.Engineering                                & -21.6$^{***}$\\
                                                       & (0.793)\\
   Chemistry                                           & -22.5$^{***}$\\
                                                       & (0.821)\\
   Computer.Science                                    & -41.2$^{***}$\\
                                                       & (2.32)\\
   Decision.Sciences                                   & 2.90\\
                                                       & (56.6)\\
   Dentistry                                           & -38.6$^{***}$\\
                                                       & (2.42)\\
   Earth.and.Planetary.Sciences                        & -33.7$^{***}$\\
                                                       & (1.34)\\
   Economics..Econometrics.and.Finance                 & -8.30\\
                                                       & (15.0)\\
   Energy                                              & -23.1$^{***}$\\
                                                       & (0.657)\\
   Engineering                                         & -30.7$^{***}$\\
                                                       & (0.866)\\
   Immunology.and.Microbiology                         & -35.6$^{***}$\\
                                                       & (1.55)\\
   Materials.Science                                   & -31.9$^{***}$\\
                                                       & (0.927)\\
   Mathematics                                         & 1.71\\
                                                       & (10.3)\\
   Medicine                                            & -37.3$^{***}$\\
                                                       & (1.38)\\
   Neuroscience                                        & -35.6$^{***}$\\
                                                       & (1.39)\\
   Nursing                                             & -40.0$^{***}$\\
                                                       & (1.20)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & -28.3$^{***}$\\
                                                       & (1.85)\\
   Physics.and.Astronomy                               & 15.3$^{***}$\\
                                                       & (0.857)\\
   Psychology                                          & -10.8$^{*}$\\
                                                       & (6.37)\\
   Social.Sciences                                     & -25.2$^{***}$\\
                                                       & (9.12)\\
   Veterinary                                          & -37.1$^{***}$\\
                                                       & (7.56)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 253,483\\
   R$^2$                                               & 0.06437\\
   Within R$^2$                                        & 0.06312\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [24]:
fml <- as.formula(
  paste0("novel_uzzi ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ls_bin <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Life.Sciences==1), ], vcov = "hetero")
summary(model_ls_bin)

NOTE: 12 observations removed because of NA values (LHS: 12).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 77,579
Fixed-effects: PublishedYear: 49
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error    t value
text_fac_scientistStaffPart                   -1.207487   0.485872  -2.485193
lnnum_author                                  -5.592646   0.432067 -12.943927
internationalinternational                    -1.217497   0.318326  -3.824680
lnnum_reference                               -9.145027   0.854868 -10.697584
num_fac                                        0.351628   0.200430   1.754366
SDGTrue                                       -3.052270   0.343181  -8.894048
lnmean_career_age                             -2.231310   0.585706  -3.809611
lnex_ld_avg_avgimpact                          6.248172   0.351179  17.792003
lnex_ld_avg_insthindex                         3.268469   0.379414   8.614525
ex_ld_bin_gsGlobalNorth                       -1.220556   0.619215  -1.971135
ex_ld_bin_sameCSame                            2.161486   0.327337   6.603252
knowledge_proximity_mean                       6.511178   6.146233   1.059377
lnex_ld_avg_before_year_prod_fac              -0.226968   0.289447  -0.784145
ex_ld_max_before_year_with_ih_binTrue         -4.018501   0.401392 -10.011406
Agricultural.and.Biological.Sciences          -6.729817   0.453122 -14.852118
Arts.and.Humanities                           -8.683799   4.456147  -1.948724
Biochemistry..Genetics.and.Molecular.Biology  -0.952568   0.477199  -1.996165
Business..Management.and.Accounting          106.491938  75.580163   1.408993
Chemical.Engineering                          -4.843585   2.554439  -1.896144
Chemistry                                     -5.975222   0.774948  -7.710478
Computer.Science                             -12.779958   0.740258 -17.264188
Decision.Sciences                             -0.391431   9.130010  -0.042873
Dentistry                                     -5.092147   2.042024  -2.493677
Earth.and.Planetary.Sciences                 -12.065008   1.154605 -10.449469
Energy                                        -7.007320   1.009465  -6.941617
Engineering                                   -8.481186   0.863623  -9.820471
Environmental.Science                          0.092222   0.539358   0.170985
Health.Professions                            -7.441062   2.159835  -3.445199
Immunology.and.Microbiology                   -4.393051   0.460047  -9.549143
Materials.Science                             -2.719167   0.532142  -5.109849
Mathematics                                   -0.444988   9.921833  -0.044849
Medicine                                      -9.306159   0.332487 -27.989580
Neuroscience                                  -6.492331   0.506430 -12.819787
Nursing                                       -9.919012   0.629549 -15.755752
Pharmacology..Toxicology.and.Pharmaceutics    -5.924981   0.959119  -6.177526
Physics.and.Astronomy                         -5.810784   0.829718  -7.003324
Psychology                                    -6.419788   2.005662  -3.200833
Social.Sciences                               -9.310928   2.271470  -4.099077
Veterinary                                    -4.888271   1.804132  -2.709487
                                               Pr(>|t|)
text_fac_scientistStaffPart                  1.2950e-02 *
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.3104e-04 ***
lnnum_reference                               < 2.2e-16 ***
num_fac                                      7.9372e-02 .
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            1.3929e-04 ***
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                        < 2.2e-16 ***
ex_ld_bin_gsGlobalNorth                      4.8712e-02 *
ex_ld_bin_sameCSame                          4.0482e-11 ***
knowledge_proximity_mean                     2.8943e-01
lnex_ld_avg_before_year_prod_fac             4.3296e-01
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                          5.1332e-02 .
Biochemistry..Genetics.and.Molecular.Biology 4.5919e-02 *
Business..Management.and.Accounting          1.5884e-01
Chemical.Engineering                         5.7945e-02 .
Chemistry                                    1.2683e-14 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            9.6580e-01
Dentistry                                    1.2645e-02 *
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Energy                                       3.9067e-12 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                        8.6424e-01
Health.Professions                           5.7094e-04 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                            3.2318e-07 ***
Mathematics                                  9.6423e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   6.5436e-10 ***
Physics.and.Astronomy                        2.5198e-12 ***
Psychology                                   1.3709e-03 **
Social.Sciences                              4.1522e-05 ***
Veterinary                                   6.7402e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 47.1     Adj. R2: 0.045339
             Within R2: 0.04123

In [25]:
# margins_eff_ls_bin <- avg_comparisons(model_ls_bin, variables = "text_fac_scientist", comparison = 'ratio')
# margins_eff_ls_bin

In [26]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_ls_comp_ratio.csv")
# write.csv(margins_eff_ls_bin, fname, row.names = FALSE)

In [27]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ls_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                       & -1.21$^{**}$\\
                                                       & (0.486)\\
   lnnum\_author                                       & -5.59$^{***}$\\
                                                       & (0.432)\\
   internationalinternational                          & -1.22$^{***}$\\
                                                       & (0.318)\\
   lnnum\_reference                                    & -9.15$^{***}$\\
                                                       & (0.855)\\
   num\_fac                                            & 0.352$^{*}$\\
                                                       & (0.200)\\
   SDGTrue                                             & -3.05$^{***}$\\
                                                       & (0.343)\\
   lnmean\_career\_age                                 & -2.23$^{***}$\\
                                                       & (0.586)\\
   lnex\_ld\_avg\_avgimpact                            & 6.25$^{***}$\\
                                                       & (0.351)\\
   lnex\_ld\_avg\_insthindex                           & 3.27$^{***}$\\
                                                       & (0.379)\\
   ex\_ld\_bin\_gsGlobalNorth                          & -1.22$^{**}$\\
                                                       & (0.619)\\
   ex\_ld\_bin\_sameCSame                              & 2.16$^{***}$\\
                                                       & (0.327)\\
   knowledge\_proximity\_mean                          & 6.51\\
                                                       & (6.15)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.227\\
                                                       & (0.289)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & -4.02$^{***}$\\
                                                       & (0.401)\\
   Agricultural.and.Biological.Sciences                & -6.73$^{***}$\\
                                                       & (0.453)\\
   Arts.and.Humanities                                 & -8.68$^{*}$\\
                                                       & (4.46)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -0.953$^{**}$\\
                                                       & (0.477)\\
   Business..Management.and.Accounting                 & 106.5\\
                                                       & (75.6)\\
   Chemical.Engineering                                & -4.84$^{*}$\\
                                                       & (2.55)\\
   Chemistry                                           & -5.98$^{***}$\\
                                                       & (0.775)\\
   Computer.Science                                    & -12.8$^{***}$\\
                                                       & (0.740)\\
   Decision.Sciences                                   & -0.391\\
                                                       & (9.13)\\
   Dentistry                                           & -5.09$^{**}$\\
                                                       & (2.04)\\
   Earth.and.Planetary.Sciences                        & -12.1$^{***}$\\
                                                       & (1.15)\\
   Energy                                              & -7.01$^{***}$\\
                                                       & (1.01)\\
   Engineering                                         & -8.48$^{***}$\\
                                                       & (0.864)\\
   Immunology.and.Microbiology                         & -4.39$^{***}$\\
                                                       & (0.460)\\
   Materials.Science                                   & -2.72$^{***}$\\
                                                       & (0.532)\\
   Mathematics                                         & -0.445\\
                                                       & (9.92)\\
   Medicine                                            & -9.31$^{***}$\\
                                                       & (0.332)\\
   Neuroscience                                        & -6.49$^{***}$\\
                                                       & (0.506)\\
   Nursing                                             & -9.92$^{***}$\\
                                                       & (0.630)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & -5.92$^{***}$\\
                                                       & (0.959)\\
   Physics.and.Astronomy                               & -5.81$^{***}$\\
                                                       & (0.830)\\
   Psychology                                          & -6.42$^{***}$\\
                                                       & (2.01)\\
   Social.Sciences                                     & -9.31$^{***}$\\
                                                       & (2.27)\\
   Veterinary                                          & -4.89$^{***}$\\
                                                       & (1.80)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 77,579\\
   R$^2$                                               & 0.04641\\
   Within R$^2$                                        & 0.04123\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [28]:
fml <- as.formula(
  paste0("novel_uzzi ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_hs_bin <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Health.Sciences==1), ], vcov = "hetero")
summary(model_hs_bin)

NOTE: 8 observations removed because of NA values (LHS: 8).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 33,409
Fixed-effects: PublishedYear: 46
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error   t value
text_fac_scientistStaffPart                   -6.163688   1.545622 -3.987837
lnnum_author                                  -2.578085   1.101526 -2.340467
internationalinternational                     1.195446   0.917227  1.303327
lnnum_reference                              -12.413968   2.239326 -5.543617
num_fac                                       -0.185456   0.358998 -0.516595
SDGTrue                                       -2.301709   0.831400 -2.768474
lnmean_career_age                             -1.122964   1.074451 -1.045151
lnex_ld_avg_avgimpact                          2.417556   0.653871  3.697299
lnex_ld_avg_insthindex                         2.818443   0.724040  3.892665
ex_ld_bin_gsGlobalNorth                       -2.991551   3.201607 -0.934391
ex_ld_bin_sameCSame                            3.186092   0.700706  4.546976
knowledge_proximity_mean                     -26.236262  15.560898 -1.686038
lnex_ld_avg_before_year_prod_fac              -0.456755   0.787779 -0.579801
ex_ld_max_before_year_with_ih_binTrue         -4.082273   1.044079 -3.909926
Agricultural.and.Biological.Sciences           0.078323   0.844318  0.092764
Arts.and.Humanities                          -20.845521   4.086311 -5.101305
Biochemistry..Genetics.and.Molecular.Biology  -1.160215   0.696228 -1.666429
Business..Management.and.Accounting           50.593076  17.627757  2.870080
Chemical.Engineering                           0.940744   5.254750  0.179027
Chemistry                                      0.493032   0.936088  0.526694
Computer.Science                             -10.352853   1.168660 -8.858737
Decision.Sciences                             -8.389410   6.209348 -1.351094
Dentistry                                     -4.060072   2.898352 -1.400821
Earth.and.Planetary.Sciences                 -12.118073   1.969215 -6.153759
Economics..Econometrics.and.Finance          -57.250987   5.795174 -9.879080
Energy                                         4.490500   3.111720  1.443093
Engineering                                  -11.274283   3.161308 -3.566335
Environmental.Science                         -1.112078   1.028436 -1.081329
Health.Professions                            -7.885593   3.729600 -2.114327
Immunology.and.Microbiology                    1.220800   0.756891  1.612912
Materials.Science                              5.956290   0.924123  6.445346
Mathematics                                   -6.313722   9.178848 -0.687856
Medicine                                      -4.159213   1.490491 -2.790499
Neuroscience                                  -4.104807   0.792785 -5.177706
Nursing                                      -11.115464   1.120996 -9.915699
Pharmacology..Toxicology.and.Pharmaceutics    -6.984918   1.391035 -5.021384
Physics.and.Astronomy                         22.202883   4.749101  4.675176
Psychology                                    -6.683620   3.045921 -2.194286
Social.Sciences                              -11.116572   3.620741 -3.070248
Veterinary                                    -5.607661   1.879201 -2.984066
                                               Pr(>|t|)
text_fac_scientistStaffPart                  6.6821e-05 ***
lnnum_author                                 1.9265e-02 *
internationalinternational                   1.9247e-01
lnnum_reference                              2.9853e-08 ***
num_fac                                      6.0544e-01
SDGTrue                                      5.6351e-03 **
lnmean_career_age                            2.9596e-01
lnex_ld_avg_avgimpact                        2.1825e-04 ***
lnex_ld_avg_insthindex                       9.9342e-05 ***
ex_ld_bin_gsGlobalNorth                      3.5011e-01
ex_ld_bin_sameCSame                          5.4614e-06 ***
knowledge_proximity_mean                     9.1798e-02 .
lnex_ld_avg_before_year_prod_fac             5.6205e-01
ex_ld_max_before_year_with_ih_binTrue        9.2507e-05 ***
Agricultural.and.Biological.Sciences         9.2609e-01
Arts.and.Humanities                          3.3917e-07 ***
Biochemistry..Genetics.and.Molecular.Biology 9.5637e-02 .
Business..Management.and.Accounting          4.1063e-03 **
Chemical.Engineering                         8.5792e-01
Chemistry                                    5.9841e-01
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            1.7667e-01
Dentistry                                    1.6128e-01
Earth.and.Planetary.Sciences                 7.6528e-10 ***
Economics..Econometrics.and.Finance           < 2.2e-16 ***
Energy                                       1.4900e-01
Engineering                                  3.6252e-04 ***
Environmental.Science                        2.7956e-01
Health.Professions                           3.4495e-02 *
Immunology.and.Microbiology                  1.0677e-01
Materials.Science                            1.1691e-10 ***
Mathematics                                  4.9155e-01
Medicine                                     5.2657e-03 **
Neuroscience                                 2.2593e-07 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   5.1565e-07 ***
Physics.and.Astronomy                        2.9485e-06 ***
Psychology                                   2.8222e-02 *
Social.Sciences                              2.1405e-03 **
Veterinary                                   2.8465e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 72.8     Adj. R2: 0.019049
             Within R2: 0.018954

In [29]:
# margins_eff_hs_bin <- avg_comparisons(model_hs_bin, variables = "text_fac_scientist", comparison = 'ratio')
# margins_eff_hs_bin

In [30]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_hs_comp_ratio.csv")
# write.csv(margins_eff_hs_bin, fname, row.names = FALSE)

In [31]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_hs_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                       & -6.16$^{***}$\\
                                                       & (1.55)\\
   lnnum\_author                                       & -2.58$^{**}$\\
                                                       & (1.10)\\
   internationalinternational                          & 1.20\\
                                                       & (0.917)\\
   lnnum\_reference                                    & -12.4$^{***}$\\
                                                       & (2.24)\\
   num\_fac                                            & -0.185\\
                                                       & (0.359)\\
   SDGTrue                                             & -2.30$^{***}$\\
                                                       & (0.831)\\
   lnmean\_career\_age                                 & -1.12\\
                                                       & (1.07)\\
   lnex\_ld\_avg\_avgimpact                            & 2.42$^{***}$\\
                                                       & (0.654)\\
   lnex\_ld\_avg\_insthindex                           & 2.82$^{***}$\\
                                                       & (0.724)\\
   ex\_ld\_bin\_gsGlobalNorth                          & -2.99\\
                                                       & (3.20)\\
   ex\_ld\_bin\_sameCSame                              & 3.19$^{***}$\\
                                                       & (0.701)\\
   knowledge\_proximity\_mean                          & -26.2$^{*}$\\
                                                       & (15.6)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.457\\
                                                       & (0.788)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & -4.08$^{***}$\\
                                                       & (1.04)\\
   Agricultural.and.Biological.Sciences                & 0.078\\
                                                       & (0.844)\\
   Arts.and.Humanities                                 & -20.8$^{***}$\\
                                                       & (4.09)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -1.16$^{*}$\\
                                                       & (0.696)\\
   Business..Management.and.Accounting                 & 50.6$^{***}$\\
                                                       & (17.6)\\
   Chemical.Engineering                                & 0.941\\
                                                       & (5.25)\\
   Chemistry                                           & 0.493\\
                                                       & (0.936)\\
   Computer.Science                                    & -10.4$^{***}$\\
                                                       & (1.17)\\
   Decision.Sciences                                   & -8.39\\
                                                       & (6.21)\\
   Dentistry                                           & -4.06\\
                                                       & (2.90)\\
   Earth.and.Planetary.Sciences                        & -12.1$^{***}$\\
                                                       & (1.97)\\
   Economics..Econometrics.and.Finance                 & -57.3$^{***}$\\
                                                       & (5.80)\\
   Energy                                              & 4.49\\
                                                       & (3.11)\\
   Engineering                                         & -11.3$^{***}$\\
                                                       & (3.16)\\
   Immunology.and.Microbiology                         & 1.22\\
                                                       & (0.757)\\
   Materials.Science                                   & 5.96$^{***}$\\
                                                       & (0.924)\\
   Mathematics                                         & -6.31\\
                                                       & (9.18)\\
   Medicine                                            & -4.16$^{***}$\\
                                                       & (1.49)\\
   Neuroscience                                        & -4.10$^{***}$\\
                                                       & (0.793)\\
   Nursing                                             & -11.1$^{***}$\\
                                                       & (1.12)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & -6.98$^{***}$\\
                                                       & (1.39)\\
   Physics.and.Astronomy                               & 22.2$^{***}$\\
                                                       & (4.75)\\
   Psychology                                          & -6.68$^{**}$\\
                                                       & (3.05)\\
   Social.Sciences                                     & -11.1$^{***}$\\
                                                       & (3.62)\\
   Veterinary                                          & -5.61$^{***}$\\
                                                       & (1.88)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 33,409\\
   R$^2$                                               & 0.02155\\
   Within R$^2$                                        & 0.01895\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [32]:
fml <- as.formula(
  paste0("novel_uzzi ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_nps_bin <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==0), ], vcov = "hetero")
summary(model_nps_bin)

NOTE: 6 observations removed because of NA values (LHS: 6).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 41,298
Fixed-effects: PublishedYear: 44
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error    t value
text_fac_scientistStaffPart                   -3.136065   0.929138  -3.375242
lnnum_author                                  -6.765645   0.521514 -12.973085
internationalinternational                    -1.483764   0.396163  -3.745335
lnnum_reference                               -6.393325   1.687296  -3.789096
num_fac                                        0.858191   0.271677   3.158867
SDGTrue                                       -4.757647   0.410928 -11.577809
lnmean_career_age                             -4.865555   0.611893  -7.951643
lnex_ld_avg_avgimpact                          7.330653   0.339054  21.620878
lnex_ld_avg_insthindex                         3.181002   0.322193   9.872964
ex_ld_bin_gsGlobalNorth                       -0.969013   0.809865  -1.196512
ex_ld_bin_sameCSame                            2.368498   0.518866   4.564763
knowledge_proximity_mean                      36.665280  11.419303   3.210816
lnex_ld_avg_before_year_prod_fac               0.232082   0.249651   0.929625
ex_ld_max_before_year_with_ih_binTrue         -2.868490   0.536800  -5.343683
Agricultural.and.Biological.Sciences          -4.007934   0.616567  -6.500404
Arts.and.Humanities                          101.356153 111.690460   0.907474
Biochemistry..Genetics.and.Molecular.Biology   1.847201   0.769469   2.400616
Business..Management.and.Accounting           26.798755   7.833896   3.420872
Decision.Sciences                              4.262403  19.277574   0.221107
Dentistry                                     -3.717298   8.184806  -0.454171
Health.Professions                            -8.393165   2.085403  -4.024721
Immunology.and.Microbiology                   -2.890852   0.499444  -5.788145
Medicine                                     -10.332108   0.585565 -17.644689
Neuroscience                                  -7.633680   0.557890 -13.683121
Nursing                                      -10.102462   0.787500 -12.828520
Pharmacology..Toxicology.and.Pharmaceutics    -9.521872   0.972220  -9.793948
Psychology                                    -4.263495   2.942330  -1.449020
Social.Sciences                              -61.749123  61.780607  -0.999490
Veterinary                                    -5.075311   1.647816  -3.080022
                                               Pr(>|t|)
text_fac_scientistStaffPart                  7.3819e-04 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.8040e-04 ***
lnnum_reference                              1.5141e-04 ***
num_fac                                      1.5850e-03 **
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            1.8871e-15 ***
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                        < 2.2e-16 ***
ex_ld_bin_gsGlobalNorth                      2.3150e-01
ex_ld_bin_sameCSame                          5.0150e-06 ***
knowledge_proximity_mean                     1.3246e-03 **
lnex_ld_avg_before_year_prod_fac             3.5257e-01
ex_ld_max_before_year_with_ih_binTrue        9.1559e-08 ***
Agricultural.and.Biological.Sciences         8.1017e-11 ***
Arts.and.Humanities                          3.6416e-01
Biochemistry..Genetics.and.Molecular.Biology 1.6372e-02 *
Business..Management.and.Accounting          6.2481e-04 ***
Decision.Sciences                            8.2501e-01
Dentistry                                    6.4971e-01
Health.Professions                           5.7145e-05 ***
Immunology.and.Microbiology                  7.1682e-09 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Psychology                                   1.4734e-01
Social.Sciences                              3.1756e-01
Veterinary                                   2.0712e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 47.2     Adj. R2: 0.057729
             Within R2: 0.054007

In [33]:
# margins_eff_nps_bin <- avg_comparisons(model_nps_bin, variables = "text_fac_scientist", comparison = 'ratio')
# margins_eff_nps_bin

In [34]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_nps_comp_ratio.csv")
# write.csv(margins_eff_nps_bin, fname, row.names = FALSE)

In [35]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_nps_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                       & -3.14$^{***}$\\
                                                       & (0.929)\\
   lnnum\_author                                       & -6.77$^{***}$\\
                                                       & (0.522)\\
   internationalinternational                          & -1.48$^{***}$\\
                                                       & (0.396)\\
   lnnum\_reference                                    & -6.39$^{***}$\\
                                                       & (1.69)\\
   num\_fac                                            & 0.858$^{***}$\\
                                                       & (0.272)\\
   SDGTrue                                             & -4.76$^{***}$\\
                                                       & (0.411)\\
   lnmean\_career\_age                                 & -4.87$^{***}$\\
                                                       & (0.612)\\
   lnex\_ld\_avg\_avgimpact                            & 7.33$^{***}$\\
                                                       & (0.339)\\
   lnex\_ld\_avg\_insthindex                           & 3.18$^{***}$\\
                                                       & (0.322)\\
   ex\_ld\_bin\_gsGlobalNorth                          & -0.969\\
                                                       & (0.810)\\
   ex\_ld\_bin\_sameCSame                              & 2.37$^{***}$\\
                                                       & (0.519)\\
   knowledge\_proximity\_mean                          & 36.7$^{***}$\\
                                                       & (11.4)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & 0.232\\
                                                       & (0.250)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & -2.87$^{***}$\\
                                                       & (0.537)\\
   Agricultural.and.Biological.Sciences                & -4.01$^{***}$\\
                                                       & (0.617)\\
   Arts.and.Humanities                                 & 101.4\\
                                                       & (111.7)\\
   Biochemistry..Genetics.and.Molecular.Biology        & 1.85$^{**}$\\
                                                       & (0.769)\\
   Business..Management.and.Accounting                 & 26.8$^{***}$\\
                                                       & (7.83)\\
   Decision.Sciences                                   & 4.26\\
                                                       & (19.3)\\
   Dentistry                                           & -3.72\\
                                                       & (8.18)\\
   Immunology.and.Microbiology                         & -2.89$^{***}$\\
                                                       & (0.499)\\
   Medicine                                            & -10.3$^{***}$\\
                                                       & (0.586)\\
   Neuroscience                                        & -7.63$^{***}$\\
                                                       & (0.558)\\
   Nursing                                             & -10.1$^{***}$\\
                                                       & (0.788)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & -9.52$^{***}$\\
                                                       & (0.972)\\
   Psychology                                          & -4.26\\
                                                       & (2.94)\\
   Social.Sciences                                     & -61.7\\
                                                       & (61.8)\\
   Veterinary                                          & -5.08$^{***}$\\
                                                       & (1.65)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 41,298\\
   R$^2$                                               & 0.05937\\
   Within R$^2$                                        & 0.05401\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H2: Collaboration > Participation

In [36]:
fml <- as.formula(
  paste0("novel_uzzi ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_total <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], vcov = "hetero")
summary(model_total)

NOTE: 98 observations removed because of NA values (LHS: 98).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 294,781
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    t value
CoTypeCollaboration                           -9.96637   0.652299 -15.278836
CoTypeParticipation                           -2.15681   1.080937  -1.995312
lnnum_author                                  21.07243   0.754953  27.912245
internationalinternational                     3.25540   0.672961   4.837428
lnnum_reference                              -18.02953   1.213173 -14.861469
num_fac                                      -11.69435   0.289572 -40.384993
SDGTrue                                       -1.49003   0.552596  -2.696418
lnmean_career_age                              1.71602   1.027390   1.670271
lnex_ld_avg_avgimpact                          7.87966   0.488332  16.135854
lnex_ld_avg_insthindex                         2.42266   0.509157   4.758176
ex_ld_bin_gsGlobalNorth                       -9.19331   1.174910  -7.824689
ex_ld_bin_sameCSame                            4.86919   0.647189   7.523598
knowledge_proximity_mean                     218.70593  11.340891  19.284722
lnex_ld_avg_before_year_prod_fac               1.38674   0.416386   3.330423
ex_ld_max_before_year_with_ih_binTrue        -27.73728   0.961968 -28.833880
Agricultural.and.Biological.Sciences         -31.74446   0.649368 -48.885144
Arts.and.Humanities                          -46.29931   6.549986  -7.068613
Biochemistry..Genetics.and.Molecular.Biology -43.98024   0.758230 -58.003845
Business..Management.and.Accounting           24.45728   4.890809   5.000662
Chemical.Engineering                         -17.70271   0.741517 -23.873644
Chemistry                                    -16.71210   0.712166 -23.466566
Computer.Science                             -32.81395   2.191390 -14.974038
Decision.Sciences                              6.26461  54.138966   0.115713
Dentistry                                    -33.30561   3.309083 -10.064907
Earth.and.Planetary.Sciences                 -28.78615   1.290739 -22.302070
Economics..Econometrics.and.Finance           -4.80693  14.954197  -0.321444
Energy                                       -17.73752   0.573737 -30.915765
Engineering                                  -24.21343   0.756802 -31.994398
Environmental.Science                        -15.47405   1.018953 -15.186228
Health.Professions                           -40.98813   3.783896 -10.832256
Immunology.and.Microbiology                  -33.09180   0.763069 -43.366744
Materials.Science                            -25.75220   0.776188 -33.177776
Mathematics                                    8.20777  10.270172   0.799185
Medicine                                     -37.76411   0.797294 -47.365353
Neuroscience                                 -27.77251   0.748199 -37.119141
Nursing                                      -29.10017   0.824570 -35.291323
Pharmacology..Toxicology.and.Pharmaceutics   -23.35018   1.154811 -20.219908
Physics.and.Astronomy                         22.35881   0.828511  26.986743
Psychology                                   -27.79034   3.482143  -7.980816
Social.Sciences                              -18.66725   7.696670  -2.425367
Veterinary                                   -31.06870   3.040562 -10.218080
                                               Pr(>|t|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          4.6010e-02 *
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.3160e-06 ***
lnnum_reference                               < 2.2e-16 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                      7.0094e-03 **
lnmean_career_age                            9.4867e-02 .
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       1.9544e-06 ***
ex_ld_bin_gsGlobalNorth                      5.1059e-15 ***
ex_ld_bin_sameCSame                          5.3439e-14 ***
knowledge_proximity_mean                      < 2.2e-16 ***
lnex_ld_avg_before_year_prod_fac             8.6725e-04 ***
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                          1.5683e-12 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          5.7167e-07 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            9.0788e-01
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.4787e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                             < 2.2e-16 ***
Mathematics                                  4.2418e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.4589e-15 ***
Social.Sciences                              1.5294e-02 *
Veterinary                                    < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 145.1     Adj. R2: 0.061253
              Within R2: 0.060319

In [37]:
# # 每组 reg_class 的平均预测概率
# pred <- avg_predictions(model_total, variables = "CoType")
# pred

In [38]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_pred.csv")
# write.csv(pred, fname, row.names = FALSE)

In [39]:
# # 每组 reg_class 的平均预测概率
# margins_eff <- avg_comparisons(model_total, variables = "CoType", comparison = 'ratio')
# margins_eff

In [40]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_comp_ratio.csv")
# write.csv(margins_eff, fname, row.names = FALSE)

In [41]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_total,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                 & -9.97$^{***}$\\
                                                       & (0.652)\\
   CoTypeParticipation                                 & -2.16$^{**}$\\
                                                       & (1.08)\\
   lnnum\_author                                       & 21.1$^{***}$\\
                                                       & (0.755)\\
   internationalinternational                          & 3.26$^{***}$\\
                                                       & (0.673)\\
   lnnum\_reference                                    & -18.0$^{***}$\\
                                                       & (1.21)\\
   num\_fac                                            & -11.7$^{***}$\\
                                                       & (0.290)\\
   SDGTrue                                             & -1.49$^{***}$\\
                                                       & (0.553)\\
   lnmean\_career\_age                                 & 1.72$^{*}$\\
                                                       & (1.03)\\
   lnex\_ld\_avg\_avgimpact                            & 7.88$^{***}$\\
                                                       & (0.488)\\
   lnex\_ld\_avg\_insthindex                           & 2.42$^{***}$\\
                                                       & (0.509)\\
   ex\_ld\_bin\_gsGlobalNorth                          & -9.19$^{***}$\\
                                                       & (1.17)\\
   ex\_ld\_bin\_sameCSame                              & 4.87$^{***}$\\
                                                       & (0.647)\\
   knowledge\_proximity\_mean                          & 218.7$^{***}$\\
                                                       & (11.3)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & 1.39$^{***}$\\
                                                       & (0.416)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & -27.7$^{***}$\\
                                                       & (0.962)\\
   Agricultural.and.Biological.Sciences                & -31.7$^{***}$\\
                                                       & (0.649)\\
   Arts.and.Humanities                                 & -46.3$^{***}$\\
                                                       & (6.55)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -44.0$^{***}$\\
                                                       & (0.758)\\
   Business..Management.and.Accounting                 & 24.5$^{***}$\\
                                                       & (4.89)\\
   Chemical.Engineering                                & -17.7$^{***}$\\
                                                       & (0.742)\\
   Chemistry                                           & -16.7$^{***}$\\
                                                       & (0.712)\\
   Computer.Science                                    & -32.8$^{***}$\\
                                                       & (2.19)\\
   Decision.Sciences                                   & 6.26\\
                                                       & (54.1)\\
   Dentistry                                           & -33.3$^{***}$\\
                                                       & (3.31)\\
   Earth.and.Planetary.Sciences                        & -28.8$^{***}$\\
                                                       & (1.29)\\
   Economics..Econometrics.and.Finance                 & -4.81\\
                                                       & (15.0)\\
   Energy                                              & -17.7$^{***}$\\
                                                       & (0.574)\\
   Engineering                                         & -24.2$^{***}$\\
                                                       & (0.757)\\
   Immunology.and.Microbiology                         & -33.1$^{***}$\\
                                                       & (0.763)\\
   Materials.Science                                   & -25.8$^{***}$\\
                                                       & (0.776)\\
   Mathematics                                         & 8.21\\
                                                       & (10.3)\\
   Medicine                                            & -37.8$^{***}$\\
                                                       & (0.797)\\
   Neuroscience                                        & -27.8$^{***}$\\
                                                       & (0.748)\\
   Nursing                                             & -29.1$^{***}$\\
                                                       & (0.825)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & -23.4$^{***}$\\
                                                       & (1.15)\\
   Physics.and.Astronomy                               & 22.4$^{***}$\\
                                                       & (0.829)\\
   Psychology                                          & -27.8$^{***}$\\
                                                       & (3.48)\\
   Social.Sciences                                     & -18.7$^{**}$\\
                                                       & (7.70)\\
   Veterinary                                          & -31.1$^{***}$\\
                                                       & (3.04)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 294,781\\
   R$^2$                                               & 0.06154\\
   Within R$^2$                                        & 0.06032\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H2 Discipline

In [42]:
fml <- as.formula(
  paste0("novel_uzzi ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ps <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==1), ], vcov = "hetero")
summary(model_ps)

NOTE: 92 observations removed because of NA values (LHS: 92).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 253,483
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error    t value
CoTypeCollaboration                          -10.680946   0.708625 -15.072769
CoTypeParticipation                           -3.690634   1.166319  -3.164343
lnnum_author                                  23.491284   0.822742  28.552427
internationalinternational                     4.098818   0.784869   5.222298
lnnum_reference                              -19.404254   1.340109 -14.479610
num_fac                                      -13.347596   0.330446 -40.392715
SDGTrue                                       -0.572494   0.638011  -0.897310
lnmean_career_age                              2.510982   1.184017   2.120732
lnex_ld_avg_avgimpact                         11.025679   0.612878  17.989999
lnex_ld_avg_insthindex                         2.019775   0.589581   3.425778
ex_ld_bin_gsGlobalNorth                       -9.064326   1.289801  -7.027695
ex_ld_bin_sameCSame                            5.100980   0.759500   6.716233
knowledge_proximity_mean                     256.679119  13.106711  19.583793
lnex_ld_avg_before_year_prod_fac               0.927730   0.466203   1.989971
ex_ld_max_before_year_with_ih_binTrue        -34.887864   1.228090 -28.408228
Agricultural.and.Biological.Sciences         -35.513798   0.867453 -40.940314
Arts.and.Humanities                          -57.334376   3.297162 -17.389006
Biochemistry..Genetics.and.Molecular.Biology -47.632552   0.786566 -60.557589
Business..Management.and.Accounting           21.038945   4.897137   4.296172
Chemical.Engineering                         -21.625134   0.792860 -27.274858
Chemistry                                    -22.497052   0.820956 -27.403493
Computer.Science                             -41.117689   2.314831 -17.762718
Decision.Sciences                              3.063107  56.630256   0.054090
Dentistry                                    -38.787664   2.399405 -16.165534
Earth.and.Planetary.Sciences                 -33.618210   1.340510 -25.078674
Economics..Econometrics.and.Finance           -7.973693  15.037381  -0.530258
Energy                                       -23.085746   0.656758 -35.151053
Engineering                                  -30.644831   0.864322 -35.455348
Environmental.Science                        -24.953501   1.196114 -20.862148
Health.Professions                           -43.944135   4.723935  -9.302442
Immunology.and.Microbiology                  -35.550436   1.549476 -22.943516
Materials.Science                            -31.989149   0.929181 -34.427236
Mathematics                                    1.723511  10.282411   0.167617
Medicine                                     -37.261371   1.380492 -26.991378
Neuroscience                                 -35.612426   1.386463 -25.685802
Nursing                                      -40.119793   1.205132 -33.290799
Pharmacology..Toxicology.and.Pharmaceutics   -28.378927   1.849769 -15.341878
Physics.and.Astronomy                         15.406074   0.852548  18.070632
Psychology                                   -11.179601   6.358721  -1.758152
Social.Sciences                              -25.263608   9.119569  -2.770263
Veterinary                                   -37.124856   7.640067  -4.859232
                                               Pr(>|t|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          1.5545e-03 **
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.7686e-07 ***
lnnum_reference                               < 2.2e-16 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                      3.6955e-01
lnmean_career_age                            3.3945e-02 *
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       6.1314e-04 ***
ex_ld_bin_gsGlobalNorth                      2.1050e-12 ***
ex_ld_bin_sameCSame                          1.8687e-11 ***
knowledge_proximity_mean                      < 2.2e-16 ***
lnex_ld_avg_before_year_prod_fac             4.6595e-02 *
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          1.7384e-05 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            9.5686e-01
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          5.9593e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                             < 2.2e-16 ***
Mathematics                                  8.6688e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   7.8723e-02 .
Social.Sciences                              5.6015e-03 **
Veterinary                                   1.1791e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 154.8     Adj. R2: 0.064155
              Within R2: 0.063235

In [43]:
# # 每组 reg_class 的平均预测概率
# margins_eff_ps <- avg_comparisons(model_ps, variables = "CoType", comparison = 'ratio')
# margins_eff_ps

In [44]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_ps_comp_ratio.csv")
# write.csv(margins_eff_ps, fname, row.names = FALSE)

In [45]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ps,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                 & -10.7$^{***}$\\
                                                       & (0.709)\\
   CoTypeParticipation                                 & -3.69$^{***}$\\
                                                       & (1.17)\\
   lnnum\_author                                       & 23.5$^{***}$\\
                                                       & (0.823)\\
   internationalinternational                          & 4.10$^{***}$\\
                                                       & (0.785)\\
   lnnum\_reference                                    & -19.4$^{***}$\\
                                                       & (1.34)\\
   num\_fac                                            & -13.3$^{***}$\\
                                                       & (0.330)\\
   SDGTrue                                             & -0.572\\
                                                       & (0.638)\\
   lnmean\_career\_age                                 & 2.51$^{**}$\\
                                                       & (1.18)\\
   lnex\_ld\_avg\_avgimpact                            & 11.0$^{***}$\\
                                                       & (0.613)\\
   lnex\_ld\_avg\_insthindex                           & 2.02$^{***}$\\
                                                       & (0.590)\\
   ex\_ld\_bin\_gsGlobalNorth                          & -9.06$^{***}$\\
                                                       & (1.29)\\
   ex\_ld\_bin\_sameCSame                              & 5.10$^{***}$\\
                                                       & (0.760)\\
   knowledge\_proximity\_mean                          & 256.7$^{***}$\\
                                                       & (13.1)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & 0.928$^{**}$\\
                                                       & (0.466)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & -34.9$^{***}$\\
                                                       & (1.23)\\
   Agricultural.and.Biological.Sciences                & -35.5$^{***}$\\
                                                       & (0.867)\\
   Arts.and.Humanities                                 & -57.3$^{***}$\\
                                                       & (3.30)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -47.6$^{***}$\\
                                                       & (0.787)\\
   Business..Management.and.Accounting                 & 21.0$^{***}$\\
                                                       & (4.90)\\
   Chemical.Engineering                                & -21.6$^{***}$\\
                                                       & (0.793)\\
   Chemistry                                           & -22.5$^{***}$\\
                                                       & (0.821)\\
   Computer.Science                                    & -41.1$^{***}$\\
                                                       & (2.31)\\
   Decision.Sciences                                   & 3.06\\
                                                       & (56.6)\\
   Dentistry                                           & -38.8$^{***}$\\
                                                       & (2.40)\\
   Earth.and.Planetary.Sciences                        & -33.6$^{***}$\\
                                                       & (1.34)\\
   Economics..Econometrics.and.Finance                 & -7.97\\
                                                       & (15.0)\\
   Energy                                              & -23.1$^{***}$\\
                                                       & (0.657)\\
   Engineering                                         & -30.6$^{***}$\\
                                                       & (0.864)\\
   Immunology.and.Microbiology                         & -35.6$^{***}$\\
                                                       & (1.55)\\
   Materials.Science                                   & -32.0$^{***}$\\
                                                       & (0.929)\\
   Mathematics                                         & 1.72\\
                                                       & (10.3)\\
   Medicine                                            & -37.3$^{***}$\\
                                                       & (1.38)\\
   Neuroscience                                        & -35.6$^{***}$\\
                                                       & (1.39)\\
   Nursing                                             & -40.1$^{***}$\\
                                                       & (1.21)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & -28.4$^{***}$\\
                                                       & (1.85)\\
   Physics.and.Astronomy                               & 15.4$^{***}$\\
                                                       & (0.853)\\
   Psychology                                          & -11.2$^{*}$\\
                                                       & (6.36)\\
   Social.Sciences                                     & -25.3$^{***}$\\
                                                       & (9.12)\\
   Veterinary                                          & -37.1$^{***}$\\
                                                       & (7.64)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 253,483\\
   R$^2$                                               & 0.06449\\
   Within R$^2$                                        & 0.06323\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [46]:
fml <- as.formula(
  paste0("novel_uzzi ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ls <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Life.Sciences==1), ], vcov = "hetero")
summary(model_ls)

NOTE: 12 observations removed because of NA values (LHS: 12).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 77,579
Fixed-effects: PublishedYear: 49
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error    t value
CoTypeCollaboration                           -1.427616   0.563684  -2.532653
CoTypeParticipation                           -0.651302   0.718016  -0.907085
lnnum_author                                  -5.595249   0.431546 -12.965592
internationalinternational                    -1.220636   0.318983  -3.826650
lnnum_reference                               -9.147517   0.854968 -10.699244
num_fac                                        0.354596   0.200630   1.767411
SDGTrue                                       -3.050865   0.343021  -8.894091
lnmean_career_age                             -2.214193   0.586946  -3.772396
lnex_ld_avg_avgimpact                          6.250787   0.350737  17.821880
lnex_ld_avg_insthindex                         3.270029   0.379366   8.619712
ex_ld_bin_gsGlobalNorth                       -1.206942   0.618337  -1.951918
ex_ld_bin_sameCSame                            2.158915   0.326973   6.602726
knowledge_proximity_mean                       6.610767   6.144967   1.075802
lnex_ld_avg_before_year_prod_fac              -0.225650   0.289624  -0.779113
ex_ld_max_before_year_with_ih_binTrue         -4.022510   0.401612 -10.015903
Agricultural.and.Biological.Sciences          -6.736119   0.452821 -14.875883
Arts.and.Humanities                           -8.742818   4.461046  -1.959813
Biochemistry..Genetics.and.Molecular.Biology  -0.941926   0.476997  -1.974699
Business..Management.and.Accounting          106.573948  75.582835   1.410028
Chemical.Engineering                          -4.854261   2.554069  -1.900599
Chemistry                                     -5.969308   0.775580  -7.696573
Computer.Science                             -12.788406   0.740694 -17.265433
Decision.Sciences                             -0.344119   9.098113  -0.037823
Dentistry                                     -5.078902   2.042675  -2.486398
Earth.and.Planetary.Sciences                 -12.089028   1.155162 -10.465219
Energy                                        -7.003688   1.009381  -6.938597
Engineering                                   -8.485058   0.865031  -9.808959
Environmental.Science                          0.096287   0.539390   0.178510
Health.Professions                            -7.502160   2.165689  -3.464099
Immunology.and.Microbiology                   -4.390135   0.459936  -9.545103
Materials.Science                             -2.713683   0.531506  -5.105652
Mathematics                                   -0.499107   9.936888  -0.050228
Medicine                                      -9.306831   0.332561 -27.985355
Neuroscience                                  -6.496698   0.506464 -12.827565
Nursing                                       -9.919728   0.629587 -15.755941
Pharmacology..Toxicology.and.Pharmaceutics    -5.932132   0.959426  -6.183002
Physics.and.Astronomy                         -5.793308   0.830218  -6.978058
Psychology                                    -6.433595   2.004946  -3.208862
Social.Sciences                               -9.340811   2.273498  -4.108563
Veterinary                                    -4.881431   1.806327  -2.702408
                                               Pr(>|t|)
CoTypeCollaboration                          1.1322e-02 *
CoTypeParticipation                          3.6436e-01
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.3000e-04 ***
lnnum_reference                               < 2.2e-16 ***
num_fac                                      7.7163e-02 .
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            1.6181e-04 ***
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                        < 2.2e-16 ***
ex_ld_bin_gsGlobalNorth                      5.0952e-02 .
ex_ld_bin_sameCSame                          4.0626e-11 ***
knowledge_proximity_mean                     2.8202e-01
lnex_ld_avg_before_year_prod_fac             4.3592e-01
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                          5.0021e-02 .
Biochemistry..Genetics.and.Molecular.Biology 4.8306e-02 *
Business..Management.and.Accounting          1.5854e-01
Chemical.Engineering                         5.7358e-02 .
Chemistry                                    1.4141e-14 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            9.6983e-01
Dentistry                                    1.2906e-02 *
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Energy                                       3.9911e-12 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                        8.5832e-01
Health.Professions                           5.3230e-04 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                            3.3043e-07 ***
Mathematics                                  9.5994e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   6.3207e-10 ***
Physics.and.Astronomy                        3.0168e-12 ***
Psychology                                   1.3332e-03 **
Social.Sciences                              3.9854e-05 ***
Veterinary                                   6.8854e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 47.1     Adj. R2: 0.045335
             Within R2: 0.041239

In [47]:
# # 每组 reg_class 的平均预测概率
# margins_eff_ls <- avg_comparisons(model_ls, variables = "CoType", comparison = 'ratio')
# margins_eff_ls

In [48]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_ls_comp_ratio.csv")
# write.csv(margins_eff_ls, fname, row.names = FALSE)

In [49]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ls,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                 & -1.43$^{**}$\\
                                                       & (0.564)\\
   CoTypeParticipation                                 & -0.651\\
                                                       & (0.718)\\
   lnnum\_author                                       & -5.60$^{***}$\\
                                                       & (0.432)\\
   internationalinternational                          & -1.22$^{***}$\\
                                                       & (0.319)\\
   lnnum\_reference                                    & -9.15$^{***}$\\
                                                       & (0.855)\\
   num\_fac                                            & 0.355$^{*}$\\
                                                       & (0.201)\\
   SDGTrue                                             & -3.05$^{***}$\\
                                                       & (0.343)\\
   lnmean\_career\_age                                 & -2.21$^{***}$\\
                                                       & (0.587)\\
   lnex\_ld\_avg\_avgimpact                            & 6.25$^{***}$\\
                                                       & (0.351)\\
   lnex\_ld\_avg\_insthindex                           & 3.27$^{***}$\\
                                                       & (0.379)\\
   ex\_ld\_bin\_gsGlobalNorth                          & -1.21$^{*}$\\
                                                       & (0.618)\\
   ex\_ld\_bin\_sameCSame                              & 2.16$^{***}$\\
                                                       & (0.327)\\
   knowledge\_proximity\_mean                          & 6.61\\
                                                       & (6.14)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.226\\
                                                       & (0.290)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & -4.02$^{***}$\\
                                                       & (0.402)\\
   Agricultural.and.Biological.Sciences                & -6.74$^{***}$\\
                                                       & (0.453)\\
   Arts.and.Humanities                                 & -8.74$^{*}$\\
                                                       & (4.46)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -0.942$^{**}$\\
                                                       & (0.477)\\
   Business..Management.and.Accounting                 & 106.6\\
                                                       & (75.6)\\
   Chemical.Engineering                                & -4.85$^{*}$\\
                                                       & (2.55)\\
   Chemistry                                           & -5.97$^{***}$\\
                                                       & (0.776)\\
   Computer.Science                                    & -12.8$^{***}$\\
                                                       & (0.741)\\
   Decision.Sciences                                   & -0.344\\
                                                       & (9.10)\\
   Dentistry                                           & -5.08$^{**}$\\
                                                       & (2.04)\\
   Earth.and.Planetary.Sciences                        & -12.1$^{***}$\\
                                                       & (1.16)\\
   Energy                                              & -7.00$^{***}$\\
                                                       & (1.01)\\
   Engineering                                         & -8.49$^{***}$\\
                                                       & (0.865)\\
   Immunology.and.Microbiology                         & -4.39$^{***}$\\
                                                       & (0.460)\\
   Materials.Science                                   & -2.71$^{***}$\\
                                                       & (0.532)\\
   Mathematics                                         & -0.499\\
                                                       & (9.94)\\
   Medicine                                            & -9.31$^{***}$\\
                                                       & (0.333)\\
   Neuroscience                                        & -6.50$^{***}$\\
                                                       & (0.506)\\
   Nursing                                             & -9.92$^{***}$\\
                                                       & (0.630)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & -5.93$^{***}$\\
                                                       & (0.959)\\
   Physics.and.Astronomy                               & -5.79$^{***}$\\
                                                       & (0.830)\\
   Psychology                                          & -6.43$^{***}$\\
                                                       & (2.00)\\
   Social.Sciences                                     & -9.34$^{***}$\\
                                                       & (2.27)\\
   Veterinary                                          & -4.88$^{***}$\\
                                                       & (1.81)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 77,579\\
   R$^2$                                               & 0.04642\\
   Within R$^2$                                        & 0.04124\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [50]:
fml <- as.formula(
  paste0("novel_uzzi ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_hs <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Health.Sciences==1), ], vcov = "hetero")
summary(model_hs)

NOTE: 8 observations removed because of NA values (LHS: 8).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 33,409
Fixed-effects: PublishedYear: 46
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error   t value
CoTypeCollaboration                           -6.989213   1.852211 -3.773443
CoTypeParticipation                           -4.427218   1.995193 -2.218943
lnnum_author                                  -2.612084   1.100981 -2.372506
internationalinternational                     1.182021   0.919404  1.285639
lnnum_reference                              -12.416814   2.238838 -5.546097
num_fac                                       -0.187018   0.359222 -0.520620
SDGTrue                                       -2.292495   0.829648 -2.763214
lnmean_career_age                             -1.072274   1.068849 -1.003204
lnex_ld_avg_avgimpact                          2.426588   0.656437  3.696607
lnex_ld_avg_insthindex                         2.822234   0.723453  3.901057
ex_ld_bin_gsGlobalNorth                       -2.960626   3.201131 -0.924869
ex_ld_bin_sameCSame                            3.164424   0.699325  4.524970
knowledge_proximity_mean                     -26.005403  15.500206 -1.677746
lnex_ld_avg_before_year_prod_fac              -0.456266   0.787825 -0.579147
ex_ld_max_before_year_with_ih_binTrue         -4.087667   1.044955 -3.911811
Agricultural.and.Biological.Sciences           0.074323   0.844290  0.088030
Arts.and.Humanities                          -20.938736   4.099780 -5.107283
Biochemistry..Genetics.and.Molecular.Biology  -1.153628   0.696642 -1.655985
Business..Management.and.Accounting           51.022854  17.642548  2.892034
Chemical.Engineering                           1.107832   5.265283  0.210403
Chemistry                                      0.511507   0.937441  0.545642
Computer.Science                             -10.352115   1.167973 -8.863316
Decision.Sciences                             -8.534751   6.469522 -1.319224
Dentistry                                     -4.080487   2.893619 -1.410167
Earth.and.Planetary.Sciences                 -12.090677   1.967146 -6.146303
Economics..Econometrics.and.Finance          -57.208723   5.817122 -9.834541
Energy                                         4.487371   3.111861  1.442022
Engineering                                  -11.316342   3.152504 -3.589636
Environmental.Science                         -1.113435   1.028947 -1.082111
Health.Professions                            -7.971020   3.731233 -2.136296
Immunology.and.Microbiology                    1.213551   0.756319  1.604548
Materials.Science                              5.943694   0.923358  6.437043
Mathematics                                   -6.098526   9.204908 -0.662530
Medicine                                      -4.162056   1.490328 -2.792711
Neuroscience                                  -4.115180   0.792377 -5.193462
Nursing                                      -11.128423   1.120388 -9.932653
Pharmacology..Toxicology.and.Pharmaceutics    -7.000788   1.388611 -5.041576
Physics.and.Astronomy                         22.246322   4.746061  4.687323
Psychology                                    -6.765636   3.047045 -2.220392
Social.Sciences                              -11.250833   3.602692 -3.122896
Veterinary                                    -5.593661   1.886922 -2.964437
                                               Pr(>|t|)
CoTypeCollaboration                          1.6129e-04 ***
CoTypeParticipation                          2.6497e-02 *
lnnum_author                                 1.7674e-02 *
internationalinternational                   1.9858e-01
lnnum_reference                              2.9433e-08 ***
num_fac                                      6.0263e-01
SDGTrue                                      5.7267e-03 **
lnmean_career_age                            3.1577e-01
lnex_ld_avg_avgimpact                        2.1885e-04 ***
lnex_ld_avg_insthindex                       9.5961e-05 ***
ex_ld_bin_gsGlobalNorth                      3.5504e-01
ex_ld_bin_sameCSame                          6.0612e-06 ***
knowledge_proximity_mean                     9.3406e-02 .
lnex_ld_avg_before_year_prod_fac             5.6249e-01
ex_ld_max_before_year_with_ih_binTrue        9.1788e-05 ***
Agricultural.and.Biological.Sciences         9.2985e-01
Arts.and.Humanities                          3.2862e-07 ***
Biochemistry..Genetics.and.Molecular.Biology 9.7734e-02 .
Business..Management.and.Accounting          3.8300e-03 **
Chemical.Engineering                         8.3335e-01
Chemistry                                    5.8532e-01
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            1.8710e-01
Dentistry                                    1.5850e-01
Earth.and.Planetary.Sciences                 8.0208e-10 ***
Economics..Econometrics.and.Finance           < 2.2e-16 ***
Energy                                       1.4931e-01
Engineering                                  3.3162e-04 ***
Environmental.Science                        2.7921e-01
Health.Professions                           3.2663e-02 *
Immunology.and.Microbiology                  1.0860e-01
Materials.Science                            1.2348e-10 ***
Mathematics                                  5.0764e-01
Medicine                                     5.2298e-03 **
Neuroscience                                 2.0763e-07 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   4.6413e-07 ***
Physics.and.Astronomy                        2.7790e-06 ***
Psychology                                   2.6399e-02 *
Social.Sciences                              1.7923e-03 **
Veterinary                                   3.0345e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 72.8     Adj. R2: 0.019056
             Within R2: 0.01899

In [51]:
# # 每组 reg_class 的平均预测概率
# margins_eff_hs <- avg_comparisons(model_hs, variables = "CoType", comparison = 'ratio')
# margins_eff_hs

In [52]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_hs_comp_ratio.csv")
# write.csv(margins_eff_hs, fname, row.names = FALSE)

In [53]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_hs,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                 & -6.99$^{***}$\\
                                                       & (1.85)\\
   CoTypeParticipation                                 & -4.43$^{**}$\\
                                                       & (2.00)\\
   lnnum\_author                                       & -2.61$^{**}$\\
                                                       & (1.10)\\
   internationalinternational                          & 1.18\\
                                                       & (0.919)\\
   lnnum\_reference                                    & -12.4$^{***}$\\
                                                       & (2.24)\\
   num\_fac                                            & -0.187\\
                                                       & (0.359)\\
   SDGTrue                                             & -2.29$^{***}$\\
                                                       & (0.830)\\
   lnmean\_career\_age                                 & -1.07\\
                                                       & (1.07)\\
   lnex\_ld\_avg\_avgimpact                            & 2.43$^{***}$\\
                                                       & (0.656)\\
   lnex\_ld\_avg\_insthindex                           & 2.82$^{***}$\\
                                                       & (0.723)\\
   ex\_ld\_bin\_gsGlobalNorth                          & -2.96\\
                                                       & (3.20)\\
   ex\_ld\_bin\_sameCSame                              & 3.16$^{***}$\\
                                                       & (0.699)\\
   knowledge\_proximity\_mean                          & -26.0$^{*}$\\
                                                       & (15.5)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & -0.456\\
                                                       & (0.788)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & -4.09$^{***}$\\
                                                       & (1.04)\\
   Agricultural.and.Biological.Sciences                & 0.074\\
                                                       & (0.844)\\
   Arts.and.Humanities                                 & -20.9$^{***}$\\
                                                       & (4.10)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -1.15$^{*}$\\
                                                       & (0.697)\\
   Business..Management.and.Accounting                 & 51.0$^{***}$\\
                                                       & (17.6)\\
   Chemical.Engineering                                & 1.11\\
                                                       & (5.27)\\
   Chemistry                                           & 0.512\\
                                                       & (0.937)\\
   Computer.Science                                    & -10.4$^{***}$\\
                                                       & (1.17)\\
   Decision.Sciences                                   & -8.53\\
                                                       & (6.47)\\
   Dentistry                                           & -4.08\\
                                                       & (2.89)\\
   Earth.and.Planetary.Sciences                        & -12.1$^{***}$\\
                                                       & (1.97)\\
   Economics..Econometrics.and.Finance                 & -57.2$^{***}$\\
                                                       & (5.82)\\
   Energy                                              & 4.49\\
                                                       & (3.11)\\
   Engineering                                         & -11.3$^{***}$\\
                                                       & (3.15)\\
   Immunology.and.Microbiology                         & 1.21\\
                                                       & (0.756)\\
   Materials.Science                                   & 5.94$^{***}$\\
                                                       & (0.923)\\
   Mathematics                                         & -6.10\\
                                                       & (9.20)\\
   Medicine                                            & -4.16$^{***}$\\
                                                       & (1.49)\\
   Neuroscience                                        & -4.12$^{***}$\\
                                                       & (0.792)\\
   Nursing                                             & -11.1$^{***}$\\
                                                       & (1.12)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & -7.00$^{***}$\\
                                                       & (1.39)\\
   Physics.and.Astronomy                               & 22.2$^{***}$\\
                                                       & (4.75)\\
   Psychology                                          & -6.77$^{**}$\\
                                                       & (3.05)\\
   Social.Sciences                                     & -11.3$^{***}$\\
                                                       & (3.60)\\
   Veterinary                                          & -5.59$^{***}$\\
                                                       & (1.89)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 33,409\\
   R$^2$                                               & 0.02158\\
   Within R$^2$                                        & 0.01899\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [54]:
fml <- as.formula(
  paste0("novel_uzzi ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_nps <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==0), ], vcov = "hetero")
summary(model_nps)

NOTE: 6 observations removed because of NA values (LHS: 6).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 41,298
Fixed-effects: PublishedYear: 44
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error    t value
CoTypeCollaboration                           -3.414270   0.798505  -4.275830
CoTypeParticipation                           -2.548076   1.849937  -1.377385
lnnum_author                                  -6.769396   0.518203 -13.063219
internationalinternational                    -1.484360   0.396095  -3.747482
lnnum_reference                               -6.395976   1.684931  -3.795986
num_fac                                        0.860175   0.271122   3.172648
SDGTrue                                       -4.754423   0.413033 -11.511009
lnmean_career_age                             -4.850856   0.617512  -7.855482
lnex_ld_avg_avgimpact                          7.331620   0.339462  21.597749
lnex_ld_avg_insthindex                         3.183849   0.321926   9.890008
ex_ld_bin_gsGlobalNorth                       -0.951871   0.807113  -1.179353
ex_ld_bin_sameCSame                            2.365081   0.520806   4.541197
knowledge_proximity_mean                      36.791198  11.306539   3.253975
lnex_ld_avg_before_year_prod_fac               0.229310   0.250560   0.915189
ex_ld_max_before_year_with_ih_binTrue         -2.869540   0.537406  -5.339617
Agricultural.and.Biological.Sciences          -4.009395   0.615981  -6.508959
Arts.and.Humanities                          101.238128 111.819130   0.905374
Biochemistry..Genetics.and.Molecular.Biology   1.853666   0.774738   2.392638
Business..Management.and.Accounting           26.945254   7.821519   3.445016
Decision.Sciences                              4.259041  19.197515   0.221854
Dentistry                                     -3.719215   8.181633  -0.454581
Health.Professions                            -8.417432   2.089126  -4.029165
Immunology.and.Microbiology                   -2.890673   0.499525  -5.786846
Medicine                                     -10.331724   0.585793 -17.637153
Neuroscience                                  -7.639061   0.556386 -13.729793
Nursing                                      -10.101573   0.787729 -12.823670
Pharmacology..Toxicology.and.Pharmaceutics    -9.536853   0.966686  -9.865514
Psychology                                    -4.274684   2.945601  -1.451209
Social.Sciences                              -61.763839  61.766568  -0.999956
Veterinary                                    -5.071907   1.649379  -3.075040
                                               Pr(>|t|)
CoTypeCollaboration                          1.9085e-05 ***
CoTypeParticipation                          1.6840e-01
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.7886e-04 ***
lnnum_reference                              1.4727e-04 ***
num_fac                                      1.5117e-03 **
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            4.0784e-15 ***
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                        < 2.2e-16 ***
ex_ld_bin_gsGlobalNorth                      2.3826e-01
ex_ld_bin_sameCSame                          5.6094e-06 ***
knowledge_proximity_mean                     1.1389e-03 **
lnex_ld_avg_before_year_prod_fac             3.6010e-01
ex_ld_max_before_year_with_ih_binTrue        9.3635e-08 ***
Agricultural.and.Biological.Sciences         7.6540e-11 ***
Arts.and.Humanities                          3.6527e-01
Biochemistry..Genetics.and.Molecular.Biology 1.6732e-02 *
Business..Management.and.Accounting          5.7159e-04 ***
Decision.Sciences                            8.2443e-01
Dentistry                                    6.4941e-01
Health.Professions                           5.6076e-05 ***
Immunology.and.Microbiology                  7.2238e-09 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Psychology                                   1.4673e-01
Social.Sciences                              3.1734e-01
Veterinary                                   2.1061e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 47.2     Adj. R2: 0.057713
             Within R2: 0.054014

In [55]:
# # 每组 reg_class 的平均预测概率
# margins_eff_nps <- avg_comparisons(model_nps, variables = "CoType", comparison = 'ratio')
# margins_eff_nps

In [56]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_nps_comp_ratio.csv")
# write.csv(margins_eff_nps, fname, row.names = FALSE)

In [57]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_nps,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                 & -3.41$^{***}$\\
                                                       & (0.799)\\
   CoTypeParticipation                                 & -2.55\\
                                                       & (1.85)\\
   lnnum\_author                                       & -6.77$^{***}$\\
                                                       & (0.518)\\
   internationalinternational                          & -1.48$^{***}$\\
                                                       & (0.396)\\
   lnnum\_reference                                    & -6.40$^{***}$\\
                                                       & (1.68)\\
   num\_fac                                            & 0.860$^{***}$\\
                                                       & (0.271)\\
   SDGTrue                                             & -4.75$^{***}$\\
                                                       & (0.413)\\
   lnmean\_career\_age                                 & -4.85$^{***}$\\
                                                       & (0.618)\\
   lnex\_ld\_avg\_avgimpact                            & 7.33$^{***}$\\
                                                       & (0.339)\\
   lnex\_ld\_avg\_insthindex                           & 3.18$^{***}$\\
                                                       & (0.322)\\
   ex\_ld\_bin\_gsGlobalNorth                          & -0.952\\
                                                       & (0.807)\\
   ex\_ld\_bin\_sameCSame                              & 2.37$^{***}$\\
                                                       & (0.521)\\
   knowledge\_proximity\_mean                          & 36.8$^{***}$\\
                                                       & (11.3)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & 0.229\\
                                                       & (0.251)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & -2.87$^{***}$\\
                                                       & (0.537)\\
   Agricultural.and.Biological.Sciences                & -4.01$^{***}$\\
                                                       & (0.616)\\
   Arts.and.Humanities                                 & 101.2\\
                                                       & (111.8)\\
   Biochemistry..Genetics.and.Molecular.Biology        & 1.85$^{**}$\\
                                                       & (0.775)\\
   Business..Management.and.Accounting                 & 26.9$^{***}$\\
                                                       & (7.82)\\
   Decision.Sciences                                   & 4.26\\
                                                       & (19.2)\\
   Dentistry                                           & -3.72\\
                                                       & (8.18)\\
   Immunology.and.Microbiology                         & -2.89$^{***}$\\
                                                       & (0.500)\\
   Medicine                                            & -10.3$^{***}$\\
                                                       & (0.586)\\
   Neuroscience                                        & -7.64$^{***}$\\
                                                       & (0.556)\\
   Nursing                                             & -10.1$^{***}$\\
                                                       & (0.788)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & -9.54$^{***}$\\
                                                       & (0.967)\\
   Psychology                                          & -4.27\\
                                                       & (2.95)\\
   Social.Sciences                                     & -61.8\\
                                                       & (61.8)\\
   Veterinary                                          & -5.07$^{***}$\\
                                                       & (1.65)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 41,298\\
   R$^2$                                               & 0.05938\\
   Within R$^2$                                        & 0.05401\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H3: Too much will suppress

# H3a: Participation too much not good

In [58]:
fml <- as.formula(
  paste0("novel_uzzi ~ ratio_fac_scientist + I(ratio_fac_scientist^2) +  ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_h3_pratio <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], vcov = "hetero")
summary(model_h3_pratio)

NOTE: 98 observations removed because of NA values (LHS: 98).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 294,781
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    t value
ratio_fac_scientist                          -49.16323   4.693222 -10.475369
I(ratio_fac_scientist^2)                      45.21122   8.755500   5.163751
lnnum_author                                  20.82863   0.754383  27.610170
internationalinternational                     3.41035   0.670711   5.084681
lnnum_reference                              -18.09063   1.211922 -14.927222
num_fac                                      -11.47137   0.288355 -39.782120
SDGTrue                                       -1.51644   0.554286  -2.735848
lnmean_career_age                              1.66885   1.024643   1.628713
lnex_ld_avg_avgimpact                          7.81831   0.489160  15.983125
lnex_ld_avg_insthindex                         2.34477   0.511548   4.583679
ex_ld_bin_gsGlobalNorth                       -9.05628   1.173675  -7.716176
ex_ld_bin_sameCSame                            4.68937   0.645221   7.267842
knowledge_proximity_mean                     219.76732  11.278386  19.485706
lnex_ld_avg_before_year_prod_fac               1.29533   0.417242   3.104508
ex_ld_max_before_year_with_ih_binTrue        -27.57812   0.959290 -28.748487
Agricultural.and.Biological.Sciences         -31.56761   0.648715 -48.661771
Arts.and.Humanities                          -46.14885   6.550001  -7.045625
Biochemistry..Genetics.and.Molecular.Biology -44.08442   0.757133 -58.225444
Business..Management.and.Accounting           24.29805   4.889005   4.969936
Chemical.Engineering                         -17.73983   0.741610 -23.920699
Chemistry                                    -16.75762   0.712677 -23.513626
Computer.Science                             -32.85024   2.191729 -14.988273
Decision.Sciences                              6.13317  54.138586   0.113286
Dentistry                                    -33.25091   3.307810 -10.052242
Earth.and.Planetary.Sciences                 -28.79711   1.285772 -22.396744
Economics..Econometrics.and.Finance           -4.65612  14.976423  -0.310897
Energy                                       -17.82581   0.574223 -31.043355
Engineering                                  -24.21115   0.756316 -32.011942
Environmental.Science                        -15.52433   1.018303 -15.245285
Health.Professions                           -40.93927   3.780118 -10.830157
Immunology.and.Microbiology                  -33.21047   0.760451 -43.672068
Materials.Science                            -25.68104   0.775529 -33.114234
Mathematics                                    8.45449  10.257534   0.824222
Medicine                                     -37.79898   0.797146 -47.417880
Neuroscience                                 -27.84861   0.749002 -37.180943
Nursing                                      -29.17608   0.825100 -35.360675
Pharmacology..Toxicology.and.Pharmaceutics   -23.39253   1.154677 -20.258928
Physics.and.Astronomy                         22.51859   0.832797  27.039707
Psychology                                   -27.75848   3.483513  -7.968530
Social.Sciences                              -18.62148   7.701493  -2.417905
Veterinary                                   -31.04891   3.054021 -10.166566
                                               Pr(>|t|)
ratio_fac_scientist                           < 2.2e-16 ***
I(ratio_fac_scientist^2)                     2.4221e-07 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   3.6847e-07 ***
lnnum_reference                               < 2.2e-16 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                      6.2224e-03 **
lnmean_career_age                            1.0337e-01
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       4.5705e-06 ***
ex_ld_bin_gsGlobalNorth                      1.2024e-14 ***
ex_ld_bin_sameCSame                          3.6617e-13 ***
knowledge_proximity_mean                      < 2.2e-16 ***
lnex_ld_avg_before_year_prod_fac             1.9061e-03 **
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                          1.8503e-12 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          6.7012e-07 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            9.0980e-01
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.5588e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                             < 2.2e-16 ***
Mathematics                                  4.0981e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.6114e-15 ***
Social.Sciences                              1.5611e-02 *
Veterinary                                    < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 145.1     Adj. R2: 0.061343
              Within R2: 0.060408

In [59]:
# library(marginaleffects)
# # 设置 draw = FALSE，直接拦截绘图数据
# plot_data <- plot_predictions(model_h3_pratio, condition = "ratio_fac_scientist", draw = FALSE)
# # 选出我们最需要的几列：x轴变量、预测值(estimate)、置信区间下限(conf.low)、上限(conf.high)
# export_data <- plot_data[, c("ratio_fac_scientist", "estimate", "conf.low", "conf.high")]
# # # 导出为 CSV 文件，给 Python 准备
# write.csv(export_data, "R_ex_ld_h3_pred_pratio.csv", row.names = FALSE)
# export_data
# # print("数据已成功导出！")
# # head(export_data)

In [60]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_h3_pratio,
                           keep = c("ratio_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   ratio\_fac\_scientist                               & -49.2$^{***}$\\
                                                       & (4.69)\\
   ratio\_fac\_scientist square                        & 45.2$^{***}$\\
                                                       & (8.76)\\
   lnnum\_author                                       & 20.8$^{***}$\\
                                                       & (0.754)\\
   internationalinternational                          & 3.41$^{***}$\\
                                                       & (0.671)\\
   lnnum\_reference                                    & -18.1$^{***}$\\
                                                       & (1.21)\\
   num\_fac                                            & -11.5$^{***}$\\
                                                       & (0.288)\\
   SDGTrue                                             & -1.52$^{***}$\\
                                                       & (0.554)\\
   lnmean\_career\_age                                 & 1.67\\
                                                       & (1.02)\\
   lnex\_ld\_avg\_avgimpact                            & 7.82$^{***}$\\
                                                       & (0.489)\\
   lnex\_ld\_avg\_insthindex                           & 2.34$^{***}$\\
                                                       & (0.512)\\
   ex\_ld\_bin\_gsGlobalNorth                          & -9.06$^{***}$\\
                                                       & (1.17)\\
   ex\_ld\_bin\_sameCSame                              & 4.69$^{***}$\\
                                                       & (0.645)\\
   knowledge\_proximity\_mean                          & 219.8$^{***}$\\
                                                       & (11.3)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & 1.30$^{***}$\\
                                                       & (0.417)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & -27.6$^{***}$\\
                                                       & (0.959)\\
   Agricultural.and.Biological.Sciences                & -31.6$^{***}$\\
                                                       & (0.649)\\
   Arts.and.Humanities                                 & -46.1$^{***}$\\
                                                       & (6.55)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -44.1$^{***}$\\
                                                       & (0.757)\\
   Business..Management.and.Accounting                 & 24.3$^{***}$\\
                                                       & (4.89)\\
   Chemical.Engineering                                & -17.7$^{***}$\\
                                                       & (0.742)\\
   Chemistry                                           & -16.8$^{***}$\\
                                                       & (0.713)\\
   Computer.Science                                    & -32.9$^{***}$\\
                                                       & (2.19)\\
   Decision.Sciences                                   & 6.13\\
                                                       & (54.1)\\
   Dentistry                                           & -33.3$^{***}$\\
                                                       & (3.31)\\
   Earth.and.Planetary.Sciences                        & -28.8$^{***}$\\
                                                       & (1.29)\\
   Economics..Econometrics.and.Finance                 & -4.66\\
                                                       & (15.0)\\
   Energy                                              & -17.8$^{***}$\\
                                                       & (0.574)\\
   Engineering                                         & -24.2$^{***}$\\
                                                       & (0.756)\\
   Immunology.and.Microbiology                         & -33.2$^{***}$\\
                                                       & (0.760)\\
   Materials.Science                                   & -25.7$^{***}$\\
                                                       & (0.776)\\
   Mathematics                                         & 8.45\\
                                                       & (10.3)\\
   Medicine                                            & -37.8$^{***}$\\
                                                       & (0.797)\\
   Neuroscience                                        & -27.8$^{***}$\\
                                                       & (0.749)\\
   Nursing                                             & -29.2$^{***}$\\
                                                       & (0.825)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & -23.4$^{***}$\\
                                                       & (1.15)\\
   Physics.and.Astronomy                               & 22.5$^{***}$\\
                                                       & (0.833)\\
   Psychology                                          & -27.8$^{***}$\\
                                                       & (3.48)\\
   Social.Sciences                                     & -18.6$^{**}$\\
                                                       & (7.70)\\
   Veterinary                                          & -31.0$^{***}$\\
                                                       & (3.05)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 294,781\\
   R$^2$                                               & 0.06163\\
   Within R$^2$                                        & 0.06041\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H3b: Lead too much not good

In [61]:
fml <- as.formula(
  paste0("novel_uzzi ~ fac_scientist_lead_ratio + I(fac_scientist_lead_ratio^2) +  ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_h3_lratio <- feols(fml, data = data[(data$paper_type =='article')&(data$CoType_Service==0)&(data$knowledge_proximity_mean>0), ], vcov = "hetero")
summary(model_h3_lratio)

NOTE: 14 observations removed because of NA values (LHS: 14).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 78,519
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error    t value
fac_scientist_lead_ratio                      11.489314   6.756742   1.700422
I(fac_scientist_lead_ratio^2)                 -7.083996   9.173371  -0.772235
lnnum_author                                  41.356115   1.081579  38.236802
internationalinternational                    -0.393851   1.183209  -0.332867
lnnum_reference                              -16.324329   2.379446  -6.860560
num_fac                                      -12.198191   0.456036 -26.748301
SDGTrue                                       -2.913139   0.932859  -3.122806
lnmean_career_age                              3.682351   1.495649   2.462041
lnex_ld_avg_avgimpact                          3.576699   0.781519   4.576597
lnex_ld_avg_insthindex                         4.912999   0.799729   6.143332
ex_ld_bin_gsGlobalNorth                      -14.709542   1.272001 -11.564098
ex_ld_bin_sameCSame                            3.235174   0.993771   3.255451
knowledge_proximity_mean                     238.800944  23.192992  10.296254
lnex_ld_avg_before_year_prod_fac               0.043750   0.597954   0.073166
ex_ld_max_before_year_with_ih_binTrue        -10.644998   2.162144  -4.923353
Agricultural.and.Biological.Sciences         -26.744697   1.101717 -24.275460
Arts.and.Humanities                          -46.738548   2.245751 -20.811988
Biochemistry..Genetics.and.Molecular.Biology -38.575015   0.964289 -40.003602
Business..Management.and.Accounting           26.500700   6.456057   4.104781
Chemical.Engineering                         -13.515856   1.262244 -10.707803
Chemistry                                    -11.438916   1.781919  -6.419438
Computer.Science                             -20.264059   2.493210  -8.127699
Decision.Sciences                            -40.083834  10.971989  -3.653288
Dentistry                                    -19.374381   9.283204  -2.087036
Earth.and.Planetary.Sciences                 -28.895601   3.004064  -9.618838
Economics..Econometrics.and.Finance            4.957190  19.479652   0.254480
Energy                                       -10.972898   1.010860 -10.855017
Engineering                                  -19.876136   1.127332 -17.631131
Environmental.Science                        -27.966963   1.273756 -21.956298
Health.Professions                           -31.307734   5.414817  -5.781863
Immunology.and.Microbiology                  -15.496064   2.100742  -7.376472
Materials.Science                            -12.685698   1.474755  -8.601905
Mathematics                                   30.847768  15.205772   2.028688
Medicine                                     -33.519475   1.718391 -19.506312
Neuroscience                                 -22.430582   1.516956 -14.786572
Nursing                                      -26.753421   1.637746 -16.335517
Pharmacology..Toxicology.and.Pharmaceutics   -12.014868   2.437991  -4.928184
Physics.and.Astronomy                         13.419064   1.249453  10.739948
Psychology                                    -2.494501   8.638105  -0.288779
Social.Sciences                              -18.238066   4.217435  -4.324446
Veterinary                                   -15.842203   9.140980  -1.733097
                                               Pr(>|t|)
fac_scientist_lead_ratio                     8.9055e-02 .
I(fac_scientist_lead_ratio^2)                4.3998e-01
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   7.3924e-01
lnnum_reference                              6.9098e-12 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                      1.7920e-03 **
lnmean_career_age                            1.3817e-02 *
lnex_ld_avg_avgimpact                        4.7332e-06 ***
lnex_ld_avg_insthindex                       8.1195e-10 ***
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                          1.1326e-03 **
knowledge_proximity_mean                      < 2.2e-16 ***
lnex_ld_avg_before_year_prod_fac             9.4167e-01
ex_ld_max_before_year_with_ih_binTrue        8.5246e-07 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          4.0511e-05 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                    1.3756e-10 ***
Computer.Science                             4.4383e-16 ***
Decision.Sciences                            2.5907e-04 ***
Dentistry                                    3.6888e-02 *
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.9913e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                           7.4157e-09 ***
Immunology.and.Microbiology                  1.6414e-13 ***
Materials.Science                             < 2.2e-16 ***
Mathematics                                  4.2493e-02 *
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   8.3166e-07 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   7.7275e-01
Social.Sciences                              1.5310e-05 ***
Veterinary                                   8.3082e-02 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 124.7     Adj. R2: 0.11637
              Within R2: 0.11499

In [62]:
# library(marginaleffects)
# # 设置 draw = FALSE，直接拦截绘图数据
# plot_data <- plot_predictions(model_h3_lratio, condition = "fac_scientist_lead_ratio", draw = FALSE)
# # 选出我们最需要的几列：x轴变量、预测值(estimate)、置信区间下限(conf.low)、上限(conf.high)
# export_data <- plot_data[, c("fac_scientist_lead_ratio", "estimate", "conf.low", "conf.high")]
# # # 导出为 CSV 文件，给 Python 准备
# write.csv(export_data, "R_ex_ld_h3_pred_lratio.csv", row.names = FALSE)
# export_data
# # print("数据已成功导出！")
# # head(export_data)

In [63]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_h3_lratio,
                           keep = c("fac_scientist_lead_ratio", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                 & novel\_uzzi\\
   Model:                                              & (1)\\
   \midrule
   \emph{Variables}\\
   fac\_scientist\_lead\_ratio                         & 11.5$^{*}$\\
                                                       & (6.76)\\
   fac\_scientist\_lead\_ratio square                  & -7.08\\
                                                       & (9.17)\\
   lnnum\_author                                       & 41.4$^{***}$\\
                                                       & (1.08)\\
   internationalinternational                          & -0.394\\
                                                       & (1.18)\\
   lnnum\_reference                                    & -16.3$^{***}$\\
                                                       & (2.38)\\
   num\_fac                                            & -12.2$^{***}$\\
                                                       & (0.456)\\
   SDGTrue                                             & -2.91$^{***}$\\
                                                       & (0.933)\\
   lnmean\_career\_age                                 & 3.68$^{**}$\\
                                                       & (1.50)\\
   lnex\_ld\_avg\_avgimpact                            & 3.58$^{***}$\\
                                                       & (0.782)\\
   lnex\_ld\_avg\_insthindex                           & 4.91$^{***}$\\
                                                       & (0.800)\\
   ex\_ld\_bin\_gsGlobalNorth                          & -14.7$^{***}$\\
                                                       & (1.27)\\
   ex\_ld\_bin\_sameCSame                              & 3.24$^{***}$\\
                                                       & (0.994)\\
   knowledge\_proximity\_mean                          & 238.8$^{***}$\\
                                                       & (23.2)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac              & 0.044\\
                                                       & (0.598)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue        & -10.6$^{***}$\\
                                                       & (2.16)\\
   Agricultural.and.Biological.Sciences                & -26.7$^{***}$\\
                                                       & (1.10)\\
   Arts.and.Humanities                                 & -46.7$^{***}$\\
                                                       & (2.25)\\
   Biochemistry..Genetics.and.Molecular.Biology        & -38.6$^{***}$\\
                                                       & (0.964)\\
   Business..Management.and.Accounting                 & 26.5$^{***}$\\
                                                       & (6.46)\\
   Chemical.Engineering                                & -13.5$^{***}$\\
                                                       & (1.26)\\
   Chemistry                                           & -11.4$^{***}$\\
                                                       & (1.78)\\
   Computer.Science                                    & -20.3$^{***}$\\
                                                       & (2.49)\\
   Decision.Sciences                                   & -40.1$^{***}$\\
                                                       & (11.0)\\
   Dentistry                                           & -19.4$^{**}$\\
                                                       & (9.28)\\
   Earth.and.Planetary.Sciences                        & -28.9$^{***}$\\
                                                       & (3.00)\\
   Economics..Econometrics.and.Finance                 & 4.96\\
                                                       & (19.5)\\
   Energy                                              & -11.0$^{***}$\\
                                                       & (1.01)\\
   Engineering                                         & -19.9$^{***}$\\
                                                       & (1.13)\\
   Immunology.and.Microbiology                         & -15.5$^{***}$\\
                                                       & (2.10)\\
   Materials.Science                                   & -12.7$^{***}$\\
                                                       & (1.47)\\
   Mathematics                                         & 30.8$^{**}$\\
                                                       & (15.2)\\
   Medicine                                            & -33.5$^{***}$\\
                                                       & (1.72)\\
   Neuroscience                                        & -22.4$^{***}$\\
                                                       & (1.52)\\
   Nursing                                             & -26.8$^{***}$\\
                                                       & (1.64)\\
   Pharmacology..Toxicology.and.Pharmaceutics          & -12.0$^{***}$\\
                                                       & (2.44)\\
   Physics.and.Astronomy                               & 13.4$^{***}$\\
                                                       & (1.25)\\
   Psychology                                          & -2.49\\
                                                       & (8.64)\\
   Social.Sciences                                     & -18.2$^{***}$\\
                                                       & (4.22)\\
   Veterinary                                          & -15.8$^{*}$\\
                                                       & (9.14)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                       & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                        & 78,519\\
   R$^2$                                               & 0.11739\\
   Within R$^2$                                        & 0.11499\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# Moderating

In [64]:
fml <- as.formula(
  paste0("novel_uzzi ~ CoType*lnex_ld_avg_before_year_prod_fac  + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_pre_facpub <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], vcov = "hetero")
summary(model_pre_facpub)

NOTE: 98 observations removed because of NA values (LHS: 98).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 294,781
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                       Estimate Std. Error
CoTypeCollaboration                                   -5.513123   1.984836
CoTypeParticipation                                  -37.516598   3.174151
lnex_ld_avg_before_year_prod_fac                       0.132528   0.513220
lnnum_author                                          19.454120   0.732072
internationalinternational                             3.699588   0.673092
lnnum_reference                                      -18.060777   1.213206
num_fac                                              -11.703731   0.281608
SDGTrue                                               -1.394094   0.553021
lnmean_career_age                                      1.936293   1.030843
lnex_ld_avg_avgimpact                                  8.031189   0.487130
lnex_ld_avg_insthindex                                 2.334539   0.509161
ex_ld_bin_gsGlobalNorth                               -9.365642   1.178921
ex_ld_bin_sameCSame                                    5.271470   0.642586
knowledge_proximity_mean                             214.128317  11.241747
ex_ld_max_before_year_with_ih_binTrue                -26.572501   0.960656
Agricultural.and.Biological.Sciences                 -31.379132   0.644618
Arts.and.Humanities                                  -45.749472   6.550874
Biochemistry..Genetics.and.Molecular.Biology         -43.762894   0.759204
Business..Management.and.Accounting                   24.878294   4.888164
Chemical.Engineering                                 -17.549561   0.741542
Chemistry                                            -16.704060   0.711723
Computer.Science                                     -32.691769   2.189383
Decision.Sciences                                      7.117858  54.118567
Dentistry                                            -32.947230   3.365965
Earth.and.Planetary.Sciences                         -28.735645   1.291710
Economics..Econometrics.and.Finance                   -5.337303  14.952820
Energy                                               -17.505074   0.574009
Engineering                                          -23.971684   0.752997
Environmental.Science                                -15.378905   1.019450
Health.Professions                                   -40.276437   3.779248
Immunology.and.Microbiology                          -32.801106   0.758460
Materials.Science                                    -25.698051   0.777063
Mathematics                                            7.297270  10.273727
Medicine                                             -37.515039   0.798169
Neuroscience                                         -27.591667   0.747136
Nursing                                              -29.066679   0.821005
Pharmacology..Toxicology.and.Pharmaceutics           -23.507934   1.153365
Physics.and.Astronomy                                 22.437392   0.829971
Psychology                                           -27.206510   3.484805
Social.Sciences                                      -17.255159   7.682897
Veterinary                                           -31.314792   2.983111
CoTypeCollaboration:lnex_ld_avg_before_year_prod_fac  -1.882798   0.690266
CoTypeParticipation:lnex_ld_avg_before_year_prod_fac  14.370126   1.085401
                                                        t value   Pr(>|t|)
CoTypeCollaboration                                   -2.777621 5.4762e-03 **
CoTypeParticipation                                  -11.819411  < 2.2e-16 ***
lnex_ld_avg_before_year_prod_fac                       0.258229 7.9623e-01
lnnum_author                                          26.574036  < 2.2e-16 ***
internationalinternational                             5.496406 3.8793e-08 ***
lnnum_reference                                      -14.886819  < 2.2e-16 ***
num_fac                                              -41.560351  < 2.2e-16 ***
SDGTrue                                               -2.520869 1.1707e-02 *
lnmean_career_age                                      1.878359 6.0333e-02 .
lnex_ld_avg_avgimpact                                 16.486759  < 2.2e-16 ***
lnex_ld_avg_insthindex                                 4.585070 4.5402e-06 ***
ex_ld_bin_gsGlobalNorth                               -7.944251 1.9605e-15 ***
ex_ld_bin_sameCSame                                    8.203524 2.3437e-16 ***
knowledge_proximity_mean                              19.047601  < 2.2e-16 ***
ex_ld_max_before_year_with_ih_binTrue                -27.660800  < 2.2e-16 ***
Agricultural.and.Biological.Sciences                 -48.678637  < 2.2e-16 ***
Arts.and.Humanities                                   -6.983721 2.8807e-12 ***
Biochemistry..Genetics.and.Molecular.Biology         -57.643162  < 2.2e-16 ***
Business..Management.and.Accounting                    5.089496 3.5924e-07 ***
Chemical.Engineering                                 -23.666308  < 2.2e-16 ***
Chemistry                                            -23.469892  < 2.2e-16 ***
Computer.Science                                     -14.931953  < 2.2e-16 ***
Decision.Sciences                                      0.131523 8.9536e-01
Dentistry                                             -9.788346  < 2.2e-16 ***
Earth.and.Planetary.Sciences                         -22.246207  < 2.2e-16 ***
Economics..Econometrics.and.Finance                   -0.356943 7.2113e-01
Energy                                               -30.496187  < 2.2e-16 ***
Engineering                                          -31.835027  < 2.2e-16 ***
Environmental.Science                                -15.085496  < 2.2e-16 ***
Health.Professions                                   -10.657261  < 2.2e-16 ***
Immunology.and.Microbiology                          -43.246966  < 2.2e-16 ***
Materials.Science                                    -33.070756  < 2.2e-16 ***
Mathematics                                            0.710285 4.7753e-01
Medicine                                             -47.001367  < 2.2e-16 ***
Neuroscience                                         -36.929896  < 2.2e-16 ***
Nursing                                              -35.403787  < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics           -20.382038  < 2.2e-16 ***
Physics.and.Astronomy                                 27.033938  < 2.2e-16 ***
Psychology                                            -7.807184 5.8671e-15 ***
Social.Sciences                                       -2.245918 2.4710e-02 *
Veterinary                                           -10.497362  < 2.2e-16 ***
CoTypeCollaboration:lnex_ld_avg_before_year_prod_fac  -2.727642 6.3793e-03 **
CoTypeParticipation:lnex_ld_avg_before_year_prod_fac  13.239457  < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 145.1     Adj. R2: 0.062176
              Within R2: 0.061249

In [65]:
# # 1. 找到你这个连续变量的实际最小值和最大值（假设是 0 和 10，你需要改成你的实际极值）
# min_val <- min(data$lnex_ld_avg_before_year_prod_fac, na.rm=TRUE)
# max_val <- max(data$lnex_ld_avg_before_year_prod_fac, na.rm=TRUE)
# # 2. 运行估计
# res_pre_facpub <- avg_comparisons(
#     model_pre_facpub,
#     variables = "CoType",
#     comparison = "ratio",
#     newdata = datagrid(
#     model = model_pre_facpub,
#     lnex_ld_avg_before_year_prod_fac = seq(min_val, max_val, length.out = 50) # 这里的 10 可以改成任意你想要的数字
#   ),
#     by = "lnex_ld_avg_before_year_prod_fac"
# )
# res_pre_facpub

In [66]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_facpub.csv")
# write.csv(res_pre_facpub, fname, row.names = FALSE)

In [67]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_facpub,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                                        & novel\_uzzi\\
   Model:                                                                     & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                                        & -5.51$^{***}$\\
                                                                              & (1.98)\\
   CoTypeParticipation                                                        & -37.5$^{***}$\\
                                                                              & (3.17)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac                                     & 0.133\\
                                                                              & (0.513)\\
   lnnum\_author                                                              & 19.5$^{***}$\\
                                                                              & (0.732)\\
   internationalinternational                                                 & 3.70$^{***}$\\
                                                                              & (0.673)\\
   lnnum\_reference                                                           & -18.1$^{***}$\\
                                                                              & (1.21)\\
   num\_fac                                                                   & -11.7$^{***}$\\
                                                                              & (0.282)\\
   SDGTrue                                                                    & -1.39$^{**}$\\
                                                                              & (0.553)\\
   lnmean\_career\_age                                                        & 1.94$^{*}$\\
                                                                              & (1.03)\\
   lnex\_ld\_avg\_avgimpact                                                   & 8.03$^{***}$\\
                                                                              & (0.487)\\
   lnex\_ld\_avg\_insthindex                                                  & 2.33$^{***}$\\
                                                                              & (0.509)\\
   ex\_ld\_bin\_gsGlobalNorth                                                 & -9.37$^{***}$\\
                                                                              & (1.18)\\
   ex\_ld\_bin\_sameCSame                                                     & 5.27$^{***}$\\
                                                                              & (0.643)\\
   knowledge\_proximity\_mean                                                 & 214.1$^{***}$\\
                                                                              & (11.2)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue                               & -26.6$^{***}$\\
                                                                              & (0.961)\\
   Agricultural.and.Biological.Sciences                                       & -31.4$^{***}$\\
                                                                              & (0.645)\\
   Arts.and.Humanities                                                        & -45.7$^{***}$\\
                                                                              & (6.55)\\
   Biochemistry..Genetics.and.Molecular.Biology                               & -43.8$^{***}$\\
                                                                              & (0.759)\\
   Business..Management.and.Accounting                                        & 24.9$^{***}$\\
                                                                              & (4.89)\\
   Chemical.Engineering                                                       & -17.5$^{***}$\\
                                                                              & (0.742)\\
   Chemistry                                                                  & -16.7$^{***}$\\
                                                                              & (0.712)\\
   Computer.Science                                                           & -32.7$^{***}$\\
                                                                              & (2.19)\\
   Decision.Sciences                                                          & 7.12\\
                                                                              & (54.1)\\
   Dentistry                                                                  & -32.9$^{***}$\\
                                                                              & (3.37)\\
   Earth.and.Planetary.Sciences                                               & -28.7$^{***}$\\
                                                                              & (1.29)\\
   Economics..Econometrics.and.Finance                                        & -5.34\\
                                                                              & (15.0)\\
   Energy                                                                     & -17.5$^{***}$\\
                                                                              & (0.574)\\
   Engineering                                                                & -24.0$^{***}$\\
                                                                              & (0.753)\\
   Immunology.and.Microbiology                                                & -32.8$^{***}$\\
                                                                              & (0.758)\\
   Materials.Science                                                          & -25.7$^{***}$\\
                                                                              & (0.777)\\
   Mathematics                                                                & 7.30\\
                                                                              & (10.3)\\
   Medicine                                                                   & -37.5$^{***}$\\
                                                                              & (0.798)\\
   Neuroscience                                                               & -27.6$^{***}$\\
                                                                              & (0.747)\\
   Nursing                                                                    & -29.1$^{***}$\\
                                                                              & (0.821)\\
   Pharmacology..Toxicology.and.Pharmaceutics                                 & -23.5$^{***}$\\
                                                                              & (1.15)\\
   Physics.and.Astronomy                                                      & 22.4$^{***}$\\
                                                                              & (0.830)\\
   Psychology                                                                 & -27.2$^{***}$\\
                                                                              & (3.48)\\
   Social.Sciences                                                            & -17.3$^{**}$\\
                                                                              & (7.68)\\
   Veterinary                                                                 & -31.3$^{***}$\\
                                                                              & (2.98)\\
   CoTypeCollaboration $\times$ lnex\_ld\_avg\_before\_year\_prod\_fac        & -1.88$^{***}$\\
                                                                              & (0.690)\\
   CoTypeParticipation $\times$ lnex\_ld\_avg\_before\_year\_prod\_fac        & 14.4$^{***}$\\
                                                                              & (1.09)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                                              & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                                               & 294,781\\
   R$^2$                                                                      & 0.06247\\
   Within R$^2$                                                               & 0.06125\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [68]:
fml <- as.formula(
  paste0("novel_uzzi ~ CoType*ex_ld_max_before_year_with_ih_bin  + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_pre_withih <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], vcov = "hetero")
summary(model_pre_withih)

NOTE: 98 observations removed because of NA values (LHS: 98).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 294,781
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                           Estimate Std. Error
CoTypeCollaboration                                       -23.22205   2.301395
CoTypeParticipation                                       -25.83847   3.228196
ex_ld_max_before_year_with_ih_binTrue                     -29.53324   1.012175
lnnum_author                                               21.01265   0.755560
internationalinternational                                  3.36101   0.672651
lnnum_reference                                           -18.09916   1.214429
num_fac                                                   -11.78134   0.289397
SDGTrue                                                    -1.48374   0.552352
lnmean_career_age                                           1.83468   1.028452
lnex_ld_avg_avgimpact                                       7.81367   0.487951
lnex_ld_avg_insthindex                                      2.46568   0.508683
ex_ld_bin_gsGlobalNorth                                    -9.25818   1.175605
ex_ld_bin_sameCSame                                         4.87797   0.647165
knowledge_proximity_mean                                  217.35379  11.352691
lnex_ld_avg_before_year_prod_fac                            1.06219   0.422596
Agricultural.and.Biological.Sciences                      -31.67647   0.649054
Arts.and.Humanities                                       -45.91525   6.546624
Biochemistry..Genetics.and.Molecular.Biology              -44.06859   0.761614
Business..Management.and.Accounting                        24.51917   4.888313
Chemical.Engineering                                      -17.67930   0.741347
Chemistry                                                 -16.63768   0.712174
Computer.Science                                          -32.76240   2.191759
Decision.Sciences                                           6.54687  54.137595
Dentistry                                                 -33.07147   3.301878
Earth.and.Planetary.Sciences                              -28.82875   1.290243
Economics..Econometrics.and.Finance                        -4.46140  14.988521
Energy                                                    -17.61531   0.572202
Engineering                                               -24.06308   0.752757
Environmental.Science                                     -15.56455   1.020071
Health.Professions                                        -40.95876   3.793780
Immunology.and.Microbiology                               -33.13696   0.765760
Materials.Science                                         -25.68663   0.773545
Mathematics                                                 8.14304  10.266729
Medicine                                                  -37.84659   0.799810
Neuroscience                                              -27.74213   0.751388
Nursing                                                   -28.97938   0.825101
Pharmacology..Toxicology.and.Pharmaceutics                -23.43935   1.158125
Physics.and.Astronomy                                      22.41374   0.828138
Psychology                                                -28.11167   3.484625
Social.Sciences                                           -18.31338   7.687793
Veterinary                                                -30.69625   3.111743
CoTypeCollaboration:ex_ld_max_before_year_with_ih_binTrue  15.09342   2.342599
CoTypeParticipation:ex_ld_max_before_year_with_ih_binTrue  25.64376   3.387012
                                                             t value   Pr(>|t|)
CoTypeCollaboration                                       -10.090419  < 2.2e-16
CoTypeParticipation                                        -8.003997 1.2088e-15
ex_ld_max_before_year_with_ih_binTrue                     -29.177987  < 2.2e-16
lnnum_author                                               27.810686  < 2.2e-16
internationalinternational                                  4.996670 5.8362e-07
lnnum_reference                                           -14.903425  < 2.2e-16
num_fac                                                   -40.709937  < 2.2e-16
SDGTrue                                                    -2.686231 7.2267e-03
lnmean_career_age                                           1.783925 7.4437e-02
lnex_ld_avg_avgimpact                                      16.013215  < 2.2e-16
lnex_ld_avg_insthindex                                      4.847181 1.2529e-06
ex_ld_bin_gsGlobalNorth                                    -7.875245 3.4122e-15
ex_ld_bin_sameCSame                                         7.537449 4.8061e-14
knowledge_proximity_mean                                   19.145574  < 2.2e-16
lnex_ld_avg_before_year_prod_fac                            2.513488 1.1955e-02
Agricultural.and.Biological.Sciences                      -48.804030  < 2.2e-16
Arts.and.Humanities                                        -7.013576 2.3280e-12
Biochemistry..Genetics.and.Molecular.Biology              -57.862123  < 2.2e-16
Business..Management.and.Accounting                         5.015876 5.2823e-07
Chemical.Engineering                                      -23.847554  < 2.2e-16
Chemistry                                                 -23.361819  < 2.2e-16
Computer.Science                                          -14.947991  < 2.2e-16
Decision.Sciences                                           0.120930 9.0375e-01
Dentistry                                                 -10.015959  < 2.2e-16
Earth.and.Planetary.Sciences                              -22.343667  < 2.2e-16
Economics..Econometrics.and.Finance                        -0.297654 7.6597e-01
Energy                                                    -30.785108  < 2.2e-16
Engineering                                               -31.966616  < 2.2e-16
Environmental.Science                                     -15.258296  < 2.2e-16
Health.Professions                                        -10.796292  < 2.2e-16
Immunology.and.Microbiology                               -43.273273  < 2.2e-16
Materials.Science                                         -33.206369  < 2.2e-16
Mathematics                                                 0.793149 4.2769e-01
Medicine                                                  -47.319465  < 2.2e-16
Neuroscience                                              -36.921171  < 2.2e-16
Nursing                                                   -35.122219  < 2.2e-16
Pharmacology..Toxicology.and.Pharmaceutics                -20.239062  < 2.2e-16
Physics.and.Astronomy                                      27.065240  < 2.2e-16
Psychology                                                 -8.067345 7.2110e-16
Social.Sciences                                            -2.382138 1.7213e-02
Veterinary                                                 -9.864649  < 2.2e-16
CoTypeCollaboration:ex_ld_max_before_year_with_ih_binTrue   6.443024 1.1730e-10
CoTypeParticipation:ex_ld_max_before_year_with_ih_binTrue   7.571203 3.7085e-14

CoTypeCollaboration                                       ***
CoTypeParticipation                                       ***
ex_ld_max_before_year_with_ih_binTrue                     ***
lnnum_author                                              ***
internationalinternational                                ***
lnnum_reference                                           ***
num_fac                                                   ***
SDGTrue                                                   **
lnmean_career_age                                         .
lnex_ld_avg_avgimpact                                     ***
lnex_ld_avg_insthindex                                    ***
ex_ld_bin_gsGlobalNorth                                   ***
ex_ld_bin_sameCSame                                       ***
knowledge_proximity_mean                                  ***
lnex_ld_avg_before_year_prod_fac                          *
Agricultural.and.Biological.Sciences                      ***
Arts.and.Humanities                                       ***
Biochemistry..Genetics.and.Molecular.Biology              ***
Business..Management.and.Accounting                       ***
Chemical.Engineering                                      ***
Chemistry                                                 ***
Computer.Science                                          ***
Decision.Sciences
Dentistry                                                 ***
Earth.and.Planetary.Sciences                              ***
Economics..Econometrics.and.Finance
Energy                                                    ***
Engineering                                               ***
Environmental.Science                                     ***
Health.Professions                                        ***
Immunology.and.Microbiology                               ***
Materials.Science                                         ***
Mathematics
Medicine                                                  ***
Neuroscience                                              ***
Nursing                                                   ***
Pharmacology..Toxicology.and.Pharmaceutics                ***
Physics.and.Astronomy                                     ***
Psychology                                                ***
Social.Sciences                                           *
Veterinary                                                ***
CoTypeCollaboration:ex_ld_max_before_year_with_ih_binTrue ***
CoTypeParticipation:ex_ld_max_before_year_with_ih_binTrue ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 145.1     Adj. R2: 0.06151
              Within R2: 0.060583

In [69]:
# # 每组 reg_class 的平均预测概率
# res_pre_withih <- avg_comparisons(model_pre_withih, variables = "CoType", comparison = 'ratio', by = 'ex_ld_max_before_year_with_ih_bin')
# res_pre_withih

In [70]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_withih.csv")
# write.csv(res_pre_withih, fname, row.names = FALSE)

In [71]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_withih,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                                               & novel\_uzzi\\
   Model:                                                                            & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                                               & -23.2$^{***}$\\
                                                                                     & (2.30)\\
   CoTypeParticipation                                                               & -25.8$^{***}$\\
                                                                                     & (3.23)\\
   ex\_ld\_max\_before\_year\_with\_ih\_binTrue                                      & -29.5$^{***}$\\
                                                                                     & (1.01)\\
   lnnum\_author                                                                     & 21.0$^{***}$\\
                                                                                     & (0.756)\\
   internationalinternational                                                        & 3.36$^{***}$\\
                                                                                     & (0.673)\\
   lnnum\_reference                                                                  & -18.1$^{***}$\\
                                                                                     & (1.21)\\
   num\_fac                                                                          & -11.8$^{***}$\\
                                                                                     & (0.289)\\
   SDGTrue                                                                           & -1.48$^{***}$\\
                                                                                     & (0.552)\\
   lnmean\_career\_age                                                               & 1.83$^{*}$\\
                                                                                     & (1.03)\\
   lnex\_ld\_avg\_avgimpact                                                          & 7.81$^{***}$\\
                                                                                     & (0.488)\\
   lnex\_ld\_avg\_insthindex                                                         & 2.47$^{***}$\\
                                                                                     & (0.509)\\
   ex\_ld\_bin\_gsGlobalNorth                                                        & -9.26$^{***}$\\
                                                                                     & (1.18)\\
   ex\_ld\_bin\_sameCSame                                                            & 4.88$^{***}$\\
                                                                                     & (0.647)\\
   knowledge\_proximity\_mean                                                        & 217.4$^{***}$\\
                                                                                     & (11.4)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac                                            & 1.06$^{**}$\\
                                                                                     & (0.423)\\
   Agricultural.and.Biological.Sciences                                              & -31.7$^{***}$\\
                                                                                     & (0.649)\\
   Arts.and.Humanities                                                               & -45.9$^{***}$\\
                                                                                     & (6.55)\\
   Biochemistry..Genetics.and.Molecular.Biology                                      & -44.1$^{***}$\\
                                                                                     & (0.762)\\
   Business..Management.and.Accounting                                               & 24.5$^{***}$\\
                                                                                     & (4.89)\\
   Chemical.Engineering                                                              & -17.7$^{***}$\\
                                                                                     & (0.741)\\
   Chemistry                                                                         & -16.6$^{***}$\\
                                                                                     & (0.712)\\
   Computer.Science                                                                  & -32.8$^{***}$\\
                                                                                     & (2.19)\\
   Decision.Sciences                                                                 & 6.55\\
                                                                                     & (54.1)\\
   Dentistry                                                                         & -33.1$^{***}$\\
                                                                                     & (3.30)\\
   Earth.and.Planetary.Sciences                                                      & -28.8$^{***}$\\
                                                                                     & (1.29)\\
   Economics..Econometrics.and.Finance                                               & -4.46\\
                                                                                     & (15.0)\\
   Energy                                                                            & -17.6$^{***}$\\
                                                                                     & (0.572)\\
   Engineering                                                                       & -24.1$^{***}$\\
                                                                                     & (0.753)\\
   Immunology.and.Microbiology                                                       & -33.1$^{***}$\\
                                                                                     & (0.766)\\
   Materials.Science                                                                 & -25.7$^{***}$\\
                                                                                     & (0.774)\\
   Mathematics                                                                       & 8.14\\
                                                                                     & (10.3)\\
   Medicine                                                                          & -37.8$^{***}$\\
                                                                                     & (0.800)\\
   Neuroscience                                                                      & -27.7$^{***}$\\
                                                                                     & (0.751)\\
   Nursing                                                                           & -29.0$^{***}$\\
                                                                                     & (0.825)\\
   Pharmacology..Toxicology.and.Pharmaceutics                                        & -23.4$^{***}$\\
                                                                                     & (1.16)\\
   Physics.and.Astronomy                                                             & 22.4$^{***}$\\
                                                                                     & (0.828)\\
   Psychology                                                                        & -28.1$^{***}$\\
                                                                                     & (3.48)\\
   Social.Sciences                                                                   & -18.3$^{**}$\\
                                                                                     & (7.69)\\
   Veterinary                                                                        & -30.7$^{***}$\\
                                                                                     & (3.11)\\
   CoTypeCollaboration $\times$ ex\_ld\_max\_before\_year\_with\_ih\_binTrue         & 15.1$^{***}$\\
                                                                                     & (2.34)\\
   CoTypeParticipation $\times$ ex\_ld\_max\_before\_year\_with\_ih\_binTrue         & 25.6$^{***}$\\
                                                                                     & (3.39)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                                                     & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                                                      & 294,781\\
   R$^2$                                                                             & 0.06181\\
   Within R$^2$                                                                      & 0.06058\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [72]:
fml <- as.formula(
  paste0("novel_uzzi ~ CoType*ex_ld_max_before_year_participation_bin  + ", paper_level, "+", ex_controls, "+", moderating2, "+",disciplines, " | PublishedYear")
)
model_pre_partic <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], vcov = "hetero")
summary(model_pre_partic)

NOTE: 98 observations removed because of NA values (LHS: 98).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 294,781
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                                  Estimate
CoTypeCollaboration                                             -17.143482
CoTypeParticipation                                             -22.907473
ex_ld_max_before_year_participation_binTrue                     -21.923427
lnnum_author                                                     21.155471
internationalinternational                                        3.350200
lnnum_reference                                                 -18.332787
num_fac                                                         -11.466717
SDGTrue                                                          -1.684036
lnmean_career_age                                                 1.053035
lnex_ld_avg_avgimpact                                             7.689534
lnex_ld_avg_insthindex                                            2.148499
ex_ld_bin_gsGlobalNorth                                          -9.276522
ex_ld_bin_sameCSame                                               5.202487
knowledge_proximity_mean                                        222.170080
lnex_ld_avg_before_year_prod_fac                                 -0.069308
Agricultural.and.Biological.Sciences                            -32.874400
Arts.and.Humanities                                             -46.185426
Biochemistry..Genetics.and.Molecular.Biology                    -44.040081
Business..Management.and.Accounting                              25.951682
Chemical.Engineering                                            -17.685936
Chemistry                                                       -17.551453
Computer.Science                                                -32.810867
Decision.Sciences                                                 5.185438
Dentistry                                                       -35.010298
Earth.and.Planetary.Sciences                                    -29.056367
Economics..Econometrics.and.Finance                              -4.582779
Energy                                                          -18.036012
Engineering                                                     -25.030739
Environmental.Science                                           -15.304923
Health.Professions                                              -41.202933
Immunology.and.Microbiology                                     -33.192215
Materials.Science                                               -26.140257
Mathematics                                                       6.523387
Medicine                                                        -37.705761
Neuroscience                                                    -27.669538
Nursing                                                         -30.271622
Pharmacology..Toxicology.and.Pharmaceutics                      -23.552707
Physics.and.Astronomy                                            22.320513
Psychology                                                      -25.683063
Social.Sciences                                                 -19.387924
Veterinary                                                      -32.425201
CoTypeCollaboration:ex_ld_max_before_year_participation_binTrue   8.697365
CoTypeParticipation:ex_ld_max_before_year_participation_binTrue  26.167530
                                                                Std. Error
CoTypeCollaboration                                               1.282377
CoTypeParticipation                                               1.661553
ex_ld_max_before_year_participation_binTrue                       0.824129
lnnum_author                                                      0.760262
internationalinternational                                        0.675272
lnnum_reference                                                   1.215579
num_fac                                                           0.288762
SDGTrue                                                           0.552556
lnmean_career_age                                                 1.028557
lnex_ld_avg_avgimpact                                             0.488339
lnex_ld_avg_insthindex                                            0.511635
ex_ld_bin_gsGlobalNorth                                           1.177893
ex_ld_bin_sameCSame                                               0.643585
knowledge_proximity_mean                                         11.384840
lnex_ld_avg_before_year_prod_fac                                  0.438440
Agricultural.and.Biological.Sciences                              0.656916
Arts.and.Humanities                                               6.541190
Biochemistry..Genetics.and.Molecular.Biology                      0.759338
Business..Management.and.Accounting                               4.901569
Chemical.Engineering                                              0.741861
Chemistry                                                         0.719676
Computer.Science                                                  2.188059
Decision.Sciences                                                53.999670
Dentistry                                                         3.289003
Earth.and.Planetary.Sciences                                      1.295936
Economics..Econometrics.and.Finance                              14.902179
Energy                                                            0.577689
Engineering                                                       0.761441
Environmental.Science                                             1.023260
Health.Professions                                                3.798642
Immunology.and.Microbiology                                       0.764303
Materials.Science                                                 0.778027
Mathematics                                                      10.331460
Medicine                                                          0.797248
Neuroscience                                                      0.740008
Nursing                                                           0.822291
Pharmacology..Toxicology.and.Pharmaceutics                        1.154104
Physics.and.Astronomy                                             0.830731
Psychology                                                        3.459967
Social.Sciences                                                   7.610848
Veterinary                                                        3.049282
CoTypeCollaboration:ex_ld_max_before_year_participation_binTrue   1.389240
CoTypeParticipation:ex_ld_max_before_year_participation_binTrue   1.987272
                                                                   t value
CoTypeCollaboration                                             -13.368522
CoTypeParticipation                                             -13.786787
ex_ld_max_before_year_participation_binTrue                     -26.601951
lnnum_author                                                     27.826570
internationalinternational                                        4.961261
lnnum_reference                                                 -15.081521
num_fac                                                         -39.709922
SDGTrue                                                          -3.047719
lnmean_career_age                                                 1.023798
lnex_ld_avg_avgimpact                                            15.746307
lnex_ld_avg_insthindex                                            4.199282
ex_ld_bin_gsGlobalNorth                                          -7.875525
ex_ld_bin_sameCSame                                               8.083600
knowledge_proximity_mean                                         19.514554
lnex_ld_avg_before_year_prod_fac                                 -0.158078
Agricultural.and.Biological.Sciences                            -50.043531
Arts.and.Humanities                                              -7.060707
Biochemistry..Genetics.and.Molecular.Biology                    -57.997979
Business..Management.and.Accounting                               5.294567
Chemical.Engineering                                            -23.839949
Chemistry                                                       -24.388004
Computer.Science                                                -14.995423
Decision.Sciences                                                 0.096027
Dentistry                                                       -10.644652
Earth.and.Planetary.Sciences                                    -22.421145
Economics..Econometrics.and.Finance                              -0.307524
Energy                                                          -31.220970
Engineering                                                     -32.872842
Environmental.Science                                           -14.957020
Health.Professions                                              -10.846755
Immunology.and.Microbiology                                     -43.428088
Materials.Science                                               -33.598140
Mathematics                                                       0.631410
Medicine                                                        -47.294876
Neuroscience                                                    -37.390867
Nursing                                                         -36.813776
Pharmacology..Toxicology.and.Pharmaceutics                      -20.407788
Physics.and.Astronomy                                            26.868514
Psychology                                                       -7.422921
Social.Sciences                                                  -2.547406
Veterinary                                                      -10.633716
CoTypeCollaboration:ex_ld_max_before_year_participation_binTrue   6.260520
CoTypeParticipation:ex_ld_max_before_year_participation_binTrue  13.167562
                                                                  Pr(>|t|)
CoTypeCollaboration                                              < 2.2e-16 ***
CoTypeParticipation                                              < 2.2e-16 ***
ex_ld_max_before_year_participation_binTrue                      < 2.2e-16 ***
lnnum_author                                                     < 2.2e-16 ***
internationalinternational                                      7.0076e-07 ***
lnnum_reference                                                  < 2.2e-16 ***
num_fac                                                          < 2.2e-16 ***
SDGTrue                                                         2.3061e-03 **
lnmean_career_age                                               3.0593e-01
lnex_ld_avg_avgimpact                                            < 2.2e-16 ***
lnex_ld_avg_insthindex                                          2.6784e-05 ***
ex_ld_bin_gsGlobalNorth                                         3.4046e-15 ***
ex_ld_bin_sameCSame                                             6.3117e-16 ***
knowledge_proximity_mean                                         < 2.2e-16 ***
lnex_ld_avg_before_year_prod_fac                                8.7440e-01
Agricultural.and.Biological.Sciences                             < 2.2e-16 ***
Arts.and.Humanities                                             1.6602e-12 ***
Biochemistry..Genetics.and.Molecular.Biology                     < 2.2e-16 ***
Business..Management.and.Accounting                             1.1938e-07 ***
Chemical.Engineering                                             < 2.2e-16 ***
Chemistry                                                        < 2.2e-16 ***
Computer.Science                                                 < 2.2e-16 ***
Decision.Sciences                                               9.2350e-01
Dentistry                                                        < 2.2e-16 ***
Earth.and.Planetary.Sciences                                     < 2.2e-16 ***
Economics..Econometrics.and.Finance                             7.5844e-01
Energy                                                           < 2.2e-16 ***
Engineering                                                      < 2.2e-16 ***
Environmental.Science                                            < 2.2e-16 ***
Health.Professions                                               < 2.2e-16 ***
Immunology.and.Microbiology                                      < 2.2e-16 ***
Materials.Science                                                < 2.2e-16 ***
Mathematics                                                     5.2777e-01
Medicine                                                         < 2.2e-16 ***
Neuroscience                                                     < 2.2e-16 ***
Nursing                                                          < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics                       < 2.2e-16 ***
Physics.and.Astronomy                                            < 2.2e-16 ***
Psychology                                                      1.1487e-13 ***
Social.Sciences                                                 1.0853e-02 *
Veterinary                                                       < 2.2e-16 ***
CoTypeCollaboration:ex_ld_max_before_year_participation_binTrue 3.8422e-10 ***
CoTypeParticipation:ex_ld_max_before_year_participation_binTrue  < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 145.2     Adj. R2: 0.059904
              Within R2: 0.058975

In [73]:
# # 每组 reg_class 的平均预测概率
# res_pre_partic <- avg_comparisons(model_pre_partic, variables = "CoType", comparison = 'ratio', by = 'ex_ld_max_before_year_participation_bin')
# res_pre_partic

In [74]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_partic.csv")
# write.csv(res_pre_partic, fname, row.names = FALSE)

In [75]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_partic,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                                                   & novel\_uzzi\\
   Model:                                                                                & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                                                   & -17.1$^{***}$\\
                                                                                         & (1.28)\\
   CoTypeParticipation                                                                   & -22.9$^{***}$\\
                                                                                         & (1.66)\\
   lnnum\_author                                                                         & 21.2$^{***}$\\
                                                                                         & (0.760)\\
   internationalinternational                                                            & 3.35$^{***}$\\
                                                                                         & (0.675)\\
   lnnum\_reference                                                                      & -18.3$^{***}$\\
                                                                                         & (1.22)\\
   num\_fac                                                                              & -11.5$^{***}$\\
                                                                                         & (0.289)\\
   SDGTrue                                                                               & -1.68$^{***}$\\
                                                                                         & (0.553)\\
   lnmean\_career\_age                                                                   & 1.05\\
                                                                                         & (1.03)\\
   lnex\_ld\_avg\_avgimpact                                                              & 7.69$^{***}$\\
                                                                                         & (0.488)\\
   lnex\_ld\_avg\_insthindex                                                             & 2.15$^{***}$\\
                                                                                         & (0.512)\\
   ex\_ld\_bin\_gsGlobalNorth                                                            & -9.28$^{***}$\\
                                                                                         & (1.18)\\
   ex\_ld\_bin\_sameCSame                                                                & 5.20$^{***}$\\
                                                                                         & (0.644)\\
   knowledge\_proximity\_mean                                                            & 222.2$^{***}$\\
                                                                                         & (11.4)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac                                                & -0.069\\
                                                                                         & (0.438)\\
   Agricultural.and.Biological.Sciences                                                  & -32.9$^{***}$\\
                                                                                         & (0.657)\\
   Arts.and.Humanities                                                                   & -46.2$^{***}$\\
                                                                                         & (6.54)\\
   Biochemistry..Genetics.and.Molecular.Biology                                          & -44.0$^{***}$\\
                                                                                         & (0.759)\\
   Business..Management.and.Accounting                                                   & 26.0$^{***}$\\
                                                                                         & (4.90)\\
   Chemical.Engineering                                                                  & -17.7$^{***}$\\
                                                                                         & (0.742)\\
   Chemistry                                                                             & -17.6$^{***}$\\
                                                                                         & (0.720)\\
   Computer.Science                                                                      & -32.8$^{***}$\\
                                                                                         & (2.19)\\
   Decision.Sciences                                                                     & 5.19\\
                                                                                         & (54.0)\\
   Dentistry                                                                             & -35.0$^{***}$\\
                                                                                         & (3.29)\\
   Earth.and.Planetary.Sciences                                                          & -29.1$^{***}$\\
                                                                                         & (1.30)\\
   Economics..Econometrics.and.Finance                                                   & -4.58\\
                                                                                         & (14.9)\\
   Energy                                                                                & -18.0$^{***}$\\
                                                                                         & (0.578)\\
   Engineering                                                                           & -25.0$^{***}$\\
                                                                                         & (0.761)\\
   Immunology.and.Microbiology                                                           & -33.2$^{***}$\\
                                                                                         & (0.764)\\
   Materials.Science                                                                     & -26.1$^{***}$\\
                                                                                         & (0.778)\\
   Mathematics                                                                           & 6.52\\
                                                                                         & (10.3)\\
   Medicine                                                                              & -37.7$^{***}$\\
                                                                                         & (0.797)\\
   Neuroscience                                                                          & -27.7$^{***}$\\
                                                                                         & (0.740)\\
   Nursing                                                                               & -30.3$^{***}$\\
                                                                                         & (0.822)\\
   Pharmacology..Toxicology.and.Pharmaceutics                                            & -23.6$^{***}$\\
                                                                                         & (1.15)\\
   Physics.and.Astronomy                                                                 & 22.3$^{***}$\\
                                                                                         & (0.831)\\
   Psychology                                                                            & -25.7$^{***}$\\
                                                                                         & (3.46)\\
   Social.Sciences                                                                       & -19.4$^{**}$\\
                                                                                         & (7.61)\\
   Veterinary                                                                            & -32.4$^{***}$\\
                                                                                         & (3.05)\\
   CoTypeCollaboration $\times$ ex\_ld\_max\_before\_year\_participation\_binTrue        & 8.70$^{***}$\\
                                                                                         & (1.39)\\
   CoTypeParticipation $\times$ ex\_ld\_max\_before\_year\_participation\_binTrue        & 26.2$^{***}$\\
                                                                                         & (1.99)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                                                         & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                                                          & 294,781\\
   R$^2$                                                                                 & 0.06020\\
   Within R$^2$                                                                          & 0.05897\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [76]:
fml <- as.formula(
  paste0("novel_uzzi ~ CoType*ex_ld_max_before_year_co_lead_bin  + ", paper_level, "+", ex_controls, "+", moderating3, "+",disciplines, " | PublishedYear")
)
model_pre_co_lead <- feols(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], vcov = "hetero")
summary(model_pre_co_lead)

NOTE: 98 observations removed because of NA values (LHS: 98).

OLS estimation, Dep. Var.: novel_uzzi
Observations: 294,781
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                           Estimate Std. Error
CoTypeCollaboration                                       -20.44579   2.246875
CoTypeParticipation                                         7.50889   2.827249
ex_ld_max_before_year_co_lead_binTrue                     -29.61525   0.918215
lnnum_author                                               20.27970   0.740962
internationalinternational                                  3.53241   0.671168
lnnum_reference                                           -17.99320   1.213442
num_fac                                                   -11.41491   0.285881
SDGTrue                                                    -1.46849   0.552233
lnmean_career_age                                           2.03590   1.028359
lnex_ld_avg_avgimpact                                       8.13985   0.487019
lnex_ld_avg_insthindex                                      2.44543   0.508527
ex_ld_bin_gsGlobalNorth                                    -9.22626   1.174918
ex_ld_bin_sameCSame                                         4.99379   0.646388
knowledge_proximity_mean                                  213.06107  11.304684
lnex_ld_avg_before_year_prod_fac                            1.91234   0.430092
Agricultural.and.Biological.Sciences                      -31.51420   0.652063
Arts.and.Humanities                                       -45.68361   6.549837
Biochemistry..Genetics.and.Molecular.Biology              -44.01608   0.757927
Business..Management.and.Accounting                        25.10873   4.896579
Chemical.Engineering                                      -17.88152   0.741760
Chemistry                                                 -16.79296   0.714787
Computer.Science                                          -32.42857   2.193253
Decision.Sciences                                           7.36969  54.138815
Dentistry                                                 -33.22328   3.226583
Earth.and.Planetary.Sciences                              -28.26564   1.285792
Economics..Econometrics.and.Finance                        -4.42543  14.932291
Energy                                                    -17.82674   0.575509
Engineering                                               -23.86962   0.754397
Environmental.Science                                     -15.23653   1.020100
Health.Professions                                        -40.20116   3.804913
Immunology.and.Microbiology                               -32.93288   0.760973
Materials.Science                                         -25.42681   0.775997
Mathematics                                                 7.93831  10.257323
Medicine                                                  -37.94655   0.799595
Neuroscience                                              -27.66781   0.751150
Nursing                                                   -28.83603   0.825106
Pharmacology..Toxicology.and.Pharmaceutics                -23.20892   1.159724
Physics.and.Astronomy                                      22.72265   0.829437
Psychology                                                -28.11434   3.416650
Social.Sciences                                           -18.76703   7.700248
Veterinary                                                -29.76819   3.077346
CoTypeCollaboration:ex_ld_max_before_year_co_lead_binTrue  13.05199   2.283502
CoTypeParticipation:ex_ld_max_before_year_co_lead_binTrue -10.46116   3.002370
                                                             t value   Pr(>|t|)
CoTypeCollaboration                                        -9.099658  < 2.2e-16
CoTypeParticipation                                         2.655901 7.9101e-03
ex_ld_max_before_year_co_lead_binTrue                     -32.253083  < 2.2e-16
lnnum_author                                               27.369427  < 2.2e-16
internationalinternational                                  5.263074 1.4177e-07
lnnum_reference                                           -14.828225  < 2.2e-16
num_fac                                                   -39.928930  < 2.2e-16
SDGTrue                                                    -2.659180 7.8335e-03
lnmean_career_age                                           1.979752 4.7732e-02
lnex_ld_avg_avgimpact                                      16.713626  < 2.2e-16
lnex_ld_avg_insthindex                                      4.808858 1.5187e-06
ex_ld_bin_gsGlobalNorth                                    -7.852680 4.0860e-15
ex_ld_bin_sameCSame                                         7.725695 1.1159e-14
knowledge_proximity_mean                                   18.847150  < 2.2e-16
lnex_ld_avg_before_year_prod_fac                            4.446353 8.7372e-06
Agricultural.and.Biological.Sciences                      -48.329983  < 2.2e-16
Arts.and.Humanities                                        -6.974770 3.0701e-12
Biochemistry..Genetics.and.Molecular.Biology              -58.074276  < 2.2e-16
Business..Management.and.Accounting                         5.127810 2.9332e-07
Chemical.Engineering                                      -24.106890  < 2.2e-16
Chemistry                                                 -23.493649  < 2.2e-16
Computer.Science                                          -14.785601  < 2.2e-16
Decision.Sciences                                           0.136126 8.9172e-01
Dentistry                                                 -10.296736  < 2.2e-16
Earth.and.Planetary.Sciences                              -21.983049  < 2.2e-16
Economics..Econometrics.and.Finance                        -0.296366 7.6695e-01
Energy                                                    -30.975614  < 2.2e-16
Engineering                                               -31.640671  < 2.2e-16
Environmental.Science                                     -14.936305  < 2.2e-16
Health.Professions                                        -10.565591  < 2.2e-16
Immunology.and.Microbiology                               -43.277354  < 2.2e-16
Materials.Science                                         -32.766642  < 2.2e-16
Mathematics                                                 0.773916 4.3898e-01
Medicine                                                  -47.457215  < 2.2e-16
Neuroscience                                              -36.833931  < 2.2e-16
Nursing                                                   -34.948266  < 2.2e-16
Pharmacology..Toxicology.and.Pharmaceutics                -20.012453  < 2.2e-16
Physics.and.Astronomy                                      27.395277  < 2.2e-16
Psychology                                                 -8.228629  < 2.2e-16
Social.Sciences                                            -2.437198 1.4802e-02
Veterinary                                                 -9.673332  < 2.2e-16
CoTypeCollaboration:ex_ld_max_before_year_co_lead_binTrue   5.715779 1.0931e-08
CoTypeParticipation:ex_ld_max_before_year_co_lead_binTrue  -3.484300 4.9350e-04

CoTypeCollaboration                                       ***
CoTypeParticipation                                       **
ex_ld_max_before_year_co_lead_binTrue                     ***
lnnum_author                                              ***
internationalinternational                                ***
lnnum_reference                                           ***
num_fac                                                   ***
SDGTrue                                                   **
lnmean_career_age                                         *
lnex_ld_avg_avgimpact                                     ***
lnex_ld_avg_insthindex                                    ***
ex_ld_bin_gsGlobalNorth                                   ***
ex_ld_bin_sameCSame                                       ***
knowledge_proximity_mean                                  ***
lnex_ld_avg_before_year_prod_fac                          ***
Agricultural.and.Biological.Sciences                      ***
Arts.and.Humanities                                       ***
Biochemistry..Genetics.and.Molecular.Biology              ***
Business..Management.and.Accounting                       ***
Chemical.Engineering                                      ***
Chemistry                                                 ***
Computer.Science                                          ***
Decision.Sciences
Dentistry                                                 ***
Earth.and.Planetary.Sciences                              ***
Economics..Econometrics.and.Finance
Energy                                                    ***
Engineering                                               ***
Environmental.Science                                     ***
Health.Professions                                        ***
Immunology.and.Microbiology                               ***
Materials.Science                                         ***
Mathematics
Medicine                                                  ***
Neuroscience                                              ***
Nursing                                                   ***
Pharmacology..Toxicology.and.Pharmaceutics                ***
Physics.and.Astronomy                                     ***
Psychology                                                ***
Social.Sciences                                           *
Veterinary                                                ***
CoTypeCollaboration:ex_ld_max_before_year_co_lead_binTrue ***
CoTypeParticipation:ex_ld_max_before_year_co_lead_binTrue ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 145.0     Adj. R2: 0.062365
              Within R2: 0.061438

In [77]:
# # 每组 reg_class 的平均预测概率
# res_pre_co_lead <- avg_comparisons(model_pre_co_lead, variables = "CoType", comparison = 'ratio', by = 'ex_ld_max_before_year_co_lead_bin')
# res_pre_co_lead

In [78]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_co_lead.csv")
# write.csv(res_pre_co_lead, fname, row.names = FALSE)

In [79]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_co_lead,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                                               & novel\_uzzi\\
   Model:                                                                            & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                                               & -20.4$^{***}$\\
                                                                                     & (2.25)\\
   CoTypeParticipation                                                               & 7.51$^{***}$\\
                                                                                     & (2.83)\\
   lnnum\_author                                                                     & 20.3$^{***}$\\
                                                                                     & (0.741)\\
   internationalinternational                                                        & 3.53$^{***}$\\
                                                                                     & (0.671)\\
   lnnum\_reference                                                                  & -18.0$^{***}$\\
                                                                                     & (1.21)\\
   num\_fac                                                                          & -11.4$^{***}$\\
                                                                                     & (0.286)\\
   SDGTrue                                                                           & -1.47$^{***}$\\
                                                                                     & (0.552)\\
   lnmean\_career\_age                                                               & 2.04$^{**}$\\
                                                                                     & (1.03)\\
   lnex\_ld\_avg\_avgimpact                                                          & 8.14$^{***}$\\
                                                                                     & (0.487)\\
   lnex\_ld\_avg\_insthindex                                                         & 2.45$^{***}$\\
                                                                                     & (0.509)\\
   ex\_ld\_bin\_gsGlobalNorth                                                        & -9.23$^{***}$\\
                                                                                     & (1.17)\\
   ex\_ld\_bin\_sameCSame                                                            & 4.99$^{***}$\\
                                                                                     & (0.646)\\
   knowledge\_proximity\_mean                                                        & 213.1$^{***}$\\
                                                                                     & (11.3)\\
   lnex\_ld\_avg\_before\_year\_prod\_fac                                            & 1.91$^{***}$\\
                                                                                     & (0.430)\\
   Agricultural.and.Biological.Sciences                                              & -31.5$^{***}$\\
                                                                                     & (0.652)\\
   Arts.and.Humanities                                                               & -45.7$^{***}$\\
                                                                                     & (6.55)\\
   Biochemistry..Genetics.and.Molecular.Biology                                      & -44.0$^{***}$\\
                                                                                     & (0.758)\\
   Business..Management.and.Accounting                                               & 25.1$^{***}$\\
                                                                                     & (4.90)\\
   Chemical.Engineering                                                              & -17.9$^{***}$\\
                                                                                     & (0.742)\\
   Chemistry                                                                         & -16.8$^{***}$\\
                                                                                     & (0.715)\\
   Computer.Science                                                                  & -32.4$^{***}$\\
                                                                                     & (2.19)\\
   Decision.Sciences                                                                 & 7.37\\
                                                                                     & (54.1)\\
   Dentistry                                                                         & -33.2$^{***}$\\
                                                                                     & (3.23)\\
   Earth.and.Planetary.Sciences                                                      & -28.3$^{***}$\\
                                                                                     & (1.29)\\
   Economics..Econometrics.and.Finance                                               & -4.43\\
                                                                                     & (14.9)\\
   Energy                                                                            & -17.8$^{***}$\\
                                                                                     & (0.576)\\
   Engineering                                                                       & -23.9$^{***}$\\
                                                                                     & (0.754)\\
   Immunology.and.Microbiology                                                       & -32.9$^{***}$\\
                                                                                     & (0.761)\\
   Materials.Science                                                                 & -25.4$^{***}$\\
                                                                                     & (0.776)\\
   Mathematics                                                                       & 7.94\\
                                                                                     & (10.3)\\
   Medicine                                                                          & -37.9$^{***}$\\
                                                                                     & (0.800)\\
   Neuroscience                                                                      & -27.7$^{***}$\\
                                                                                     & (0.751)\\
   Nursing                                                                           & -28.8$^{***}$\\
                                                                                     & (0.825)\\
   Pharmacology..Toxicology.and.Pharmaceutics                                        & -23.2$^{***}$\\
                                                                                     & (1.16)\\
   Physics.and.Astronomy                                                             & 22.7$^{***}$\\
                                                                                     & (0.829)\\
   Psychology                                                                        & -28.1$^{***}$\\
                                                                                     & (3.42)\\
   Social.Sciences                                                                   & -18.8$^{**}$\\
                                                                                     & (7.70)\\
   Veterinary                                                                        & -29.8$^{***}$\\
                                                                                     & (3.08)\\
   CoTypeCollaboration $\times$ ex\_ld\_max\_before\_year\_co\_lead\_binTrue         & 13.1$^{***}$\\
                                                                                     & (2.28)\\
   CoTypeParticipation $\times$ ex\_ld\_max\_before\_year\_co\_lead\_binTrue         & -10.5$^{***}$\\
                                                                                     & (3.00)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                                                     & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                                                      & 294,781\\
   R$^2$                                                                             & 0.06266\\
   Within R$^2$                                                                      & 0.06144\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# 补充一个更deep的point，曾经开展过“Co-lead”,后续合作/参与的收益受损更严重

In [88]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", disciplines, " | PublishedYear")
)
model1 <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model1)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.168124   0.010601  15.859520
CoTypeParticipation                           0.047151   0.014212   3.317634
Arts.and.Humanities                           1.837644   0.072240  25.438148
Biochemistry..Genetics.and.Molecular.Biology  0.498277   0.012207  40.818163
Business..Management.and.Accounting          -0.428431   0.087633  -4.888910
Chemical.Engineering                          0.131064   0.020722   6.324869
Chemistry                                     0.458689   0.010925  41.986380
Computer.Science                              0.896830   0.039192  22.883139
Decision.Sciences                             1.233745   0.187252   6.588695
Dentistry                                     1.993278   0.134826  14.784118
Earth.and.Planetary.Sciences                  0.736660   0.015022  49.039048
Economics..Econometrics.and.Finance          -0.125156   0.298301  -0.419561
Energy                                        0.173190   0.017787   9.737107
Engineering                                   0.339560   0.010213  33.249267
Environmental.Science                         0.570669   0.017255  33.072600
Health.Professions                            1.407273   0.128367  10.962920
Immunology.and.Microbiology                   0.100053   0.026312   3.802612
Materials.Science                             0.025108   0.009434   2.661385
Mathematics                                   0.563191   0.123799   4.549254
Medicine                                      0.768655   0.014474  53.104109
Neuroscience                                  0.459560   0.031942  14.387405
Nursing                                       1.152191   0.043429  26.530236
Pharmacology..Toxicology.and.Pharmaceutics    0.918273   0.047863  19.185553
Physics.and.Astronomy                        -0.258106   0.010956 -23.557539
Psychology                                    0.350436   0.151391   2.314773
Social.Sciences                               0.190551   0.160549   1.186869
Veterinary                                    0.572486   0.204304   2.802123
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          9.0783e-04 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          1.0140e-06 ***
Chemical.Engineering                         2.5345e-10 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            4.4371e-11 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          6.7481e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  1.4318e-04 ***
Materials.Science                            7.7820e-03 **
Mathematics                                  5.3836e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   2.0625e-02 *
Social.Sciences                              2.3528e-01
Veterinary                                   5.0767e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -183,760.0   Adj. Pseudo R2: 0.047631
           BIC:  368,502.4     Squared Cor.: 0.061434

In [89]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+",disciplines, " | PublishedYear")
)
model2 <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model2)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.176029   0.010963  16.055991
CoTypeParticipation                           0.095087   0.014820   6.416025
lnnum_author                                 -0.130941   0.007103 -18.433963
internationalinternational                   -0.007958   0.008684  -0.916399
lnnum_reference                              -0.005923   0.008397  -0.705350
num_fac                                       0.050942   0.006548   7.779950
SDGTrue                                       0.087651   0.008086  10.840337
lnmean_career_age                            -0.007336   0.012674  -0.578814
Arts.and.Humanities                           1.805187   0.072180  25.009688
Biochemistry..Genetics.and.Molecular.Biology  0.488323   0.012268  39.804343
Business..Management.and.Accounting          -0.391345   0.087633  -4.465750
Chemical.Engineering                          0.118096   0.020734   5.695810
Chemistry                                     0.444182   0.010966  40.504784
Computer.Science                              0.885696   0.039163  22.615553
Decision.Sciences                             1.238200   0.185634   6.670124
Dentistry                                     1.986729   0.134600  14.760297
Earth.and.Planetary.Sciences                  0.718174   0.015107  47.537625
Economics..Econometrics.and.Finance          -0.174566   0.297157  -0.587455
Energy                                        0.167031   0.017788   9.390262
Engineering                                   0.327907   0.010299  31.839979
Environmental.Science                         0.543065   0.017326  31.344035
Health.Professions                            1.400534   0.127912  10.949218
Immunology.and.Microbiology                   0.103796   0.026436   3.926278
Materials.Science                             0.017062   0.009536   1.789206
Mathematics                                   0.544282   0.123426   4.409785
Medicine                                      0.770899   0.014524  53.076124
Neuroscience                                  0.459724   0.032017  14.358708
Nursing                                       1.138679   0.043461  26.199802
Pharmacology..Toxicology.and.Pharmaceutics    0.897898   0.047950  18.725619
Physics.and.Astronomy                        -0.245058   0.011148 -21.982119
Psychology                                    0.333723   0.152340   2.190644
Social.Sciences                               0.199570   0.159341   1.252474
Veterinary                                    0.583049   0.205573   2.836216
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          1.3988e-10 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   3.5946e-01
lnnum_reference                              4.8059e-01
num_fac                                      7.2553e-15 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            5.6271e-01
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          7.9789e-06 ***
Chemical.Engineering                         1.2279e-08 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            2.5559e-11 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          5.5690e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  8.6270e-05 ***
Materials.Science                            7.3582e-02 .
Mathematics                                  1.0347e-05 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   2.8478e-02 *
Social.Sciences                              2.1040e-01
Veterinary                                   4.5652e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -183,528.9   Adj. Pseudo R2: 0.048797
           BIC:  368,115.7     Squared Cor.: 0.062365

In [90]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+",disciplines, " | PublishedYear")
)
model3 <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model3)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.143687   0.011097  12.948869
CoTypeParticipation                           0.047011   0.014969   3.140640
lnnum_author                                 -0.068658   0.007116  -9.648419
internationalinternational                   -0.031089   0.009559  -3.252299
lnnum_reference                               0.061520   0.008603   7.150632
num_fac                                       0.059498   0.006605   9.007958
SDGTrue                                       0.092371   0.008114  11.384687
lnmean_career_age                             0.033050   0.012852   2.571617
lnex_ld_avg_avgimpact                        -0.264828   0.007259 -36.483771
lnex_ld_avg_insthindex                       -0.049529   0.007468  -6.632131
ex_ld_bin_gsGlobalNorth                       0.319559   0.017431  18.332975
ex_ld_bin_sameCSame                          -0.088044   0.009395  -9.371276
knowledge_proximity_mean                     -0.536984   0.156999  -3.420305
Arts.and.Humanities                           1.761999   0.072602  24.269151
Biochemistry..Genetics.and.Molecular.Biology  0.560437   0.012537  44.703274
Business..Management.and.Accounting          -0.344905   0.088174  -3.911635
Chemical.Engineering                          0.127998   0.020763   6.164848
Chemistry                                     0.436398   0.011069  39.426244
Computer.Science                              0.885328   0.039395  22.473379
Decision.Sciences                             1.205541   0.188256   6.403744
Dentistry                                     1.932497   0.135449  14.267307
Earth.and.Planetary.Sciences                  0.707815   0.015281  46.318485
Economics..Econometrics.and.Finance          -0.146465   0.292554  -0.500642
Energy                                        0.215856   0.017843  12.097741
Engineering                                   0.301371   0.010388  29.012331
Environmental.Science                         0.556121   0.017498  31.781864
Health.Professions                            1.376601   0.128348  10.725554
Immunology.and.Microbiology                   0.170265   0.026632   6.393299
Materials.Science                             0.001639   0.009727   0.168540
Mathematics                                   0.566115   0.123863   4.570476
Medicine                                      0.805057   0.014620  55.064785
Neuroscience                                  0.513867   0.032067  16.024855
Nursing                                       1.142418   0.043670  26.160014
Pharmacology..Toxicology.and.Pharmaceutics    0.891611   0.047942  18.597867
Physics.and.Astronomy                        -0.293480   0.011296 -25.979886
Psychology                                    0.370676   0.153231   2.419069
Social.Sciences                               0.155397   0.156885   0.990516
Veterinary                                    0.592872   0.205209   2.889114
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          1.6858e-03 **
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.1448e-03 **
lnnum_reference                              8.6379e-13 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            1.0122e-02 *
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       3.3087e-11 ***
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                           < 2.2e-16 ***
knowledge_proximity_mean                     6.2551e-04 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          9.1674e-05 ***
Chemical.Engineering                         7.0551e-10 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            1.5161e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          6.1662e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  1.6234e-10 ***
Materials.Science                            8.6616e-01
Mathematics                                  4.8662e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.5560e-02 *
Social.Sciences                              3.2192e-01
Veterinary                                   3.8633e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -182,548.0   Adj. Pseudo R2: 0.053853
           BIC:  366,216.9     Squared Cor.: 0.068979

In [91]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model4 <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model4)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.099926   0.011245   8.886446
CoTypeParticipation                           0.010299   0.015044   0.684582
lnnum_author                                 -0.087020   0.007328 -11.874570
internationalinternational                   -0.045118   0.009576  -4.711696
lnnum_reference                               0.059057   0.008633   6.841129
num_fac                                       0.062924   0.006715   9.369983
SDGTrue                                       0.093974   0.008128  11.561174
lnmean_career_age                             0.012005   0.013072   0.918354
lnex_ld_avg_avgimpact                        -0.269872   0.007355 -36.690437
lnex_ld_avg_insthindex                       -0.051397   0.007510  -6.844259
ex_ld_bin_gsGlobalNorth                       0.309880   0.017490  17.717256
ex_ld_bin_sameCSame                          -0.063400   0.009432  -6.721559
knowledge_proximity_mean                     -0.519050   0.159415  -3.255960
lnex_ld_avg_before_year_prod_fac             -0.049429   0.004953  -9.979480
ex_ld_max_before_year_with_ih_binTrue         0.341342   0.011341  30.097556
Arts.and.Humanities                           1.739659   0.073159  23.779227
Biochemistry..Genetics.and.Molecular.Biology  0.581832   0.012607  46.150420
Business..Management.and.Accounting          -0.356803   0.087998  -4.054647
Chemical.Engineering                          0.134750   0.020810   6.475235
Chemistry                                     0.423471   0.011105  38.132697
Computer.Science                              0.895903   0.039528  22.665211
Decision.Sciences                             1.190685   0.189362   6.287886
Dentistry                                     1.903426   0.136163  13.979002
Earth.and.Planetary.Sciences                  0.710429   0.015254  46.572210
Economics..Econometrics.and.Finance          -0.112709   0.295110  -0.381923
Energy                                        0.199571   0.017872  11.166486
Engineering                                   0.283702   0.010425  27.213022
Environmental.Science                         0.563181   0.017461  32.253949
Health.Professions                            1.369455   0.128704  10.640324
Immunology.and.Microbiology                   0.192720   0.026784   7.195428
Materials.Science                            -0.021025   0.009864  -2.131434
Mathematics                                   0.545550   0.125475   4.347874
Medicine                                      0.823541   0.014724  55.930203
Neuroscience                                  0.518029   0.032283  16.046508
Nursing                                       1.134037   0.043674  25.965997
Pharmacology..Toxicology.and.Pharmaceutics    0.892005   0.048193  18.509024
Physics.and.Astronomy                        -0.309036   0.011406 -27.095196
Psychology                                    0.395773   0.155025   2.552955
Social.Sciences                               0.123036   0.157185   0.782746
Veterinary                                    0.590046   0.206852   2.852509
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          4.9361e-01
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   2.4566e-06 ***
lnnum_reference                              7.8571e-12 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            3.5843e-01
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       7.6873e-12 ***
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                          1.7979e-11 ***
knowledge_proximity_mean                     1.1301e-03 **
lnex_ld_avg_before_year_prod_fac              < 2.2e-16 ***
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          5.0210e-05 ***
Chemical.Engineering                         9.4665e-11 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            3.2182e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.0252e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  6.2265e-13 ***
Materials.Science                            3.3053e-02 *
Mathematics                                  1.3746e-05 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.0681e-02 *
Social.Sciences                              4.3378e-01
Veterinary                                   4.3376e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -182,077.2   Adj. Pseudo R2: 0.056282
           BIC:  365,300.4     Squared Cor.: 0.072158

In [92]:
# 直接把 4 个模型并排放在一起
tab_latex <- etable(model1, model2, model3, model4,
                    keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                    se = "hetero",
                    tex = TRUE,
                    digits = 3,
                    fitstat = ~ n + r2 + ar2) # 可选：指定要在底部报告的统计量（如样本量、R方、调整R方）

# 打印出可以直接复制到 LaTeX 的代码
cat(tab_latex)

\begingroup \centering \begin{tabular}{lcccc}    \tabularnewline \midrule \midrule    Dependent Variable: & \multicolumn{4}{c}{novel\_uzzi\_bin}\\    Model:                                              & (1)            & (2)            & (3)            & (4)\\      \midrule    \emph{Variables}\\    CoTypeCollaboration                                 & 0.168$^{***}$  & 0.176$^{***}$  & 0.144$^{***}$  & 0.100$^{***}$\\                                                           & (0.011)        & (0.011)        & (0.011)        & (0.011)\\       CoTypeParticipation                                 & 0.047$^{***}$  & 0.095$^{***}$  & 0.047$^{***}$  & 0.010\\                                                           & (0.014)        & (0.015)        & (0.015)        & (0.015)\\       Arts.and.Humanities                                 & 1.84$^{***}$   & 1.81$^{***}$   & 1.76$^{***}$   & 1.74$^{***}$\\                                                           & (0.072)        & (0.072)        & (0.073)        & (0.073)\\       Biochemistry..Genetics.and.Molecular.Biology        & 0.498$^{***}$  & 0.488$^{***}$  & 0.560$^{***}$  & 0.582$^{***}$\\                                                           & (0.012)        & (0.012)        & (0.013)        & (0.013)\\       Business..Management.and.Accounting                 & -0.428$^{***}$ & -0.391$^{***}$ & -0.345$^{***}$ & -0.357$^{***}$\\                                                           & (0.088)        & (0.088)        & (0.088)        & (0.088)\\       Chemical.Engineering                                & 0.131$^{***}$  & 0.118$^{***}$  & 0.128$^{***}$  & 0.135$^{***}$\\                                                           & (0.021)        & (0.021)        & (0.021)        & (0.021)\\       Chemistry                                           & 0.459$^{***}$  & 0.444$^{***}$  & 0.436$^{***}$  & 0.423$^{***}$\\                                                           & (0.011)        & (0.011)        & (0.011)        & (0.011)\\       Computer.Science                                    & 0.897$^{***}$  & 0.886$^{***}$  & 0.885$^{***}$  & 0.896$^{***}$\\                                                           & (0.039)        & (0.039)        & (0.039)        & (0.040)\\       Decision.Sciences                                   & 1.23$^{***}$   & 1.24$^{***}$   & 1.21$^{***}$   & 1.19$^{***}$\\                                                           & (0.187)        & (0.186)        & (0.188)        & (0.189)\\       Dentistry                                           & 1.99$^{***}$   & 1.99$^{***}$   & 1.93$^{***}$   & 1.90$^{***}$\\                                                           & (0.135)        & (0.135)        & (0.135)        & (0.136)\\       Earth.and.Planetary.Sciences                        & 0.737$^{***}$  & 0.718$^{***}$  & 0.708$^{***}$  & 0.710$^{***}$\\                                                           & (0.015)        & (0.015)        & (0.015)        & (0.015)\\       Economics..Econometrics.and.Finance                 & -0.125         & -0.175         & -0.146         & -0.113\\                                                           & (0.298)        & (0.297)        & (0.293)        & (0.295)\\       Energy                                              & 0.173$^{***}$  & 0.167$^{***}$  & 0.216$^{***}$  & 0.200$^{***}$\\                                                           & (0.018)        & (0.018)        & (0.018)        & (0.018)\\       Engineering                                         & 0.340$^{***}$  & 0.328$^{***}$  & 0.301$^{***}$  & 0.284$^{***}$\\                                                           & (0.010)        & (0.010)        & (0.010)        & (0.010)\\       Immunology.and.Microbiology                         & 0.100$^{***}$  & 0.104$^{***}$  & 0.170$^{***}$  & 0.193$^{***}$\\                                                           & (0.026)        & (0.026)        & (0.027)        & (0.027)\\       Materials.Science                                   & 0.025$^{***}$  & 0.017$^{*}$    & 0.002          & -0.021$^{**}$\\                                                           & (0.009)        & (0.010)        & (0.010)        & (0.010)\\       Mathematics                                         & 0.563$^{***}$  & 0.544$^{***}$  & 0.566$^{***}$  & 0.546$^{***}$\\                                                           & (0.124)        & (0.123)        & (0.124)        & (0.125)\\       Medicine                                            & 0.769$^{***}$  & 0.771$^{***}$  & 0.805$^{***}$  & 0.824$^{***}$\\                                                           & (0.015)        & (0.015)        & (0.015)        & (0.015)\\       Neuroscience                                        & 0.460$^{***}$  & 0.460$^{***}$  & 0.514$^{***}$  & 0.518$^{***}$\\                                                           & (0.032)        & (0.032)        & (0.032)        & (0.032)\\       Nursing                                             & 1.15$^{***}$   & 1.14$^{***}$   & 1.14$^{***}$   & 1.13$^{***}$\\                                                           & (0.043)        & (0.043)        & (0.044)        & (0.044)\\       Pharmacology..Toxicology.and.Pharmaceutics          & 0.918$^{***}$  & 0.898$^{***}$  & 0.892$^{***}$  & 0.892$^{***}$\\                                                           & (0.048)        & (0.048)        & (0.048)        & (0.048)\\       Physics.and.Astronomy                               & -0.258$^{***}$ & -0.245$^{***}$ & -0.293$^{***}$ & -0.309$^{***}$\\                                                           & (0.011)        & (0.011)        & (0.011)        & (0.011)\\       Psychology                                          & 0.350$^{**}$   & 0.334$^{**}$   & 0.371$^{**}$   & 0.396$^{**}$\\                                                           & (0.151)        & (0.152)        & (0.153)        & (0.155)\\       Social.Sciences                                     & 0.191          & 0.200          & 0.155          & 0.123\\                                                           & (0.161)        & (0.159)        & (0.157)        & (0.157)\\       Veterinary                                          & 0.572$^{***}$  & 0.583$^{***}$  & 0.593$^{***}$  & 0.590$^{***}$\\                                                           & (0.204)        & (0.206)        & (0.205)        & (0.207)\\       lnnum\_author                                       &                & -0.131$^{***}$ & -0.069$^{***}$ & -0.087$^{***}$\\                                                           &                & (0.007)        & (0.007)        & (0.007)\\       internationalinternational                          &                & -0.008         & -0.031$^{***}$ & -0.045$^{***}$\\                                                           &                & (0.009)        & (0.010)        & (0.010)\\       lnnum\_reference                                    &                & -0.006         & 0.061$^{***}$  & 0.059$^{***}$\\                                                           &                & (0.008)        & (0.009)        & (0.009)\\       num\_fac                                            &                & 0.051$^{***}$  & 0.059$^{***}$  & 0.063$^{***}$\\                                                           &                & (0.007)        & (0.007)        & (0.007)\\       SDGTrue                                             &                & 0.088$^{***}$  & 0.092$^{***}$  & 0.094$^{***}$\\                                                           &                & (0.008)        & (0.008)        & (0.008)\\       lnmean\_career\_age                                 &                & -0.007         & 0.033$^{**}$   & 0.012\\                                                           &                & (0.013)        & (0.013)        & (0.013)\\       lnex\_ld\_avg\_avgimpact                            &                &                & -0.265$^{***}$ & -0.270$^{***}$\\                                                           &                &                & (0.007)        & (0.007)\\       lnex\_ld\_avg\_insthindex                           &                &                & -0.050$^{***}$ & -0.051$^{***}$\\                                                           &                &                & (0.007)        & (0.008)\\       ex\_ld\_bin\_gsGlobalNorth                          &                &                & 0.320$^{***}$  & 0.310$^{***}$\\                                                           &                &                & (0.017)        & (0.018)\\       ex\_ld\_bin\_sameCSame                              &                &                & -0.088$^{***}$ & -0.063$^{***}$\\                                                           &                &                & (0.009)        & (0.009)\\       knowledge\_proximity\_mean                          &                &                & -0.537$^{***}$ & -0.519$^{***}$\\                                                           &                &                & (0.157)        & (0.159)\\       lnex\_ld\_avg\_before\_year\_prod\_fac              &                &                &                & -0.049$^{***}$\\                                                           &                &                &                & (0.005)\\       ex\_ld\_max\_before\_year\_with\_ih\_binTrue        &                &                &                & 0.341$^{***}$\\                                                           &                &                &                & (0.011)\\       \midrule    \emph{Fixed-effects}\\    PublishedYear                                       & Yes            & Yes            & Yes            & Yes\\      \midrule    \emph{Fit statistics}\\    Observations                                        & 294,879        & 294,879        & 294,879        & 294,879\\      \midrule \midrule    \multicolumn{5}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\    \multicolumn{5}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\ \end{tabular} \par\endgroup