In [2]:
library("lme4")
library("margins")
library("stargazer")
library("emmeans")
library("ggeffects")
library("broom")
library("broom.mixed")
library("MASS")
library("pscl")
library("fixest")
library("marginaleffects")
library("modelsummary")
library("glmmTMB")
library("dplyr")

In [3]:
packageVersion("marginaleffects")

[1] ‘0.25.1’

In [4]:
main_path <- "/home/20250114zmz_kd/"
data <- read.csv(paste0(main_path, "GraduationPaper/RevisetoJournal/99921-FirstAuthorMergeSimilarity.csv"))
dim(data)

[1] 319680     92

In [5]:
print(names(data))

 [1] "X"
 [2] "work_id"
 [3] "PublishedYear"
 [4] "Facility"
 [5] "num_fac"
 [6] "paper_type"
 [7] "paper_language"
 [8] "novel_uzzi"
 [9] "novel_uzzi_bin"
[10] "num_fac_scientist"
[11] "ratio_fac_scientist"
[12] "bin_fac_scientist"
[13] "text_fac_scientist"
[14] "fac_scientist_team"
[15] "num_leader"
[16] "ratio_leader"
[17] "bin_leader"
[18] "fac_scientist_lead_num"
[19] "fac_scientist_lead_ratio"
[20] "fac_scientist_lead_bin"
[21] "fac_scientist_lead_text"
[22] "CoType"
[23] "CoType_Collaboration"
[24] "CoType_Participation"
[25] "CoType_Service"
[26] "lnnum_author"
[27] "lnnum_inst"
[28] "international"
[29] "lnnum_country"
[30] "lnnum_reference"
[31] "open_access"
[32] "RaoStirling"
[33] "SDG"
[34] "lntimescited5"
[35] "lntimescited10"
[36] "lntimescitedall"
[37] "lnab_length"
[38] "lnmean_career_age"
[39] "first_author"
[40] "lnfirst_avgimpact"
[41] "first_SameCountry"
[42] "first_GlobalSouth"
[43] "lnfirst_insthindex"
[44] "lnfirst_before_year_prod_fac"
[45] "first_before_year_with_ih_bin"
[46] "first_before_year_co_lead_bin"
[47] "first_before_year_participation_bin"
[48] "Agricultural.and.Biological.Sciences"
[49] "Arts.and.Humanities"
[50] "Biochemistry..Genetics.and.Molecular.Biology"
[51] "Business..Management.and.Accounting"
[52] "Chemical.Engineering"
[53] "Chemistry"
[54] "Computer.Science"
[55] "Decision.Sciences"
[56] "Dentistry"
[57] "Earth.and.Planetary.Sciences"
[58] "Economics..Econometrics.and.Finance"
[59] "Energy"
[60] "Engineering"
[61] "Environmental.Science"
[62] "Health.Professions"
[63] "Immunology.and.Microbiology"
[64] "Materials.Science"
[65] "Mathematics"
[66] "Medicine"
[67] "Neuroscience"
[68] "Nursing"
[69] "Pharmacology..Toxicology.and.Pharmaceutics"
[70] "Physics.and.Astronomy"
[71] "Psychology"
[72] "Social.Sciences"
[73] "Veterinary"
[74] "domain_Health.Sciences"
[75] "domain_Life.Sciences"
[76] "domain_Physical.Sciences"
[77] "domain_Social.Sciences"
[78] "sum"
[79] "num_author"
[80] "num_inst"
[81] "num_country"
[82] "num_reference"
[83] "timescited5"
[84] "timescited10"
[85] "timescitedall"
[86] "ab_length"
[87] "mean_career_age"
[88] "first_avgimpact"
[89] "first_insthindex"
[90] "first_before_year_prod_fac"
[91] "knowledge_proximity_mean"
[92] "knowledge_proximity_max"

In [6]:
colSums(is.na(data))

                                           X
                                           0
                                     work_id
                                           0
                               PublishedYear
                                           0
                                    Facility
                                           0
                                     num_fac
                                           0
                                  paper_type
                                           0
                              paper_language
                                           0
                                  novel_uzzi
                                        2615
                              novel_uzzi_bin
                                           0
                           num_fac_scientist
                                           0
                         ratio_fac_scientist
                                           0
                           bin_fac_scientist
                                           0
                          text_fac_scientist
                                           0
                          fac_scientist_team
                                           0
                                  num_leader
                                           0
                                ratio_leader
                                           0
                                  bin_leader
                                           0
                      fac_scientist_lead_num
                                           0
                    fac_scientist_lead_ratio
                                           0
                      fac_scientist_lead_bin
                                           0
                     fac_scientist_lead_text
                                           0
                                      CoType
                                           0
                        CoType_Collaboration
                                           0
                        CoType_Participation
                                           0
                              CoType_Service
                                           0
                                lnnum_author
                                           0
                                  lnnum_inst
                                           0
                               international
                                           0
                               lnnum_country
                                           0
                             lnnum_reference
                                           0
                                 open_access
                                           0
                                 RaoStirling
                                           0
                                         SDG
                                           0
                               lntimescited5
                                       14783
                              lntimescited10
                                       12968
                             lntimescitedall
                                           0
                                 lnab_length
                                           0
                           lnmean_career_age
                                           0
                                first_author
                                           0
                           lnfirst_avgimpact
                                           0
                           first_SameCountry
                                           0
                           first_GlobalSouth
                                           0
                          lnfirst_insthindex
                                           0
                lnfirst_before_year_prod_fac
                                           0
               first_before_year_with_ih_bin
                                           0
               first_before_year_co_lead_bin
                                           0
         first_before_year_participation_bin
                                           0
        Agricultural.and.Biological.Sciences
                                           0
                         Arts.and.Humanities
                                           0
Biochemistry..Genetics.and.Molecular.Biology
                                           0
         Business..Management.and.Accounting
                                           0
                        Chemical.Engineering
                                           0
                                   Chemistry
                                           0
                            Computer.Science
                                           0
                           Decision.Sciences
                                           0
                                   Dentistry
                                           0
                Earth.and.Planetary.Sciences
                                           0
         Economics..Econometrics.and.Finance
                                           0
                                      Energy
                                           0
                                 Engineering
                                           0
                       Environmental.Science
                                           0
                          Health.Professions
                                           0
                 Immunology.and.Microbiology
                                           0
                           Materials.Science
                                           0
                                 Mathematics
                                           0
                                    Medicine
                                           0
                                Neuroscience
                                           0
                                     Nursing
                                           0
  Pharmacology..Toxicology.and.Pharmaceutics
                                           0
                       Physics.and.Astronomy
                                           0
                                  Psychology
                                           0
                             Social.Sciences
                                           0
                                  Veterinary
                                           0
                      domain_Health.Sciences
                                           0
                        domain_Life.Sciences
                                           0
                    domain_Physical.Sciences
                                           0
                      domain_Social.Sciences
                                           0
                                         sum
                                           0
                                  num_author
                                           0
                                    num_inst
                                           0
                                 num_country
                                           0
                               num_reference
                                           0
                                 timescited5
                                       14783
                                timescited10
                                       12968
                               timescitedall
                                           0
                                   ab_length
                                           0
                             mean_career_age
                                           0
                             first_avgimpact
                                        1192
                            first_insthindex
                                           0
                  first_before_year_prod_fac
                                           0
                    knowledge_proximity_mean
                                      108617
                     knowledge_proximity_max
                                      108617

In [7]:
# 把所有无限值替换成 NA
data[sapply(data, is.infinite)] <- NA

In [8]:
# data <- data %>% filter(!is.na(mean_career_age))
# data <- data %>% filter(!is.na(frac_hype_words))
# data <- data %>% filter(!is.na(source_hindex))
# data <- data %>% filter(!is.na(open_access))
# dim(data)

In [9]:
# 找出所有包含无限值的行和列
inf_mask <- sapply(data, function(col) is.infinite(col))
rows_with_inf <- apply(inf_mask, 1, any)  # 哪些行至少有一个Inf
cols_with_inf <- colnames(data)[apply(inf_mask, 2, any)]  # 哪些列有Inf

# 打印包含无限值的行数和列名
cat("包含无限值的行数:", sum(rows_with_inf), "\n")
cat("包含无限值的列名:", paste(cols_with_inf, collapse = ", "), "\n")

# 查看这些行具体内容
data_filt_with_inf <- data[rows_with_inf, c(cols_with_inf), drop=FALSE]
print(data_filt_with_inf)

包含无限值的行数: 0
包含无限值的列名:
data frame with 0 columns and 0 rows

In [10]:
data$Facility <- as.factor(data$Facility)

In [11]:
data$CoType <- factor(data$CoType)
data <- within(data, CoType <- relevel(CoType, ref = 'Service'))
data$paper_type <- factor(data$paper_type)
data <- within(data, paper_type <- relevel(paper_type, ref = 'review'))
data$text_fac_scientist <- factor(data$text_fac_scientist)
data <- within(data, text_fac_scientist <- relevel(text_fac_scientist, ref = 'NonStaffPart'))
data$fac_scientist_lead_text <- factor(data$fac_scientist_lead_text)
data <- within(data, fac_scientist_lead_text <- relevel(fac_scientist_lead_text, ref = 'NonStaffLead'))
data$open_access <- factor(data$open_access)
data <- within(data, open_access <- relevel(open_access, ref = 'False'))
data$SDG <- factor(data$SDG)
data <- within(data, SDG <- relevel(SDG, ref = 'False'))
data$first_SameCountry <- factor(data$first_SameCountry)
data <- within(data, first_SameCountry <- relevel(first_SameCountry, ref = 'NonSame'))
data$first_GlobalSouth <- factor(data$first_GlobalSouth)
data <- within(data, first_GlobalSouth <- relevel(first_GlobalSouth, ref = 'GlobalSouth'))
data$first_before_year_with_ih_bin <- factor(data$first_before_year_with_ih_bin)
data <- within(data, first_before_year_with_ih_bin <- relevel(first_before_year_with_ih_bin, ref = 'False'))
data$first_before_year_participation_bin <- factor(data$first_before_year_participation_bin)
data <- within(data, first_before_year_participation_bin <- relevel(first_before_year_participation_bin, ref = 'False'))
data$first_before_year_co_lead_bin <- factor(data$first_before_year_co_lead_bin)
data <- within(data, first_before_year_co_lead_bin <- relevel(first_before_year_co_lead_bin, ref = 'False'))
data$international <- factor(data$international)
data <- within(data, international <- relevel(international, ref = 'domestic'))

In [12]:
paper_level <- "lnnum_author + international + lnnum_reference + num_fac + SDG + lnmean_career_age"
ex_controls <- "lnfirst_avgimpact + lnfirst_insthindex + first_GlobalSouth + first_SameCountry + knowledge_proximity_mean"
moderating <- "lnfirst_before_year_prod_fac + first_before_year_with_ih_bin"
moderating2 <- "lnfirst_before_year_prod_fac + first_before_year_participation_bin"
moderating3 <- "lnfirst_before_year_prod_fac + first_before_year_co_lead_bin"
disciplines <- "Agricultural.and.Biological.Sciences + Arts.and.Humanities + Biochemistry..Genetics.and.Molecular.Biology + Business..Management.and.Accounting + Chemical.Engineering + 
 Chemistry + Computer.Science + Decision.Sciences + Dentistry + Earth.and.Planetary.Sciences + 
Economics..Econometrics.and.Finance + Energy + Engineering + Environmental.Science + Health.Professions + 
Immunology.and.Microbiology + Materials.Science + Mathematics + Medicine + Neuroscience + Nursing +
Pharmacology..Toxicology.and.Pharmaceutics + Physics.and.Astronomy + Psychology + Social.Sciences + Veterinary "

In [13]:
paper_vars <- c("lnnum_author", "international", "lnnum_reference", "num_fac", "SDG", "lnmean_career_age")
ex_vars <- c("lnfirst_avgimpact", "lnfirst_insthindex", "first_GlobalSouth", "first_SameCountry", "knowledge_proximity_mean")
moderating_var <- c("lnfirst_before_year_prod_fac", "first_before_year_with_ih_bin")
moderating2_var <- c("lnfirst_before_year_prod_fac", "first_before_year_participation_bin")
moderating3_var <- c("lnfirst_before_year_prod_fac", "first_before_year_co_lead_bin")
disciplines_vars <- c("Agricultural.and.Biological.Sciences", "Arts.and.Humanities", "Biochemistry..Genetics.and.Molecular.Biology", "Business..Management.and.Accounting",
                 "Chemical.Engineering", "Chemistry", "Computer.Science", "Decision.Sciences", "Dentistry",
                 "Earth.and.Planetary.Sciences", "Economics..Econometrics.and.Finance", "Energy", "Engineering",
                 "Environmental.Science + Health.Professions", "Immunology.and.Microbiology", "Materials.Science", "Mathematics",
                 "Medicine", "Neuroscience", "Nursing", "Pharmacology..Toxicology.and.Pharmaceutics", "Physics.and.Astronomy",
                 "Psychology", "Social.Sciences", "Veterinary")

# H1:With > Without

In [14]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_total_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_total_bin)

NOTE: 107,910 observations removed because of NA values (LHS: 107,910, RHS: 107,910, Fixed-effects: 107,910).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 209,290
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
text_fac_scientistStaffPart                   0.056941   0.012310   4.625696
lnnum_author                                 -0.146121   0.008259 -17.691542
internationalinternational                   -0.038701   0.011456  -3.378332
lnnum_reference                              -0.000195   0.010153  -0.019180
num_fac                                       0.080824   0.007862  10.280264
SDGTrue                                       0.055158   0.009888   5.578043
lnmean_career_age                             0.022865   0.015981   1.430744
lnfirst_avgimpact                            -0.113022   0.005716 -19.774226
lnfirst_insthindex                           -0.065135   0.006691  -9.734713
first_GlobalSouthGlobalNorth                  0.313134   0.019720  15.879078
first_SameCountrySame                        -0.107616   0.011303  -9.521331
knowledge_proximity_mean                     -0.263546   0.159430  -1.653051
lnfirst_before_year_prod_fac                  0.009041   0.005506   1.642204
first_before_year_with_ih_binTrue             0.167752   0.013390  12.528098
Agricultural.and.Biological.Sciences          0.808036   0.031270  25.840210
Arts.and.Humanities                           1.795609   0.086083  20.858944
Biochemistry..Genetics.and.Molecular.Biology  0.640525   0.015431  41.509284
Business..Management.and.Accounting          -0.388160   0.098956  -3.922557
Chemical.Engineering                          0.210352   0.025599   8.217037
Chemistry                                     0.484940   0.013593  35.675426
Computer.Science                              0.906912   0.049155  18.450125
Decision.Sciences                             1.357437   0.221724   6.122204
Dentistry                                     2.079583   0.176393  11.789489
Earth.and.Planetary.Sciences                  0.782575   0.018145  43.129580
Economics..Econometrics.and.Finance          -0.132400   0.383755  -0.345012
Energy                                        0.260024   0.021753  11.953673
Engineering                                   0.338696   0.012575  26.933072
Environmental.Science                         0.494520   0.022258  22.217573
Health.Professions                            1.597527   0.155144  10.297026
Immunology.and.Microbiology                   0.219543   0.036323   6.044157
Materials.Science                             0.062586   0.011854   5.279789
Mathematics                                   0.404410   0.147864   2.735004
Medicine                                      0.891575   0.019125  46.617584
Neuroscience                                  0.516603   0.042259  12.224629
Nursing                                       1.176117   0.063042  18.656082
Pharmacology..Toxicology.and.Pharmaceutics    0.832868   0.064645  12.883763
Physics.and.Astronomy                        -0.257123   0.013587 -18.924802
Psychology                                    0.285367   0.184004   1.550871
Social.Sciences                               0.332004   0.187053   1.774921
Veterinary                                    0.646158   0.302367   2.137000
                                               Pr(>|z|)
text_fac_scientistStaffPart                  3.7334e-06 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   7.2927e-04 ***
lnnum_reference                              9.8470e-01
num_fac                                       < 2.2e-16 ***
SDGTrue                                      2.4324e-08 ***
lnmean_career_age                            1.5250e-01
lnfirst_avgimpact                             < 2.2e-16 ***
lnfirst_insthindex                            < 2.2e-16 ***
first_GlobalSouthGlobalNorth                  < 2.2e-16 ***
first_SameCountrySame                         < 2.2e-16 ***
knowledge_proximity_mean                     9.8321e-02 .
lnfirst_before_year_prod_fac                 1.0055e-01
first_before_year_with_ih_binTrue             < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          8.7614e-05 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            9.2290e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.3009e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  1.5019e-09 ***
Materials.Science                            1.2933e-07 ***
Mathematics                                  6.2379e-03 **
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.2093e-01
Social.Sciences                              7.5911e-02 .
Veterinary                                   3.2598e-02 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -125,437.8   Adj. Pseudo R2: 0.058989
           BIC:  251,990.5     Squared Cor.: 0.073914

In [16]:
# 每组 reg_class 的平均预测概率
pred_bin <- avg_predictions(model_total_bin, variables = "text_fac_scientist")
pred_bin

  text_fac_scientist estimate  std.error  statistic p.value      s.value
1 NonStaffPart       0.3311349 0.03085053 10.73353  7.084052e-27 86.86748
2 StaffPart          0.3428821 0.03140677 10.91746  9.512298e-28 89.76419
  conf.low  conf.high
1 0.2706690 0.3916009
2 0.2813259 0.4044382

In [14]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_pred.csv")
# write.csv(pred_bin, fname, row.names = FALSE)

In [17]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_total_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                & 0.057$^{***}$\\
                                                & (0.012)\\
   lnnum\_author                                & -0.146$^{***}$\\
                                                & (0.008)\\
   internationalinternational                   & -0.039$^{***}$\\
                                                & (0.011)\\
   lnnum\_reference                             & -0.0002\\
                                                & (0.010)\\
   num\_fac                                     & 0.081$^{***}$\\
                                                & (0.008)\\
   SDGTrue                                      & 0.055$^{***}$\\
                                                & (0.010)\\
   lnmean\_career\_age                          & 0.023\\
                                                & (0.016)\\
   lnfirst\_avgimpact                           & -0.113$^{***}$\\
                                                & (0.006)\\
   lnfirst\_insthindex                          & -0.065$^{***}$\\
                                                & (0.007)\\
   first\_GlobalSouthGlobalNorth                & 0.313$^{***}$\\
                                                & (0.020)\\
   first\_SameCountrySame                       & -0.108$^{***}$\\
                                                & (0.011)\\
   knowledge\_proximity\_mean                   & -0.264$^{*}$\\
                                                & (0.159)\\
   lnfirst\_before\_year\_prod\_fac             & 0.009\\
                                                & (0.006)\\
   first\_before\_year\_with\_ih\_binTrue       & 0.168$^{***}$\\
                                                & (0.013)\\
   Agricultural.and.Biological.Sciences         & 0.808$^{***}$\\
                                                & (0.031)\\
   Arts.and.Humanities                          & 1.80$^{***}$\\
                                                & (0.086)\\
   Biochemistry..Genetics.and.Molecular.Biology & 0.641$^{***}$\\
                                                & (0.015)\\
   Business..Management.and.Accounting          & -0.388$^{***}$\\
                                                & (0.099)\\
   Chemical.Engineering                         & 0.210$^{***}$\\
                                                & (0.026)\\
   Chemistry                                    & 0.485$^{***}$\\
                                                & (0.014)\\
   Computer.Science                             & 0.907$^{***}$\\
                                                & (0.049)\\
   Decision.Sciences                            & 1.36$^{***}$\\
                                                & (0.222)\\
   Dentistry                                    & 2.08$^{***}$\\
                                                & (0.176)\\
   Earth.and.Planetary.Sciences                 & 0.783$^{***}$\\
                                                & (0.018)\\
   Economics..Econometrics.and.Finance          & -0.132\\
                                                & (0.384)\\
   Energy                                       & 0.260$^{***}$\\
                                                & (0.022)\\
   Engineering                                  & 0.339$^{***}$\\
                                                & (0.013)\\
   Immunology.and.Microbiology                  & 0.220$^{***}$\\
                                                & (0.036)\\
   Materials.Science                            & 0.063$^{***}$\\
                                                & (0.012)\\
   Mathematics                                  & 0.404$^{***}$\\
                                                & (0.148)\\
   Medicine                                     & 0.892$^{***}$\\
                                                & (0.019)\\
   Neuroscience                                 & 0.517$^{***}$\\
                                                & (0.042)\\
   Nursing                                      & 1.18$^{***}$\\
                                                & (0.063)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.833$^{***}$\\
                                                & (0.065)\\
   Physics.and.Astronomy                        & -0.257$^{***}$\\
                                                & (0.014)\\
   Psychology                                   & 0.285\\
                                                & (0.184)\\
   Social.Sciences                              & 0.332$^{*}$\\
                                                & (0.187)\\
   Veterinary                                   & 0.646$^{**}$\\
                                                & (0.302)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 209,290\\
   Squared Correlation                          & 0.07391\\
   Pseudo R$^2$                                 & 0.05966\\
   BIC                                          & 251,990.5\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [18]:
margins_eff_bin <- avg_comparisons(model_total_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.035475 0.007965537
  statistic p.value s.value conf.low conf.high predicted_lo predicted_hi
1 129.9944  0       Inf     1.019863 1.051088  0.2443508    0.2550169
  predicted
1 0.2443508

In [19]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_comp_ratio.csv")
# write.csv(margins_eff_bin, fname, row.names = FALSE)

# H1 different disciplines

In [20]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ps_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_ps_bin)

NOTE: 87,802 observations removed because of NA values (LHS: 87,802, RHS: 87,802, Fixed-effects: 87,802).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 184,750
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
text_fac_scientistStaffPart                   0.041653   0.012906   3.227369
lnnum_author                                 -0.205165   0.009118 -22.499944
internationalinternational                   -0.069024   0.012408  -5.562760
lnnum_reference                               0.028875   0.010713   2.695215
num_fac                                       0.114524   0.008372  13.679530
SDGTrue                                       0.003450   0.010699   0.322468
lnmean_career_age                            -0.021198   0.017180  -1.233908
lnfirst_avgimpact                            -0.091296   0.006307 -14.475383
lnfirst_insthindex                           -0.039293   0.007271  -5.403903
first_GlobalSouthGlobalNorth                  0.312973   0.021063  14.859227
first_SameCountrySame                        -0.105097   0.012276  -8.561191
knowledge_proximity_mean                      0.125678   0.173672   0.723651
lnfirst_before_year_prod_fac                  0.012123   0.005882   2.061165
first_before_year_with_ih_binTrue             0.143428   0.014133  10.148198
Agricultural.and.Biological.Sciences          1.081425   0.047493  22.769992
Arts.and.Humanities                           1.807413   0.089368  20.224313
Biochemistry..Genetics.and.Molecular.Biology  0.831823   0.017504  47.521959
Business..Management.and.Accounting          -0.364562   0.098732  -3.692430
Chemical.Engineering                          0.218193   0.025773   8.466043
Chemistry                                     0.435546   0.014594  29.843432
Computer.Science                              0.832292   0.050524  16.473237
Decision.Sciences                             1.479177   0.230478   6.417857
Dentistry                                     2.522873   0.259100   9.737078
Earth.and.Planetary.Sciences                  0.792883   0.018502  42.853188
Economics..Econometrics.and.Finance          -0.144071   0.384035  -0.375150
Energy                                        0.256037   0.022232  11.516734
Engineering                                   0.344552   0.013344  25.820395
Environmental.Science                         0.401569   0.023902  16.800643
Health.Professions                            1.815774   0.172580  10.521328
Immunology.and.Microbiology                   0.503786   0.094024   5.358049
Materials.Science                             0.028385   0.012867   2.205983
Mathematics                                   0.374725   0.148732   2.519463
Medicine                                      1.032544   0.028956  35.658528
Neuroscience                                  0.753856   0.074878  10.067777
Nursing                                       1.524301   0.102141  14.923520
Pharmacology..Toxicology.and.Pharmaceutics    0.689136   0.088862   7.755081
Physics.and.Astronomy                        -0.262051   0.014360 -18.248328
Psychology                                   -0.484892   0.325503  -1.489669
Social.Sciences                               0.406011   0.224013   1.812446
Veterinary                                    1.363527   0.725785   1.878693
                                               Pr(>|z|)
text_fac_scientistStaffPart                  1.2493e-03 **
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   2.6554e-08 ***
lnnum_reference                              7.0343e-03 **
num_fac                                       < 2.2e-16 ***
SDGTrue                                      7.4710e-01
lnmean_career_age                            2.1724e-01
lnfirst_avgimpact                             < 2.2e-16 ***
lnfirst_insthindex                           6.5206e-08 ***
first_GlobalSouthGlobalNorth                  < 2.2e-16 ***
first_SameCountrySame                         < 2.2e-16 ***
knowledge_proximity_mean                     4.6928e-01
lnfirst_before_year_prod_fac                 3.9287e-02 *
first_before_year_with_ih_binTrue             < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          2.2212e-04 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            1.3821e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.0755e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  8.4126e-08 ***
Materials.Science                            2.7385e-02 *
Mathematics                                  1.1753e-02 *
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   8.8287e-15 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.3631e-01
Social.Sciences                              6.9917e-02 .
Veterinary                                   6.0286e-02 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -108,655.3   Adj. Pseudo R2: 0.063662
           BIC:  218,414.2     Squared Cor.: 0.079342

In [21]:
margins_eff_ps_bin <- avg_comparisons(model_ps_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_ps_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.026194 0.008300008
  statistic p.value s.value conf.low conf.high predicted_lo predicted_hi
1 123.6377  0       Inf     1.009926 1.042462  0.24514      0.2529292
  predicted
1 0.24514

In [22]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_ps_comp_ratio.csv")
# write.csv(margins_eff_ps_bin, fname, row.names = FALSE)

In [23]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ps_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                & 0.042$^{***}$\\
                                                & (0.013)\\
   lnnum\_author                                & -0.205$^{***}$\\
                                                & (0.009)\\
   internationalinternational                   & -0.069$^{***}$\\
                                                & (0.012)\\
   lnnum\_reference                             & 0.029$^{***}$\\
                                                & (0.011)\\
   num\_fac                                     & 0.115$^{***}$\\
                                                & (0.008)\\
   SDGTrue                                      & 0.003\\
                                                & (0.011)\\
   lnmean\_career\_age                          & -0.021\\
                                                & (0.017)\\
   lnfirst\_avgimpact                           & -0.091$^{***}$\\
                                                & (0.006)\\
   lnfirst\_insthindex                          & -0.039$^{***}$\\
                                                & (0.007)\\
   first\_GlobalSouthGlobalNorth                & 0.313$^{***}$\\
                                                & (0.021)\\
   first\_SameCountrySame                       & -0.105$^{***}$\\
                                                & (0.012)\\
   knowledge\_proximity\_mean                   & 0.126\\
                                                & (0.174)\\
   lnfirst\_before\_year\_prod\_fac             & 0.012$^{**}$\\
                                                & (0.006)\\
   first\_before\_year\_with\_ih\_binTrue       & 0.143$^{***}$\\
                                                & (0.014)\\
   Agricultural.and.Biological.Sciences         & 1.08$^{***}$\\
                                                & (0.048)\\
   Arts.and.Humanities                          & 1.81$^{***}$\\
                                                & (0.089)\\
   Biochemistry..Genetics.and.Molecular.Biology & 0.832$^{***}$\\
                                                & (0.018)\\
   Business..Management.and.Accounting          & -0.365$^{***}$\\
                                                & (0.099)\\
   Chemical.Engineering                         & 0.218$^{***}$\\
                                                & (0.026)\\
   Chemistry                                    & 0.436$^{***}$\\
                                                & (0.015)\\
   Computer.Science                             & 0.832$^{***}$\\
                                                & (0.051)\\
   Decision.Sciences                            & 1.48$^{***}$\\
                                                & (0.230)\\
   Dentistry                                    & 2.52$^{***}$\\
                                                & (0.259)\\
   Earth.and.Planetary.Sciences                 & 0.793$^{***}$\\
                                                & (0.018)\\
   Economics..Econometrics.and.Finance          & -0.144\\
                                                & (0.384)\\
   Energy                                       & 0.256$^{***}$\\
                                                & (0.022)\\
   Engineering                                  & 0.345$^{***}$\\
                                                & (0.013)\\
   Immunology.and.Microbiology                  & 0.504$^{***}$\\
                                                & (0.094)\\
   Materials.Science                            & 0.028$^{**}$\\
                                                & (0.013)\\
   Mathematics                                  & 0.375$^{**}$\\
                                                & (0.149)\\
   Medicine                                     & 1.03$^{***}$\\
                                                & (0.029)\\
   Neuroscience                                 & 0.754$^{***}$\\
                                                & (0.075)\\
   Nursing                                      & 1.52$^{***}$\\
                                                & (0.102)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.689$^{***}$\\
                                                & (0.089)\\
   Physics.and.Astronomy                        & -0.262$^{***}$\\
                                                & (0.014)\\
   Psychology                                   & -0.485\\
                                                & (0.326)\\
   Social.Sciences                              & 0.406$^{*}$\\
                                                & (0.224)\\
   Veterinary                                   & 1.36$^{*}$\\
                                                & (0.726)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 184,750\\
   Squared Correlation                          & 0.07934\\
   Pseudo R$^2$                                 & 0.06444\\
   BIC                                          & 218,414.2\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [24]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ls_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Life.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_ls_bin)

NOTES: 37,482 observations removed because of NA values (LHS: 37,482, RHS: 37,482, Fixed-effects: 37,482).
       1 fixed-effect (1 observation) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 47,167
Fixed-effects: PublishedYear: 48
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
text_fac_scientistStaffPart                   0.085436   0.028782   2.968382
lnnum_author                                  0.111551   0.020009   5.575036
internationalinternational                    0.119384   0.022221   5.372546
lnnum_reference                               0.067572   0.022148   3.050854
num_fac                                      -0.057576   0.015799  -3.644370
SDGTrue                                       0.125092   0.019400   6.448096
lnmean_career_age                             0.147018   0.031085   4.729569
lnfirst_avgimpact                            -0.167985   0.010497 -16.002434
lnfirst_insthindex                           -0.127874   0.013218  -9.674233
first_GlobalSouthGlobalNorth                  0.121468   0.045330   2.679604
first_SameCountrySame                        -0.169001   0.021536  -7.847375
knowledge_proximity_mean                     -1.882885   0.296891  -6.342011
lnfirst_before_year_prod_fac                  0.006520   0.011813   0.551981
first_before_year_with_ih_binTrue             0.272844   0.029434   9.269633
Agricultural.and.Biological.Sciences          0.409114   0.036921  11.080882
Arts.and.Humanities                           0.885820   0.421732   2.100434
Biochemistry..Genetics.and.Molecular.Biology -0.094304   0.038835  -2.428349
Business..Management.and.Accounting          -0.537286   0.670389  -0.801454
Chemical.Engineering                          0.268065   0.172876   1.550619
Chemistry                                     0.574149   0.029313  19.586571
Computer.Science                              0.814426   0.088021   9.252595
Decision.Sciences                            -0.436164   0.623454  -0.699593
Dentistry                                     0.802290   0.277015   2.896194
Earth.and.Planetary.Sciences                  0.906939   0.091581   9.903114
Energy                                        0.242163   0.080217   3.018867
Engineering                                   0.511898   0.038799  13.193448
Environmental.Science                        -0.017195   0.041298  -0.416360
Health.Professions                            0.446922   0.473479   0.943912
Immunology.and.Microbiology                   0.079258   0.039660   1.998444
Materials.Science                             0.176856   0.024957   7.086520
Mathematics                                   1.271649   0.700388   1.815636
Medicine                                      0.526914   0.024215  21.760117
Neuroscience                                  0.273645   0.043846   6.241055
Nursing                                       0.739149   0.072369  10.213627
Pharmacology..Toxicology.and.Pharmaceutics    0.560913   0.067474   8.312997
Physics.and.Astronomy                         0.348039   0.036378   9.567293
Psychology                                    0.451416   0.251570   1.794395
Social.Sciences                               1.172454   0.568601   2.061996
Veterinary                                    0.315304   0.357759   0.881331
                                               Pr(>|z|)
text_fac_scientistStaffPart                  2.9937e-03 **
lnnum_author                                 2.4748e-08 ***
internationalinternational                   7.7633e-08 ***
lnnum_reference                              2.2819e-03 **
num_fac                                      2.6805e-04 ***
SDGTrue                                      1.1326e-10 ***
lnmean_career_age                            2.2500e-06 ***
lnfirst_avgimpact                             < 2.2e-16 ***
lnfirst_insthindex                            < 2.2e-16 ***
first_GlobalSouthGlobalNorth                 7.3709e-03 **
first_SameCountrySame                        4.2484e-15 ***
knowledge_proximity_mean                     2.2679e-10 ***
lnfirst_before_year_prod_fac                 5.8096e-01
first_before_year_with_ih_binTrue             < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                          3.5691e-02 *
Biochemistry..Genetics.and.Molecular.Biology 1.5168e-02 *
Business..Management.and.Accounting          4.2287e-01
Chemical.Engineering                         1.2099e-01
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            4.8418e-01
Dentistry                                    3.7772e-03 **
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Energy                                       2.5372e-03 **
Engineering                                   < 2.2e-16 ***
Environmental.Science                        6.7715e-01
Health.Professions                           3.4521e-01
Immunology.and.Microbiology                  4.5669e-02 *
Materials.Science                            1.3753e-12 ***
Mathematics                                  6.9426e-02 .
Medicine                                      < 2.2e-16 ***
Neuroscience                                 4.3463e-10 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   7.2750e-02 .
Social.Sciences                              3.9208e-02 *
Veterinary                                   3.7814e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -31,080.2   Adj. Pseudo R2: 0.042969
           BIC:  63,096.7     Squared Cor.: 0.061125

In [25]:
margins_eff_ls_bin <- avg_comparisons(model_ls_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_ls_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.043579 0.0161634
  statistic p.value s.value conf.low conf.high predicted_lo predicted_hi
1 64.56435  0       Inf     1.0119   1.075259  0.2777123    0.2951708
  predicted
1 0.2777123

In [26]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_ls_comp_ratio.csv")
# write.csv(margins_eff_ls_bin, fname, row.names = FALSE)

In [27]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ls_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                & 0.085$^{***}$\\
                                                & (0.029)\\
   lnnum\_author                                & 0.112$^{***}$\\
                                                & (0.020)\\
   internationalinternational                   & 0.119$^{***}$\\
                                                & (0.022)\\
   lnnum\_reference                             & 0.068$^{***}$\\
                                                & (0.022)\\
   num\_fac                                     & -0.058$^{***}$\\
                                                & (0.016)\\
   SDGTrue                                      & 0.125$^{***}$\\
                                                & (0.019)\\
   lnmean\_career\_age                          & 0.147$^{***}$\\
                                                & (0.031)\\
   lnfirst\_avgimpact                           & -0.168$^{***}$\\
                                                & (0.011)\\
   lnfirst\_insthindex                          & -0.128$^{***}$\\
                                                & (0.013)\\
   first\_GlobalSouthGlobalNorth                & 0.121$^{***}$\\
                                                & (0.045)\\
   first\_SameCountrySame                       & -0.169$^{***}$\\
                                                & (0.021)\\
   knowledge\_proximity\_mean                   & -1.88$^{***}$\\
                                                & (0.297)\\
   lnfirst\_before\_year\_prod\_fac             & 0.007\\
                                                & (0.012)\\
   first\_before\_year\_with\_ih\_binTrue       & 0.273$^{***}$\\
                                                & (0.029)\\
   Agricultural.and.Biological.Sciences         & 0.409$^{***}$\\
                                                & (0.037)\\
   Arts.and.Humanities                          & 0.886$^{**}$\\
                                                & (0.422)\\
   Biochemistry..Genetics.and.Molecular.Biology & -0.094$^{**}$\\
                                                & (0.039)\\
   Business..Management.and.Accounting          & -0.537\\
                                                & (0.670)\\
   Chemical.Engineering                         & 0.268\\
                                                & (0.173)\\
   Chemistry                                    & 0.574$^{***}$\\
                                                & (0.029)\\
   Computer.Science                             & 0.814$^{***}$\\
                                                & (0.088)\\
   Decision.Sciences                            & -0.436\\
                                                & (0.623)\\
   Dentistry                                    & 0.802$^{***}$\\
                                                & (0.277)\\
   Earth.and.Planetary.Sciences                 & 0.907$^{***}$\\
                                                & (0.092)\\
   Energy                                       & 0.242$^{***}$\\
                                                & (0.080)\\
   Engineering                                  & 0.512$^{***}$\\
                                                & (0.039)\\
   Immunology.and.Microbiology                  & 0.079$^{**}$\\
                                                & (0.040)\\
   Materials.Science                            & 0.177$^{***}$\\
                                                & (0.025)\\
   Mathematics                                  & 1.27$^{*}$\\
                                                & (0.700)\\
   Medicine                                     & 0.527$^{***}$\\
                                                & (0.024)\\
   Neuroscience                                 & 0.274$^{***}$\\
                                                & (0.044)\\
   Nursing                                      & 0.739$^{***}$\\
                                                & (0.072)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.561$^{***}$\\
                                                & (0.068)\\
   Physics.and.Astronomy                        & 0.348$^{***}$\\
                                                & (0.036)\\
   Psychology                                   & 0.451$^{*}$\\
                                                & (0.252)\\
   Social.Sciences                              & 1.17$^{**}$\\
                                                & (0.569)\\
   Veterinary                                   & 0.315\\
                                                & (0.358)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 47,167\\
   Squared Correlation                          & 0.06112\\
   Pseudo R$^2$                                 & 0.04561\\
   BIC                                          & 63,096.7\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [28]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_hs_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Health.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_hs_bin)

NOTES: 18,407 observations removed because of NA values (LHS: 18,407, RHS: 18,407, Fixed-effects: 18,407).
       8 fixed-effects (16 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 19,042
Fixed-effects: PublishedYear: 37
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error     z value
text_fac_scientistStaffPart                    0.338705   0.050230    6.743084
lnnum_author                                   0.173438   0.032414    5.350708
internationalinternational                     0.089551   0.034635    2.585574
lnnum_reference                                0.088420   0.035227    2.509995
num_fac                                       -0.081707   0.027644   -2.955670
SDGTrue                                        0.224144   0.031064    7.215513
lnmean_career_age                              0.140854   0.050786    2.773468
lnfirst_avgimpact                             -0.132140   0.016669   -7.927382
lnfirst_insthindex                            -0.093065   0.020409   -4.560064
first_GlobalSouthGlobalNorth                   0.195973   0.070932    2.762846
first_SameCountrySame                         -0.162796   0.034108   -4.772958
knowledge_proximity_mean                      -1.017772   0.430360   -2.364935
lnfirst_before_year_prod_fac                  -0.069462   0.018897   -3.675722
first_before_year_with_ih_binTrue              0.304144   0.049908    6.094053
Agricultural.and.Biological.Sciences          -0.111495   0.072855   -1.530363
Arts.and.Humanities                            1.012137   0.586553    1.725567
Biochemistry..Genetics.and.Molecular.Biology  -0.219920   0.037852   -5.809947
Business..Management.and.Accounting          -11.489415   0.075962 -151.252151
Chemical.Engineering                          -0.256649   0.376387   -0.681875
Chemistry                                      0.094110   0.049244    1.911070
Computer.Science                               0.597216   0.120282    4.965143
Decision.Sciences                              0.650708   1.182293    0.550378
Dentistry                                      1.047274   0.191791    5.460500
Earth.and.Planetary.Sciences                   0.731307   0.247799    2.951214
Energy                                         0.089555   0.141603    0.632435
Engineering                                    0.598750   0.069082    8.667293
Environmental.Science                          0.121243   0.080258    1.510669
Health.Professions                             0.805184   0.182832    4.403948
Immunology.and.Microbiology                   -0.331587   0.052594   -6.304700
Materials.Science                             -0.373675   0.051471   -7.259847
Mathematics                                    0.425194   0.639258    0.665137
Medicine                                       0.244500   0.114430    2.136678
Neuroscience                                   0.230983   0.082131    2.812378
Nursing                                        0.835925   0.099340    8.414752
Pharmacology..Toxicology.and.Pharmaceutics     0.679650   0.116034    5.857320
Physics.and.Astronomy                          0.012862   0.068927    0.186605
Psychology                                     0.625281   0.441328    1.416818
Social.Sciences                                0.897080   0.694572    1.291558
Veterinary                                     0.376574   0.296455    1.270258
                                               Pr(>|z|)
text_fac_scientistStaffPart                  1.5506e-11 ***
lnnum_author                                 8.7611e-08 ***
internationalinternational                   9.7217e-03 **
lnnum_reference                              1.2073e-02 *
num_fac                                      3.1199e-03 **
SDGTrue                                      5.3731e-13 ***
lnmean_career_age                            5.5462e-03 **
lnfirst_avgimpact                            2.2381e-15 ***
lnfirst_insthindex                           5.1138e-06 ***
first_GlobalSouthGlobalNorth                 5.7300e-03 **
first_SameCountrySame                        1.8154e-06 ***
knowledge_proximity_mean                     1.8033e-02 *
lnfirst_before_year_prod_fac                 2.3718e-04 ***
first_before_year_with_ih_binTrue            1.1009e-09 ***
Agricultural.and.Biological.Sciences         1.2593e-01
Arts.and.Humanities                          8.4425e-02 .
Biochemistry..Genetics.and.Molecular.Biology 6.2493e-09 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Chemical.Engineering                         4.9532e-01
Chemistry                                    5.5996e-02 .
Computer.Science                             6.8651e-07 ***
Decision.Sciences                            5.8206e-01
Dentistry                                    4.7480e-08 ***
Earth.and.Planetary.Sciences                 3.1653e-03 **
Energy                                       5.2710e-01
Engineering                                   < 2.2e-16 ***
Environmental.Science                        1.3087e-01
Health.Professions                           1.0630e-05 ***
Immunology.and.Microbiology                  2.8875e-10 ***
Materials.Science                            3.8753e-13 ***
Mathematics                                  5.0596e-01
Medicine                                     3.2624e-02 *
Neuroscience                                 4.9177e-03 **
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   4.7040e-09 ***
Physics.and.Astronomy                        8.5197e-01
Psychology                                   1.5654e-01
Social.Sciences                              1.9651e-01
Veterinary                                   2.0399e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -12,421.7   Adj. Pseudo R2: 0.045825
           BIC:  25,592.3     Squared Cor.: 0.067991

In [29]:
margins_eff_hs_bin <- avg_comparisons(model_hs_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_hs_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.143906 0.04368053
  statistic p.value       s.value  conf.low conf.high predicted_lo predicted_hi
1 26.18802  3.639009e-151 499.7476 1.058294 1.229519  0.7128357    0.7769364
  predicted
1 0.7769364

In [30]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_hs_comp_ratio.csv")
# write.csv(margins_eff_hs_bin, fname, row.names = FALSE)

In [31]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_hs_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                & 0.339$^{***}$\\
                                                & (0.050)\\
   lnnum\_author                                & 0.173$^{***}$\\
                                                & (0.032)\\
   internationalinternational                   & 0.090$^{***}$\\
                                                & (0.035)\\
   lnnum\_reference                             & 0.088$^{**}$\\
                                                & (0.035)\\
   num\_fac                                     & -0.082$^{***}$\\
                                                & (0.028)\\
   SDGTrue                                      & 0.224$^{***}$\\
                                                & (0.031)\\
   lnmean\_career\_age                          & 0.141$^{***}$\\
                                                & (0.051)\\
   lnfirst\_avgimpact                           & -0.132$^{***}$\\
                                                & (0.017)\\
   lnfirst\_insthindex                          & -0.093$^{***}$\\
                                                & (0.020)\\
   first\_GlobalSouthGlobalNorth                & 0.196$^{***}$\\
                                                & (0.071)\\
   first\_SameCountrySame                       & -0.163$^{***}$\\
                                                & (0.034)\\
   knowledge\_proximity\_mean                   & -1.02$^{**}$\\
                                                & (0.430)\\
   lnfirst\_before\_year\_prod\_fac             & -0.070$^{***}$\\
                                                & (0.019)\\
   first\_before\_year\_with\_ih\_binTrue       & 0.304$^{***}$\\
                                                & (0.050)\\
   Agricultural.and.Biological.Sciences         & -0.111\\
                                                & (0.073)\\
   Arts.and.Humanities                          & 1.01$^{*}$\\
                                                & (0.587)\\
   Biochemistry..Genetics.and.Molecular.Biology & -0.220$^{***}$\\
                                                & (0.038)\\
   Business..Management.and.Accounting          & -11.5$^{***}$\\
                                                & (0.076)\\
   Chemical.Engineering                         & -0.257\\
                                                & (0.376)\\
   Chemistry                                    & 0.094$^{*}$\\
                                                & (0.049)\\
   Computer.Science                             & 0.597$^{***}$\\
                                                & (0.120)\\
   Decision.Sciences                            & 0.651\\
                                                & (1.18)\\
   Dentistry                                    & 1.05$^{***}$\\
                                                & (0.192)\\
   Earth.and.Planetary.Sciences                 & 0.731$^{***}$\\
                                                & (0.248)\\
   Energy                                       & 0.090\\
                                                & (0.142)\\
   Engineering                                  & 0.599$^{***}$\\
                                                & (0.069)\\
   Immunology.and.Microbiology                  & -0.332$^{***}$\\
                                                & (0.053)\\
   Materials.Science                            & -0.374$^{***}$\\
                                                & (0.051)\\
   Mathematics                                  & 0.425\\
                                                & (0.639)\\
   Medicine                                     & 0.244$^{**}$\\
                                                & (0.114)\\
   Neuroscience                                 & 0.231$^{***}$\\
                                                & (0.082)\\
   Nursing                                      & 0.836$^{***}$\\
                                                & (0.099)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.680$^{***}$\\
                                                & (0.116)\\
   Physics.and.Astronomy                        & 0.013\\
                                                & (0.069)\\
   Psychology                                   & 0.625\\
                                                & (0.441)\\
   Social.Sciences                              & 0.897\\
                                                & (0.695)\\
   Veterinary                                   & 0.377\\
                                                & (0.296)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 19,042\\
   Squared Correlation                          & 0.06799\\
   Pseudo R$^2$                                 & 0.05155\\
   BIC                                          & 25,592.3\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [32]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ text_fac_scientist + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_nps_bin <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==0), ], family = binomial("logit"), vcov = "hetero")
summary(model_nps_bin)

NOTES: 20,108 observations removed because of NA values (LHS: 20,108, RHS: 20,108, Fixed-effects: 20,108).
       8 fixed-effects (14 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 24,526
Fixed-effects: PublishedYear: 36
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error     z value
text_fac_scientistStaffPart                    0.333565   0.047892    6.964895
lnnum_author                                   0.199742   0.028592    6.985880
internationalinternational                     0.132876   0.031168    4.263199
lnnum_reference                               -0.166086   0.034468   -4.818587
num_fac                                       -0.115882   0.024077   -4.813038
SDGTrue                                        0.270627   0.027688    9.774002
lnmean_career_age                              0.199133   0.045206    4.405032
lnfirst_avgimpact                             -0.238691   0.014556  -16.397646
lnfirst_insthindex                            -0.190896   0.018700  -10.208518
first_GlobalSouthGlobalNorth                   0.145371   0.065450    2.221090
first_SameCountrySame                         -0.153090   0.030534   -5.013718
knowledge_proximity_mean                      -3.294387   0.444030   -7.419287
lnfirst_before_year_prod_fac                   0.013659   0.017825    0.766303
first_before_year_with_ih_binTrue              0.332631   0.046080    7.218481
Agricultural.and.Biological.Sciences           0.105332   0.046722    2.254449
Arts.and.Humanities                            0.909143   0.369720    2.459002
Biochemistry..Genetics.and.Molecular.Biology  -0.308365   0.040418   -7.629302
Business..Management.and.Accounting          -11.263040   0.071109 -158.390815
Decision.Sciences                             -0.366931   0.984641   -0.372655
Dentistry                                      1.152695   0.238687    4.829311
Health.Professions                             0.563964   0.342122    1.648431
Immunology.and.Microbiology                   -0.041193   0.043265   -0.952119
Medicine                                       0.573257   0.029637   19.342715
Neuroscience                                   0.335592   0.052740    6.363108
Nursing                                        0.838266   0.082528   10.157361
Pharmacology..Toxicology.and.Pharmaceutics     0.892595   0.096541    9.245743
Psychology                                     0.400688   0.241712    1.657707
Social.Sciences                               -0.122026   0.370387   -0.329454
Veterinary                                     0.319192   0.356967    0.894176
                                               Pr(>|z|)
text_fac_scientistStaffPart                  3.2865e-12 ***
lnnum_author                                 2.8308e-12 ***
internationalinternational                   2.0152e-05 ***
lnnum_reference                              1.4458e-06 ***
num_fac                                      1.4865e-06 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            1.0577e-05 ***
lnfirst_avgimpact                             < 2.2e-16 ***
lnfirst_insthindex                            < 2.2e-16 ***
first_GlobalSouthGlobalNorth                 2.6345e-02 *
first_SameCountrySame                        5.3388e-07 ***
knowledge_proximity_mean                     1.1775e-13 ***
lnfirst_before_year_prod_fac                 4.4350e-01
first_before_year_with_ih_binTrue            5.2571e-13 ***
Agricultural.and.Biological.Sciences         2.4168e-02 *
Arts.and.Humanities                          1.3932e-02 *
Biochemistry..Genetics.and.Molecular.Biology 2.3603e-14 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Decision.Sciences                            7.0941e-01
Dentistry                                    1.3701e-06 ***
Health.Professions                           9.9264e-02 .
Immunology.and.Microbiology                  3.4104e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                 1.9771e-10 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Psychology                                   9.7377e-02 .
Social.Sciences                              7.4181e-01
Veterinary                                   3.7123e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -15,605.0   Adj. Pseudo R2: 0.06373
           BIC:  31,867.0     Squared Cor.: 0.088871

In [33]:
margins_eff_nps_bin <- avg_comparisons(model_nps_bin, variables = "text_fac_scientist", comparison = 'ratio')
margins_eff_nps_bin

  term               contrast                             estimate std.error
1 text_fac_scientist mean(StaffPart) / mean(NonStaffPart) 1.181102 0.04572548
  statistic p.value       s.value  conf.low conf.high predicted_lo predicted_hi
1 25.83027  4.053707e-147 486.3042 1.091481 1.270722  0.6187152    0.69374
  predicted
1 0.6187152

In [34]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h1_nps_comp_ratio.csv")
# write.csv(margins_eff_nps_bin, fname, row.names = FALSE)

In [35]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_nps_bin,
                           keep = c("text_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   text\_fac\_scientistStaffPart                & 0.334$^{***}$\\
                                                & (0.048)\\
   lnnum\_author                                & 0.200$^{***}$\\
                                                & (0.029)\\
   internationalinternational                   & 0.133$^{***}$\\
                                                & (0.031)\\
   lnnum\_reference                             & -0.166$^{***}$\\
                                                & (0.035)\\
   num\_fac                                     & -0.116$^{***}$\\
                                                & (0.024)\\
   SDGTrue                                      & 0.271$^{***}$\\
                                                & (0.028)\\
   lnmean\_career\_age                          & 0.199$^{***}$\\
                                                & (0.045)\\
   lnfirst\_avgimpact                           & -0.239$^{***}$\\
                                                & (0.015)\\
   lnfirst\_insthindex                          & -0.191$^{***}$\\
                                                & (0.019)\\
   first\_GlobalSouthGlobalNorth                & 0.145$^{**}$\\
                                                & (0.066)\\
   first\_SameCountrySame                       & -0.153$^{***}$\\
                                                & (0.030)\\
   knowledge\_proximity\_mean                   & -3.29$^{***}$\\
                                                & (0.444)\\
   lnfirst\_before\_year\_prod\_fac             & 0.014\\
                                                & (0.018)\\
   first\_before\_year\_with\_ih\_binTrue       & 0.333$^{***}$\\
                                                & (0.046)\\
   Agricultural.and.Biological.Sciences         & 0.105$^{**}$\\
                                                & (0.047)\\
   Arts.and.Humanities                          & 0.909$^{**}$\\
                                                & (0.370)\\
   Biochemistry..Genetics.and.Molecular.Biology & -0.308$^{***}$\\
                                                & (0.040)\\
   Business..Management.and.Accounting          & -11.3$^{***}$\\
                                                & (0.071)\\
   Decision.Sciences                            & -0.367\\
                                                & (0.985)\\
   Dentistry                                    & 1.15$^{***}$\\
                                                & (0.239)\\
   Immunology.and.Microbiology                  & -0.041\\
                                                & (0.043)\\
   Medicine                                     & 0.573$^{***}$\\
                                                & (0.030)\\
   Neuroscience                                 & 0.336$^{***}$\\
                                                & (0.053)\\
   Nursing                                      & 0.838$^{***}$\\
                                                & (0.083)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.893$^{***}$\\
                                                & (0.097)\\
   Psychology                                   & 0.401$^{*}$\\
                                                & (0.242)\\
   Social.Sciences                              & -0.122\\
                                                & (0.370)\\
   Veterinary                                   & 0.319\\
                                                & (0.357)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 24,526\\
   Squared Correlation                          & 0.08887\\
   Pseudo R$^2$                                 & 0.06755\\
   BIC                                          & 31,867.0\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H2: Collaboration > Participation

In [36]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_total <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_total)

NOTE: 107,910 observations removed because of NA values (LHS: 107,910, RHS: 107,910, Fixed-effects: 107,910).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 209,290
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.084582   0.013500   6.265139
CoTypeParticipation                          -0.013599   0.018721  -0.726386
lnnum_author                                 -0.139751   0.008417 -16.603769
internationalinternational                   -0.038775   0.011454  -3.385383
lnnum_reference                               0.000455   0.010154   0.044774
num_fac                                       0.080489   0.007865  10.233479
SDGTrue                                       0.054362   0.009891   5.495997
lnmean_career_age                             0.021174   0.015987   1.324482
lnfirst_avgimpact                            -0.113242   0.005716 -19.812309
lnfirst_insthindex                           -0.063511   0.006700  -9.478811
first_GlobalSouthGlobalNorth                  0.312653   0.019723  15.851938
first_SameCountrySame                        -0.109761   0.011313  -9.702182
knowledge_proximity_mean                     -0.271497   0.159420  -1.703031
lnfirst_before_year_prod_fac                  0.008470   0.005509   1.537691
first_before_year_with_ih_binTrue             0.165813   0.013402  12.372102
Agricultural.and.Biological.Sciences          0.807939   0.031283  25.827160
Arts.and.Humanities                           1.798156   0.086168  20.868029
Biochemistry..Genetics.and.Molecular.Biology  0.637994   0.015439  41.322926
Business..Management.and.Accounting          -0.390836   0.099043  -3.946111
Chemical.Engineering                          0.210956   0.025595   8.242200
Chemistry                                     0.485009   0.013594  35.679095
Computer.Science                              0.904936   0.049134  18.417597
Decision.Sciences                             1.356996   0.221459   6.127520
Dentistry                                     2.081624   0.176501  11.793860
Earth.and.Planetary.Sciences                  0.782261   0.018147  43.106563
Economics..Econometrics.and.Finance          -0.137600   0.383692  -0.358621
Energy                                        0.260148   0.021751  11.960303
Engineering                                   0.337840   0.012580  26.855450
Environmental.Science                         0.494877   0.022260  22.231382
Health.Professions                            1.599894   0.155194  10.309014
Immunology.and.Microbiology                   0.218481   0.036308   6.017502
Materials.Science                             0.063312   0.011856   5.340085
Mathematics                                   0.402030   0.147924   2.717805
Medicine                                      0.890850   0.019124  46.582750
Neuroscience                                  0.516232   0.042256  12.216884
Nursing                                       1.177632   0.063040  18.680773
Pharmacology..Toxicology.and.Pharmaceutics    0.834464   0.064629  12.911688
Physics.and.Astronomy                        -0.258429   0.013590 -19.016568
Psychology                                    0.287349   0.183793   1.563438
Social.Sciences                               0.336731   0.187061   1.800116
Veterinary                                    0.644638   0.302981   2.127654
                                               Pr(>|z|)
CoTypeCollaboration                          3.7249e-10 ***
CoTypeParticipation                          4.6760e-01
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   7.1079e-04 ***
lnnum_reference                              9.6429e-01
num_fac                                       < 2.2e-16 ***
SDGTrue                                      3.8851e-08 ***
lnmean_career_age                            1.8534e-01
lnfirst_avgimpact                             < 2.2e-16 ***
lnfirst_insthindex                            < 2.2e-16 ***
first_GlobalSouthGlobalNorth                  < 2.2e-16 ***
first_SameCountrySame                         < 2.2e-16 ***
knowledge_proximity_mean                     8.8562e-02 .
lnfirst_before_year_prod_fac                 1.2412e-01
first_before_year_with_ih_binTrue             < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          7.9431e-05 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            8.9259e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.1988e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  1.7713e-09 ***
Materials.Science                            9.2903e-08 ***
Mathematics                                  6.5717e-03 **
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.1795e-01
Social.Sciences                              7.1842e-02 .
Veterinary                                   3.3366e-02 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -125,425.8   Adj. Pseudo R2: 0.059071
           BIC:  251,978.7     Squared Cor.: 0.073988

In [37]:
# 每组 reg_class 的平均预测概率
pred <- avg_predictions(model_total, variables = "CoType")
pred

  CoType        estimate  std.error  statistic p.value      s.value  conf.low
1 Service       0.3311722 0.03086527 10.72961  7.390980e-27 86.80629 0.2706774
2 Collaboration 0.3486968 0.03170624 10.99774  3.918438e-28 91.04371 0.2865537
3 Participation 0.3283952 0.03085786 10.64219  1.896200e-26 85.44702 0.2679149
  conf.high
1 0.3916670
2 0.4108399
3 0.3888755

In [38]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_pred.csv")
# write.csv(pred, fname, row.names = FALSE)

In [39]:
# 每组 reg_class 的平均预测概率
margins_eff <- avg_comparisons(model_total, variables = "CoType", comparison = 'ratio')
margins_eff

  term   contrast                            estimate  std.error   statistic
1 CoType mean(Collaboration) / mean(Service) 1.0529170 0.008981724 117.22883
2 CoType mean(Participation) / mean(Service) 0.9916148 0.011515338  86.11252
  p.value s.value conf.low  conf.high predicted_lo predicted_hi predicted
1 0       Inf     1.0353132 1.070521  0.2444137    0.2603693    0.2444137
2 0       Inf     0.9690452 1.014184  0.2444137    0.2419111    0.2444137

In [40]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_comp_ratio.csv")
# write.csv(margins_eff, fname, row.names = FALSE)

In [41]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_total,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                          & 0.085$^{***}$\\
                                                & (0.013)\\
   CoTypeParticipation                          & -0.014\\
                                                & (0.019)\\
   lnnum\_author                                & -0.140$^{***}$\\
                                                & (0.008)\\
   internationalinternational                   & -0.039$^{***}$\\
                                                & (0.011)\\
   lnnum\_reference                             & 0.0005\\
                                                & (0.010)\\
   num\_fac                                     & 0.081$^{***}$\\
                                                & (0.008)\\
   SDGTrue                                      & 0.054$^{***}$\\
                                                & (0.010)\\
   lnmean\_career\_age                          & 0.021\\
                                                & (0.016)\\
   lnfirst\_avgimpact                           & -0.113$^{***}$\\
                                                & (0.006)\\
   lnfirst\_insthindex                          & -0.064$^{***}$\\
                                                & (0.007)\\
   first\_GlobalSouthGlobalNorth                & 0.313$^{***}$\\
                                                & (0.020)\\
   first\_SameCountrySame                       & -0.110$^{***}$\\
                                                & (0.011)\\
   knowledge\_proximity\_mean                   & -0.271$^{*}$\\
                                                & (0.159)\\
   lnfirst\_before\_year\_prod\_fac             & 0.008\\
                                                & (0.006)\\
   first\_before\_year\_with\_ih\_binTrue       & 0.166$^{***}$\\
                                                & (0.013)\\
   Agricultural.and.Biological.Sciences         & 0.808$^{***}$\\
                                                & (0.031)\\
   Arts.and.Humanities                          & 1.80$^{***}$\\
                                                & (0.086)\\
   Biochemistry..Genetics.and.Molecular.Biology & 0.638$^{***}$\\
                                                & (0.015)\\
   Business..Management.and.Accounting          & -0.391$^{***}$\\
                                                & (0.099)\\
   Chemical.Engineering                         & 0.211$^{***}$\\
                                                & (0.026)\\
   Chemistry                                    & 0.485$^{***}$\\
                                                & (0.014)\\
   Computer.Science                             & 0.905$^{***}$\\
                                                & (0.049)\\
   Decision.Sciences                            & 1.36$^{***}$\\
                                                & (0.221)\\
   Dentistry                                    & 2.08$^{***}$\\
                                                & (0.177)\\
   Earth.and.Planetary.Sciences                 & 0.782$^{***}$\\
                                                & (0.018)\\
   Economics..Econometrics.and.Finance          & -0.138\\
                                                & (0.384)\\
   Energy                                       & 0.260$^{***}$\\
                                                & (0.022)\\
   Engineering                                  & 0.338$^{***}$\\
                                                & (0.013)\\
   Immunology.and.Microbiology                  & 0.218$^{***}$\\
                                                & (0.036)\\
   Materials.Science                            & 0.063$^{***}$\\
                                                & (0.012)\\
   Mathematics                                  & 0.402$^{***}$\\
                                                & (0.148)\\
   Medicine                                     & 0.891$^{***}$\\
                                                & (0.019)\\
   Neuroscience                                 & 0.516$^{***}$\\
                                                & (0.042)\\
   Nursing                                      & 1.18$^{***}$\\
                                                & (0.063)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.834$^{***}$\\
                                                & (0.065)\\
   Physics.and.Astronomy                        & -0.258$^{***}$\\
                                                & (0.014)\\
   Psychology                                   & 0.287\\
                                                & (0.184)\\
   Social.Sciences                              & 0.337$^{*}$\\
                                                & (0.187)\\
   Veterinary                                   & 0.645$^{**}$\\
                                                & (0.303)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 209,290\\
   Squared Correlation                          & 0.07399\\
   Pseudo R$^2$                                 & 0.05975\\
   BIC                                          & 251,978.7\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H2 Discipline

In [42]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ps <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_ps)

NOTE: 87,802 observations removed because of NA values (LHS: 87,802, RHS: 87,802, Fixed-effects: 87,802).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 184,750
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.066368   0.014107   4.704600
CoTypeParticipation                          -0.022799   0.019649  -1.160288
lnnum_author                                 -0.198918   0.009287 -21.419384
internationalinternational                   -0.068990   0.012406  -5.561088
lnnum_reference                               0.029384   0.010714   2.742720
num_fac                                       0.114177   0.008375  13.632559
SDGTrue                                       0.002806   0.010701   0.262172
lnmean_career_age                            -0.022632   0.017185  -1.316993
lnfirst_avgimpact                            -0.091491   0.006307 -14.506581
lnfirst_insthindex                           -0.037754   0.007281  -5.184999
first_GlobalSouthGlobalNorth                  0.312883   0.021066  14.852303
first_SameCountrySame                        -0.107359   0.012290  -8.735562
knowledge_proximity_mean                      0.117976   0.173654   0.679372
lnfirst_before_year_prod_fac                  0.011493   0.005885   1.952930
first_before_year_with_ih_binTrue             0.141713   0.014144  10.018983
Agricultural.and.Biological.Sciences          1.082201   0.047499  22.783485
Arts.and.Humanities                           1.809314   0.089441  20.229167
Biochemistry..Genetics.and.Molecular.Biology  0.829144   0.017516  47.336892
Business..Management.and.Accounting          -0.366784   0.098803  -3.712282
Chemical.Engineering                          0.218778   0.025768   8.490188
Chemistry                                     0.435745   0.014595  29.855874
Computer.Science                              0.830558   0.050497  16.447797
Decision.Sciences                             1.478177   0.230195   6.421404
Dentistry                                     2.523272   0.259009   9.742007
Earth.and.Planetary.Sciences                  0.792762   0.018503  42.844041
Economics..Econometrics.and.Finance          -0.148560   0.384004  -0.386872
Energy                                        0.256126   0.022230  11.521602
Engineering                                   0.343852   0.013348  25.761480
Environmental.Science                         0.402062   0.023903  16.820246
Health.Professions                            1.818597   0.172559  10.538984
Immunology.and.Microbiology                   0.502612   0.093967   5.348829
Materials.Science                             0.029230   0.012870   2.271265
Mathematics                                   0.372615   0.148752   2.504949
Medicine                                      1.032102   0.028954  35.645688
Neuroscience                                  0.753827   0.074883  10.066751
Nursing                                       1.525631   0.102129  14.938289
Pharmacology..Toxicology.and.Pharmaceutics    0.690273   0.088862   7.767892
Physics.and.Astronomy                        -0.263106   0.014362 -18.319663
Psychology                                   -0.481711   0.324215  -1.485776
Social.Sciences                               0.409543   0.223961   1.828632
Veterinary                                    1.366879   0.730560   1.871002
                                               Pr(>|z|)
CoTypeCollaboration                          2.5436e-06 ***
CoTypeParticipation                          2.4593e-01
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   2.6810e-08 ***
lnnum_reference                              6.0933e-03 **
num_fac                                       < 2.2e-16 ***
SDGTrue                                      7.9319e-01
lnmean_career_age                            1.8784e-01
lnfirst_avgimpact                             < 2.2e-16 ***
lnfirst_insthindex                           2.1602e-07 ***
first_GlobalSouthGlobalNorth                  < 2.2e-16 ***
first_SameCountrySame                         < 2.2e-16 ***
knowledge_proximity_mean                     4.9690e-01
lnfirst_before_year_prod_fac                 5.0828e-02 .
first_before_year_with_ih_binTrue             < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          2.0540e-04 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            1.3502e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          6.9885e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  8.8525e-08 ***
Materials.Science                            2.3131e-02 *
Mathematics                                  1.2247e-02 *
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   7.9803e-15 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.3734e-01
Social.Sciences                              6.7455e-02 .
Veterinary                                   6.1345e-02 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -108,646.1   Adj. Pseudo R2: 0.063732
           BIC:  218,408.0     Squared Cor.: 0.079401

In [43]:
# 每组 reg_class 的平均预测概率
margins_eff_ps <- avg_comparisons(model_ps, variables = "CoType", comparison = 'ratio')
margins_eff_ps

  term   contrast                            estimate  std.error   statistic
1 CoType mean(Collaboration) / mean(Service) 1.0419089 0.009272398 112.36672
2 CoType mean(Participation) / mean(Service) 0.9858076 0.012187639  80.88585
  p.value s.value conf.low  conf.high predicted_lo predicted_hi predicted
1 0       Inf     1.0237354 1.060083  0.2451978    0.2576876    0.2451978
2 0       Inf     0.9619202 1.009695  0.2451978    0.2410029    0.2451978

In [44]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_ps_comp_ratio.csv")
# write.csv(margins_eff_ps, fname, row.names = FALSE)

In [45]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ps,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                          & 0.066$^{***}$\\
                                                & (0.014)\\
   CoTypeParticipation                          & -0.023\\
                                                & (0.020)\\
   lnnum\_author                                & -0.199$^{***}$\\
                                                & (0.009)\\
   internationalinternational                   & -0.069$^{***}$\\
                                                & (0.012)\\
   lnnum\_reference                             & 0.029$^{***}$\\
                                                & (0.011)\\
   num\_fac                                     & 0.114$^{***}$\\
                                                & (0.008)\\
   SDGTrue                                      & 0.003\\
                                                & (0.011)\\
   lnmean\_career\_age                          & -0.023\\
                                                & (0.017)\\
   lnfirst\_avgimpact                           & -0.091$^{***}$\\
                                                & (0.006)\\
   lnfirst\_insthindex                          & -0.038$^{***}$\\
                                                & (0.007)\\
   first\_GlobalSouthGlobalNorth                & 0.313$^{***}$\\
                                                & (0.021)\\
   first\_SameCountrySame                       & -0.107$^{***}$\\
                                                & (0.012)\\
   knowledge\_proximity\_mean                   & 0.118\\
                                                & (0.174)\\
   lnfirst\_before\_year\_prod\_fac             & 0.011$^{*}$\\
                                                & (0.006)\\
   first\_before\_year\_with\_ih\_binTrue       & 0.142$^{***}$\\
                                                & (0.014)\\
   Agricultural.and.Biological.Sciences         & 1.08$^{***}$\\
                                                & (0.048)\\
   Arts.and.Humanities                          & 1.81$^{***}$\\
                                                & (0.089)\\
   Biochemistry..Genetics.and.Molecular.Biology & 0.829$^{***}$\\
                                                & (0.018)\\
   Business..Management.and.Accounting          & -0.367$^{***}$\\
                                                & (0.099)\\
   Chemical.Engineering                         & 0.219$^{***}$\\
                                                & (0.026)\\
   Chemistry                                    & 0.436$^{***}$\\
                                                & (0.015)\\
   Computer.Science                             & 0.831$^{***}$\\
                                                & (0.051)\\
   Decision.Sciences                            & 1.48$^{***}$\\
                                                & (0.230)\\
   Dentistry                                    & 2.52$^{***}$\\
                                                & (0.259)\\
   Earth.and.Planetary.Sciences                 & 0.793$^{***}$\\
                                                & (0.018)\\
   Economics..Econometrics.and.Finance          & -0.149\\
                                                & (0.384)\\
   Energy                                       & 0.256$^{***}$\\
                                                & (0.022)\\
   Engineering                                  & 0.344$^{***}$\\
                                                & (0.013)\\
   Immunology.and.Microbiology                  & 0.503$^{***}$\\
                                                & (0.094)\\
   Materials.Science                            & 0.029$^{**}$\\
                                                & (0.013)\\
   Mathematics                                  & 0.373$^{**}$\\
                                                & (0.149)\\
   Medicine                                     & 1.03$^{***}$\\
                                                & (0.029)\\
   Neuroscience                                 & 0.754$^{***}$\\
                                                & (0.075)\\
   Nursing                                      & 1.53$^{***}$\\
                                                & (0.102)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.690$^{***}$\\
                                                & (0.089)\\
   Physics.and.Astronomy                        & -0.263$^{***}$\\
                                                & (0.014)\\
   Psychology                                   & -0.482\\
                                                & (0.324)\\
   Social.Sciences                              & 0.410$^{*}$\\
                                                & (0.224)\\
   Veterinary                                   & 1.37$^{*}$\\
                                                & (0.731)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 184,750\\
   Squared Correlation                          & 0.07940\\
   Pseudo R$^2$                                 & 0.06452\\
   BIC                                          & 218,408.0\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [46]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_ls <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Life.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_ls)

NOTES: 37,482 observations removed because of NA values (LHS: 37,482, RHS: 37,482, Fixed-effects: 37,482).
       1 fixed-effect (1 observation) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 47,167
Fixed-effects: PublishedYear: 48
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.053669   0.031644   1.695999
CoTypeParticipation                           0.178240   0.048273   3.692305
lnnum_author                                  0.110616   0.020008   5.528611
internationalinternational                    0.118752   0.022222   5.343761
lnnum_reference                               0.066832   0.022154   3.016686
num_fac                                      -0.057404   0.015802  -3.632779
SDGTrue                                       0.125317   0.019401   6.459166
lnmean_career_age                             0.149235   0.031092   4.799850
lnfirst_avgimpact                            -0.167849   0.010499 -15.987316
lnfirst_insthindex                           -0.128936   0.013227  -9.747749
first_GlobalSouthGlobalNorth                  0.124429   0.045369   2.742605
first_SameCountrySame                        -0.168362   0.021535  -7.818171
knowledge_proximity_mean                     -1.860858   0.297023  -6.265041
lnfirst_before_year_prod_fac                  0.007114   0.011811   0.602331
first_before_year_with_ih_binTrue             0.275584   0.029465   9.353025
Agricultural.and.Biological.Sciences          0.408349   0.036929  11.057603
Arts.and.Humanities                           0.871724   0.420134   2.074873
Biochemistry..Genetics.and.Molecular.Biology -0.092097   0.038851  -2.370536
Business..Management.and.Accounting          -0.529655   0.668258  -0.792591
Chemical.Engineering                          0.264145   0.173450   1.522892
Chemistry                                     0.574586   0.029321  19.596094
Computer.Science                              0.814269   0.088046   9.248184
Decision.Sciences                            -0.430752   0.622561  -0.691903
Dentistry                                     0.804231   0.276913   2.904270
Earth.and.Planetary.Sciences                  0.902474   0.091613   9.850968
Energy                                        0.242528   0.080265   3.021578
Engineering                                   0.510447   0.038820  13.149118
Environmental.Science                        -0.016474   0.041305  -0.398843
Health.Professions                            0.441791   0.472877   0.934262
Immunology.and.Microbiology                   0.079726   0.039660   2.010225
Materials.Science                             0.177220   0.024956   7.101297
Mathematics                                   1.263719   0.697616   1.811483
Medicine                                      0.526788   0.024216  21.754143
Neuroscience                                  0.273480   0.043849   6.236801
Nursing                                       0.737607   0.072371  10.191960
Pharmacology..Toxicology.and.Pharmaceutics    0.559546   0.067495   8.290195
Physics.and.Astronomy                         0.350543   0.036397   9.631179
Psychology                                    0.447633   0.251925   1.776850
Social.Sciences                               1.161256   0.568207   2.043721
Veterinary                                    0.316983   0.357109   0.887638
                                               Pr(>|z|)
CoTypeCollaboration                          8.9886e-02 .
CoTypeParticipation                          2.2223e-04 ***
lnnum_author                                 3.2278e-08 ***
internationalinternational                   9.1038e-08 ***
lnnum_reference                              2.5555e-03 **
num_fac                                      2.8039e-04 ***
SDGTrue                                      1.0528e-10 ***
lnmean_career_age                            1.5878e-06 ***
lnfirst_avgimpact                             < 2.2e-16 ***
lnfirst_insthindex                            < 2.2e-16 ***
first_GlobalSouthGlobalNorth                 6.0954e-03 **
first_SameCountrySame                        5.3596e-15 ***
knowledge_proximity_mean                     3.7273e-10 ***
lnfirst_before_year_prod_fac                 5.4695e-01
first_before_year_with_ih_binTrue             < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                          3.7998e-02 *
Biochemistry..Genetics.and.Molecular.Biology 1.7762e-02 *
Business..Management.and.Accounting          4.2802e-01
Chemical.Engineering                         1.2779e-01
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            4.8900e-01
Dentistry                                    3.6811e-03 **
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Energy                                       2.5146e-03 **
Engineering                                   < 2.2e-16 ***
Environmental.Science                        6.9001e-01
Health.Professions                           3.5017e-01
Immunology.and.Microbiology                  4.4407e-02 *
Materials.Science                            1.2359e-12 ***
Mathematics                                  7.0066e-02 .
Medicine                                      < 2.2e-16 ***
Neuroscience                                 4.4661e-10 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   7.5593e-02 .
Social.Sciences                              4.0981e-02 *
Veterinary                                   3.7474e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -31,077.2   Adj. Pseudo R2: 0.04303
           BIC:  63,101.5     Squared Cor.: 0.061256

In [47]:
# 每组 reg_class 的平均预测概率
margins_eff_ls <- avg_comparisons(model_ls, variables = "CoType", comparison = 'ratio')
margins_eff_ls

  term   contrast                            estimate std.error  statistic
1 CoType mean(Collaboration) / mean(Service) 1.027348 0.01679171 61.18183
2 CoType mean(Participation) / mean(Service) 1.091068 0.02793909 39.05168
  p.value s.value conf.low  conf.high predicted_lo predicted_hi predicted
1 0       Inf     0.9944366 1.060259  0.2776936    0.2885858    0.2776936
2 0       Inf     1.0363086 1.145828  0.2776936    0.3148177    0.2776936

In [48]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_ls_comp_ratio.csv")
# write.csv(margins_eff_ls, fname, row.names = FALSE)

In [49]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_ls,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                          & 0.054$^{*}$\\
                                                & (0.032)\\
   CoTypeParticipation                          & 0.178$^{***}$\\
                                                & (0.048)\\
   lnnum\_author                                & 0.111$^{***}$\\
                                                & (0.020)\\
   internationalinternational                   & 0.119$^{***}$\\
                                                & (0.022)\\
   lnnum\_reference                             & 0.067$^{***}$\\
                                                & (0.022)\\
   num\_fac                                     & -0.057$^{***}$\\
                                                & (0.016)\\
   SDGTrue                                      & 0.125$^{***}$\\
                                                & (0.019)\\
   lnmean\_career\_age                          & 0.149$^{***}$\\
                                                & (0.031)\\
   lnfirst\_avgimpact                           & -0.168$^{***}$\\
                                                & (0.011)\\
   lnfirst\_insthindex                          & -0.129$^{***}$\\
                                                & (0.013)\\
   first\_GlobalSouthGlobalNorth                & 0.124$^{***}$\\
                                                & (0.045)\\
   first\_SameCountrySame                       & -0.168$^{***}$\\
                                                & (0.021)\\
   knowledge\_proximity\_mean                   & -1.86$^{***}$\\
                                                & (0.297)\\
   lnfirst\_before\_year\_prod\_fac             & 0.007\\
                                                & (0.012)\\
   first\_before\_year\_with\_ih\_binTrue       & 0.276$^{***}$\\
                                                & (0.029)\\
   Agricultural.and.Biological.Sciences         & 0.408$^{***}$\\
                                                & (0.037)\\
   Arts.and.Humanities                          & 0.872$^{**}$\\
                                                & (0.420)\\
   Biochemistry..Genetics.and.Molecular.Biology & -0.092$^{**}$\\
                                                & (0.039)\\
   Business..Management.and.Accounting          & -0.530\\
                                                & (0.668)\\
   Chemical.Engineering                         & 0.264\\
                                                & (0.173)\\
   Chemistry                                    & 0.575$^{***}$\\
                                                & (0.029)\\
   Computer.Science                             & 0.814$^{***}$\\
                                                & (0.088)\\
   Decision.Sciences                            & -0.431\\
                                                & (0.623)\\
   Dentistry                                    & 0.804$^{***}$\\
                                                & (0.277)\\
   Earth.and.Planetary.Sciences                 & 0.902$^{***}$\\
                                                & (0.092)\\
   Energy                                       & 0.243$^{***}$\\
                                                & (0.080)\\
   Engineering                                  & 0.510$^{***}$\\
                                                & (0.039)\\
   Immunology.and.Microbiology                  & 0.080$^{**}$\\
                                                & (0.040)\\
   Materials.Science                            & 0.177$^{***}$\\
                                                & (0.025)\\
   Mathematics                                  & 1.26$^{*}$\\
                                                & (0.698)\\
   Medicine                                     & 0.527$^{***}$\\
                                                & (0.024)\\
   Neuroscience                                 & 0.273$^{***}$\\
                                                & (0.044)\\
   Nursing                                      & 0.738$^{***}$\\
                                                & (0.072)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.560$^{***}$\\
                                                & (0.068)\\
   Physics.and.Astronomy                        & 0.351$^{***}$\\
                                                & (0.036)\\
   Psychology                                   & 0.448$^{*}$\\
                                                & (0.252)\\
   Social.Sciences                              & 1.16$^{**}$\\
                                                & (0.568)\\
   Veterinary                                   & 0.317\\
                                                & (0.357)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 47,167\\
   Squared Correlation                          & 0.06126\\
   Pseudo R$^2$                                 & 0.04570\\
   BIC                                          & 63,101.5\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [50]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_hs <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Health.Sciences==1), ], family = binomial("logit"), vcov = "hetero")
summary(model_hs)

NOTES: 18,407 observations removed because of NA values (LHS: 18,407, RHS: 18,407, Fixed-effects: 18,407).
       8 fixed-effects (16 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 19,042
Fixed-effects: PublishedYear: 37
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error     z value
CoTypeCollaboration                            0.305629   0.056364    5.422447
CoTypeParticipation                            0.421204   0.082600    5.099349
lnnum_author                                   0.171432   0.032416    5.288491
internationalinternational                     0.088627   0.034638    2.558642
lnnum_reference                                0.088111   0.035254    2.499281
num_fac                                       -0.081910   0.027661   -2.961218
SDGTrue                                        0.224677   0.031069    7.231632
lnmean_career_age                              0.142694   0.050795    2.809187
lnfirst_avgimpact                             -0.132042   0.016672   -7.919727
lnfirst_insthindex                            -0.093913   0.020412   -4.600781
first_GlobalSouthGlobalNorth                   0.197282   0.070952    2.780496
first_SameCountrySame                         -0.163163   0.034108   -4.783691
knowledge_proximity_mean                      -1.009843   0.430464   -2.345943
lnfirst_before_year_prod_fac                  -0.068907   0.018890   -3.647702
first_before_year_with_ih_binTrue              0.306395   0.049962    6.132536
Agricultural.and.Biological.Sciences          -0.111673   0.072872   -1.532450
Arts.and.Humanities                            1.004918   0.587161    1.711488
Biochemistry..Genetics.and.Molecular.Biology  -0.220072   0.037853   -5.813863
Business..Management.and.Accounting          -11.471459   0.077389 -148.231071
Chemical.Engineering                          -0.251214   0.375811   -0.668458
Chemistry                                      0.094845   0.049253    1.925653
Computer.Science                               0.598102   0.120320    4.970945
Decision.Sciences                              0.658708   1.184390    0.556158
Dentistry                                      1.045894   0.191720    5.455313
Earth.and.Planetary.Sciences                   0.731175   0.248049    2.947703
Energy                                         0.089726   0.141681    0.633294
Engineering                                    0.596426   0.069096    8.631875
Environmental.Science                          0.121241   0.080269    1.510432
Health.Professions                             0.801595   0.182899    4.382725
Immunology.and.Microbiology                   -0.332024   0.052594   -6.312904
Materials.Science                             -0.374457   0.051464   -7.276091
Mathematics                                    0.435512   0.637559    0.683093
Medicine                                       0.243986   0.114405    2.132648
Neuroscience                                   0.230157   0.082150    2.801650
Nursing                                        0.833806   0.099342    8.393310
Pharmacology..Toxicology.and.Pharmaceutics     0.677573   0.116047    5.838772
Physics.and.Astronomy                          0.014124   0.068942    0.204870
Psychology                                     0.621864   0.441103    1.409793
Social.Sciences                                0.889318   0.695160    1.279301
Veterinary                                     0.376648   0.296002    1.272450
                                               Pr(>|z|)
CoTypeCollaboration                          5.8789e-08 ***
CoTypeParticipation                          3.4082e-07 ***
lnnum_author                                 1.2333e-07 ***
internationalinternational                   1.0508e-02 *
lnnum_reference                              1.2445e-02 *
num_fac                                      3.0642e-03 **
SDGTrue                                      4.7723e-13 ***
lnmean_career_age                            4.9667e-03 **
lnfirst_avgimpact                            2.3803e-15 ***
lnfirst_insthindex                           4.2091e-06 ***
first_GlobalSouthGlobalNorth                 5.4276e-03 **
first_SameCountrySame                        1.7210e-06 ***
knowledge_proximity_mean                     1.8979e-02 *
lnfirst_before_year_prod_fac                 2.6460e-04 ***
first_before_year_with_ih_binTrue            8.6489e-10 ***
Agricultural.and.Biological.Sciences         1.2541e-01
Arts.and.Humanities                          8.6991e-02 .
Biochemistry..Genetics.and.Molecular.Biology 6.1048e-09 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Chemical.Engineering                         5.0384e-01
Chemistry                                    5.4148e-02 .
Computer.Science                             6.6627e-07 ***
Decision.Sciences                            5.7810e-01
Dentistry                                    4.8887e-08 ***
Earth.and.Planetary.Sciences                 3.2014e-03 **
Energy                                       5.2654e-01
Engineering                                   < 2.2e-16 ***
Environmental.Science                        1.3093e-01
Health.Professions                           1.1720e-05 ***
Immunology.and.Microbiology                  2.7385e-10 ***
Materials.Science                            3.4363e-13 ***
Mathematics                                  4.9455e-01
Medicine                                     3.2954e-02 *
Neuroscience                                 5.0842e-03 **
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   5.2587e-09 ***
Physics.and.Astronomy                        8.3767e-01
Psychology                                   1.5860e-01
Social.Sciences                              2.0079e-01
Veterinary                                   2.0321e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -12,420.8   Adj. Pseudo R2: 0.045811
           BIC:  25,600.5     Squared Cor.: 0.068085

In [51]:
# 每组 reg_class 的平均预测概率
margins_eff_hs <- avg_comparisons(model_hs, variables = "CoType", comparison = 'ratio')
margins_eff_hs

  term   contrast                            estimate std.error  statistic
1 CoType mean(Collaboration) / mean(Service) 1.130172 0.04170746 27.09759
2 CoType mean(Participation) / mean(Service) 1.177706 0.05895015 19.97799
  p.value       s.value  conf.low conf.high predicted_lo predicted_hi predicted
1 1.051269e-161 534.7583 1.048426 1.211917  0.7143028    0.7724160    0.772416
2  8.559759e-89 292.5540 1.062166 1.293246  0.7143028    0.7920914    0.772416

In [52]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_hs_comp_ratio.csv")
# write.csv(margins_eff_hs, fname, row.names = FALSE)

In [53]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_hs,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                          & 0.306$^{***}$\\
                                                & (0.056)\\
   CoTypeParticipation                          & 0.421$^{***}$\\
                                                & (0.083)\\
   lnnum\_author                                & 0.171$^{***}$\\
                                                & (0.032)\\
   internationalinternational                   & 0.089$^{**}$\\
                                                & (0.035)\\
   lnnum\_reference                             & 0.088$^{**}$\\
                                                & (0.035)\\
   num\_fac                                     & -0.082$^{***}$\\
                                                & (0.028)\\
   SDGTrue                                      & 0.225$^{***}$\\
                                                & (0.031)\\
   lnmean\_career\_age                          & 0.143$^{***}$\\
                                                & (0.051)\\
   lnfirst\_avgimpact                           & -0.132$^{***}$\\
                                                & (0.017)\\
   lnfirst\_insthindex                          & -0.094$^{***}$\\
                                                & (0.020)\\
   first\_GlobalSouthGlobalNorth                & 0.197$^{***}$\\
                                                & (0.071)\\
   first\_SameCountrySame                       & -0.163$^{***}$\\
                                                & (0.034)\\
   knowledge\_proximity\_mean                   & -1.01$^{**}$\\
                                                & (0.430)\\
   lnfirst\_before\_year\_prod\_fac             & -0.069$^{***}$\\
                                                & (0.019)\\
   first\_before\_year\_with\_ih\_binTrue       & 0.306$^{***}$\\
                                                & (0.050)\\
   Agricultural.and.Biological.Sciences         & -0.112\\
                                                & (0.073)\\
   Arts.and.Humanities                          & 1.00$^{*}$\\
                                                & (0.587)\\
   Biochemistry..Genetics.and.Molecular.Biology & -0.220$^{***}$\\
                                                & (0.038)\\
   Business..Management.and.Accounting          & -11.5$^{***}$\\
                                                & (0.077)\\
   Chemical.Engineering                         & -0.251\\
                                                & (0.376)\\
   Chemistry                                    & 0.095$^{*}$\\
                                                & (0.049)\\
   Computer.Science                             & 0.598$^{***}$\\
                                                & (0.120)\\
   Decision.Sciences                            & 0.659\\
                                                & (1.18)\\
   Dentistry                                    & 1.05$^{***}$\\
                                                & (0.192)\\
   Earth.and.Planetary.Sciences                 & 0.731$^{***}$\\
                                                & (0.248)\\
   Energy                                       & 0.090\\
                                                & (0.142)\\
   Engineering                                  & 0.596$^{***}$\\
                                                & (0.069)\\
   Immunology.and.Microbiology                  & -0.332$^{***}$\\
                                                & (0.053)\\
   Materials.Science                            & -0.374$^{***}$\\
                                                & (0.051)\\
   Mathematics                                  & 0.436\\
                                                & (0.638)\\
   Medicine                                     & 0.244$^{**}$\\
                                                & (0.114)\\
   Neuroscience                                 & 0.230$^{***}$\\
                                                & (0.082)\\
   Nursing                                      & 0.834$^{***}$\\
                                                & (0.099)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.678$^{***}$\\
                                                & (0.116)\\
   Physics.and.Astronomy                        & 0.014\\
                                                & (0.069)\\
   Psychology                                   & 0.622\\
                                                & (0.441)\\
   Social.Sciences                              & 0.889\\
                                                & (0.695)\\
   Veterinary                                   & 0.377\\
                                                & (0.296)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 19,042\\
   Squared Correlation                          & 0.06809\\
   Pseudo R$^2$                                 & 0.05161\\
   BIC                                          & 25,600.5\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [54]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_nps <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0)&(data$domain_Physical.Sciences==0), ], family = binomial("logit"), vcov = "hetero")
summary(model_nps)

NOTES: 20,108 observations removed because of NA values (LHS: 20,108, RHS: 20,108, Fixed-effects: 20,108).
       8 fixed-effects (14 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 24,526
Fixed-effects: PublishedYear: 36
Standard-errors: Heteroskedasticity-robust
                                               Estimate Std. Error     z value
CoTypeCollaboration                            0.261100   0.054730    4.770665
CoTypeParticipation                            0.505163   0.078218    6.458353
lnnum_author                                   0.198543   0.028587    6.945344
internationalinternational                     0.132736   0.031172    4.258187
lnnum_reference                               -0.167023   0.034480   -4.844006
num_fac                                       -0.115533   0.024075   -4.798812
SDGTrue                                        0.271951   0.027700    9.817773
lnmean_career_age                              0.203432   0.045236    4.497118
lnfirst_avgimpact                             -0.238572   0.014559  -16.386123
lnfirst_insthindex                            -0.191791   0.018710  -10.250513
first_GlobalSouthGlobalNorth                   0.148867   0.065578    2.270076
first_SameCountrySame                         -0.153287   0.030536   -5.019888
knowledge_proximity_mean                      -3.249496   0.444423   -7.311725
lnfirst_before_year_prod_fac                   0.013330   0.017822    0.747974
first_before_year_with_ih_binTrue              0.338049   0.046141    7.326486
Agricultural.and.Biological.Sciences           0.105319   0.046730    2.253787
Arts.and.Humanities                            0.874663   0.369056    2.369999
Biochemistry..Genetics.and.Molecular.Biology  -0.305472   0.040433   -7.555076
Business..Management.and.Accounting          -10.227644   0.072669 -140.743145
Decision.Sciences                             -0.370756   0.985408   -0.376246
Dentistry                                      1.148293   0.238348    4.817708
Health.Professions                             0.566822   0.341413    1.660222
Immunology.and.Microbiology                   -0.041592   0.043276   -0.961092
Medicine                                       0.573476   0.029645   19.344906
Neuroscience                                   0.335948   0.052733    6.370715
Nursing                                        0.835840   0.082535   10.127108
Pharmacology..Toxicology.and.Pharmaceutics     0.889205   0.096602    9.204825
Psychology                                     0.398676   0.241414    1.651423
Social.Sciences                               -0.130199   0.370873   -0.351062
Veterinary                                     0.322697   0.356451    0.905305
                                               Pr(>|z|)
CoTypeCollaboration                          1.8362e-06 ***
CoTypeParticipation                          1.0585e-10 ***
lnnum_author                                 3.7754e-12 ***
internationalinternational                   2.0609e-05 ***
lnnum_reference                              1.2725e-06 ***
num_fac                                      1.5961e-06 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            6.8881e-06 ***
lnfirst_avgimpact                             < 2.2e-16 ***
lnfirst_insthindex                            < 2.2e-16 ***
first_GlobalSouthGlobalNorth                 2.3203e-02 *
first_SameCountrySame                        5.1702e-07 ***
knowledge_proximity_mean                     2.6373e-13 ***
lnfirst_before_year_prod_fac                 4.5448e-01
first_before_year_with_ih_binTrue            2.3627e-13 ***
Agricultural.and.Biological.Sciences         2.4210e-02 *
Arts.and.Humanities                          1.7788e-02 *
Biochemistry..Genetics.and.Molecular.Biology 4.1861e-14 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Decision.Sciences                            7.0673e-01
Dentistry                                    1.4522e-06 ***
Health.Professions                           9.6870e-02 .
Immunology.and.Microbiology                  3.3651e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                 1.8815e-10 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Psychology                                   9.8652e-02 .
Social.Sciences                              7.2554e-01
Veterinary                                   3.6530e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -15,601.2   Adj. Pseudo R2: 0.063896
           BIC:  31,869.5     Squared Cor.: 0.089124

In [55]:
# 每组 reg_class 的平均预测概率
margins_eff_nps <- avg_comparisons(model_nps, variables = "CoType", comparison = 'ratio')
margins_eff_nps

  term   contrast                            estimate std.error  statistic
1 CoType mean(Collaboration) / mean(Service) 1.141390 0.04180786 27.30084
2 CoType mean(Participation) / mean(Service) 1.275099 0.07281343 17.51186
  p.value       s.value  conf.low conf.high predicted_lo predicted_hi predicted
1 4.145299e-164 542.7447 1.059448 1.223331  0.6177946    0.6772796    0.6177946
2  1.163266e-68 225.6729 1.132387 1.417810  0.6177946    0.7281705    0.6177946

In [56]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h2_nps_comp_ratio.csv")
# write.csv(margins_eff_nps, fname, row.names = FALSE)

In [57]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_nps,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                          & 0.261$^{***}$\\
                                                & (0.055)\\
   CoTypeParticipation                          & 0.505$^{***}$\\
                                                & (0.078)\\
   lnnum\_author                                & 0.199$^{***}$\\
                                                & (0.029)\\
   internationalinternational                   & 0.133$^{***}$\\
                                                & (0.031)\\
   lnnum\_reference                             & -0.167$^{***}$\\
                                                & (0.035)\\
   num\_fac                                     & -0.116$^{***}$\\
                                                & (0.024)\\
   SDGTrue                                      & 0.272$^{***}$\\
                                                & (0.028)\\
   lnmean\_career\_age                          & 0.203$^{***}$\\
                                                & (0.045)\\
   lnfirst\_avgimpact                           & -0.239$^{***}$\\
                                                & (0.015)\\
   lnfirst\_insthindex                          & -0.192$^{***}$\\
                                                & (0.019)\\
   first\_GlobalSouthGlobalNorth                & 0.149$^{**}$\\
                                                & (0.066)\\
   first\_SameCountrySame                       & -0.153$^{***}$\\
                                                & (0.030)\\
   knowledge\_proximity\_mean                   & -3.25$^{***}$\\
                                                & (0.444)\\
   lnfirst\_before\_year\_prod\_fac             & 0.013\\
                                                & (0.018)\\
   first\_before\_year\_with\_ih\_binTrue       & 0.338$^{***}$\\
                                                & (0.046)\\
   Agricultural.and.Biological.Sciences         & 0.105$^{**}$\\
                                                & (0.047)\\
   Arts.and.Humanities                          & 0.875$^{**}$\\
                                                & (0.369)\\
   Biochemistry..Genetics.and.Molecular.Biology & -0.305$^{***}$\\
                                                & (0.040)\\
   Business..Management.and.Accounting          & -10.2$^{***}$\\
                                                & (0.073)\\
   Decision.Sciences                            & -0.371\\
                                                & (0.985)\\
   Dentistry                                    & 1.15$^{***}$\\
                                                & (0.238)\\
   Immunology.and.Microbiology                  & -0.042\\
                                                & (0.043)\\
   Medicine                                     & 0.573$^{***}$\\
                                                & (0.030)\\
   Neuroscience                                 & 0.336$^{***}$\\
                                                & (0.053)\\
   Nursing                                      & 0.836$^{***}$\\
                                                & (0.083)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.889$^{***}$\\
                                                & (0.097)\\
   Psychology                                   & 0.399$^{*}$\\
                                                & (0.241)\\
   Social.Sciences                              & -0.130\\
                                                & (0.371)\\
   Veterinary                                   & 0.323\\
                                                & (0.356)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 24,526\\
   Squared Correlation                          & 0.08912\\
   Pseudo R$^2$                                 & 0.06778\\
   BIC                                          & 31,869.5\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H3: Too much will suppress

# H3a: Participation too much not good

In [58]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ ratio_fac_scientist + I(ratio_fac_scientist^2) +  ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_h3_pratio <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_h3_pratio)

NOTE: 107,910 observations removed because of NA values (LHS: 107,910, RHS: 107,910, Fixed-effects: 107,910).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 209,290
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
ratio_fac_scientist                           0.251694   0.069004   3.647520
I(ratio_fac_scientist^2)                     -0.188557   0.082658  -2.281186
lnnum_author                                 -0.140719   0.008267 -17.021587
internationalinternational                   -0.037975   0.011510  -3.299234
lnnum_reference                               0.000461   0.010159   0.045367
num_fac                                       0.080685   0.007879  10.240341
SDGTrue                                       0.054731   0.009891   5.533176
lnmean_career_age                             0.023003   0.015987   1.438857
lnfirst_avgimpact                            -0.113105   0.005715 -19.790078
lnfirst_insthindex                           -0.064276   0.006728  -9.553903
first_GlobalSouthGlobalNorth                  0.312893   0.019721  15.865745
first_SameCountrySame                        -0.108726   0.011290  -9.630386
knowledge_proximity_mean                     -0.269062   0.159508  -1.686825
lnfirst_before_year_prod_fac                  0.008465   0.005505   1.537575
first_before_year_with_ih_binTrue             0.168840   0.013304  12.691086
Agricultural.and.Biological.Sciences          0.807787   0.031280  25.824421
Arts.and.Humanities                           1.796832   0.086123  20.863652
Biochemistry..Genetics.and.Molecular.Biology  0.639191   0.015433  41.415934
Business..Management.and.Accounting          -0.387590   0.098938  -3.917492
Chemical.Engineering                          0.210234   0.025598   8.212886
Chemistry                                     0.485289   0.013593  35.702082
Computer.Science                              0.906324   0.049152  18.439329
Decision.Sciences                             1.358854   0.221630   6.131175
Dentistry                                     2.080943   0.176388  11.797500
Earth.and.Planetary.Sciences                  0.782777   0.018145  43.139940
Economics..Econometrics.and.Finance          -0.136634   0.383520  -0.356262
Energy                                        0.260571   0.021751  11.979992
Engineering                                   0.338237   0.012585  26.876743
Environmental.Science                         0.494724   0.022262  22.222845
Health.Professions                            1.599656   0.155143  10.310841
Immunology.and.Microbiology                   0.218728   0.036314   6.023315
Materials.Science                             0.063076   0.011857   5.319921
Mathematics                                   0.402064   0.148037   2.715967
Medicine                                      0.890786   0.019121  46.586369
Neuroscience                                  0.516869   0.042258  12.231290
Nursing                                       1.176844   0.063048  18.665843
Pharmacology..Toxicology.and.Pharmaceutics    0.833892   0.064635  12.901573
Physics.and.Astronomy                        -0.258049   0.013603 -18.970668
Psychology                                    0.287913   0.183746   1.566908
Social.Sciences                               0.334979   0.187147   1.789925
Veterinary                                    0.646251   0.302814   2.134153
                                               Pr(>|z|)
ratio_fac_scientist                          2.6478e-04 ***
I(ratio_fac_scientist^2)                     2.2537e-02 *
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   9.6949e-04 ***
lnnum_reference                              9.6381e-01
num_fac                                       < 2.2e-16 ***
SDGTrue                                      3.1448e-08 ***
lnmean_career_age                            1.5019e-01
lnfirst_avgimpact                             < 2.2e-16 ***
lnfirst_insthindex                            < 2.2e-16 ***
first_GlobalSouthGlobalNorth                  < 2.2e-16 ***
first_SameCountrySame                         < 2.2e-16 ***
knowledge_proximity_mean                     9.1637e-02 .
lnfirst_before_year_prod_fac                 1.2415e-01
first_before_year_with_ih_binTrue             < 2.2e-16 ***
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          8.9475e-05 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            8.7233e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.2164e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  1.7088e-09 ***
Materials.Science                            1.0381e-07 ***
Mathematics                                  6.6082e-03 **
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.1714e-01
Social.Sciences                              7.3466e-02 .
Veterinary                                   3.2830e-02 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -125,437.7   Adj. Pseudo R2: 0.058982
           BIC:  252,002.5     Squared Cor.: 0.073899

In [53]:
# library(marginaleffects)
# # 设置 draw = FALSE，直接拦截绘图数据
# plot_data <- plot_predictions(model_h3_pratio, condition = "ratio_fac_scientist", draw = FALSE)
# # 选出我们最需要的几列：x轴变量、预测值(estimate)、置信区间下限(conf.low)、上限(conf.high)
# export_data <- plot_data[, c("ratio_fac_scientist", "estimate", "conf.low", "conf.high")]
# # # 导出为 CSV 文件，给 Python 准备
# write.csv(export_data, "R_ex_ld_h3_pred_pratio.csv", row.names = FALSE)
# export_data
# # print("数据已成功导出！")
# # head(export_data)

   ratio_fac_scientist estimate  conf.low  conf.high
1  0.00000000          0.2586039 0.2064557 0.3186350
2  0.02003023          0.2602754 0.2078948 0.3205134
3  0.04006047          0.2618789 0.2092731 0.3223182
4  0.06009070          0.2634136 0.2105904 0.3240477
5  0.08012094          0.2648786 0.2118464 0.3257002
6  0.10015117          0.2662729 0.2130410 0.3272743
7  0.12018141          0.2675960 0.2141737 0.3287686
8  0.14021164          0.2688470 0.2152444 0.3301818
9  0.16024187          0.2700252 0.2162528 0.3315128
10 0.18027211          0.2711301 0.2171985 0.3327605
11 0.20030234          0.2721610 0.2180813 0.3339241
12 0.22033258          0.2731173 0.2189008 0.3350028
13 0.24036281          0.2739986 0.2196567 0.3359958
14 0.26039305          0.2748044 0.2203486 0.3369027
15 0.28042328          0.2755343 0.2209761 0.3377231
16 0.30045351          0.2761879 0.2215389 0.3384565
17 0.32048375          0.2767648 0.2220363 0.3391029
18 0.34051398          0.2772647 0.2224681 0.3396622
19 0.36054422          0.2776874 0.2228337 0.3401344
20 0.38057445          0.2780327 0.2231327 0.3405197
21 0.40060469          0.2783004 0.2233644 0.3408184
22 0.42063492          0.2784903 0.2235284 0.3410308
23 0.44066515          0.2786023 0.2236240 0.3411576
24 0.46069539          0.2786365 0.2236508 0.3411994
25 0.48072562          0.2785927 0.2236080 0.3411568
26 0.50075586          0.2784710 0.2234950 0.3410309
27 0.52078609          0.2782714 0.2233112 0.3408225
28 0.54081633          0.2779941 0.2230559 0.3405328
29 0.56084656          0.2776392 0.2227285 0.3401629
30 0.58087680          0.2772069 0.2223283 0.3397143
31 0.60090703          0.2766974 0.2218545 0.3391882
32 0.62093726          0.2761110 0.2213065 0.3385862
33 0.64096750          0.2754480 0.2206836 0.3379099
34 0.66099773          0.2747087 0.2199851 0.3371610
35 0.68102797          0.2738935 0.2192105 0.3363414
36 0.70105820          0.2730029 0.2183589 0.3354528
37 0.72108844          0.2720372 0.2174298 0.3344971
38 0.74111867          0.2709971 0.2164227 0.3334766
39 0.76114890          0.2698832 0.2153371 0.3323931
40 0.78117914          0.2686959 0.2141723 0.3312488
41 0.80120937          0.2674359 0.2129281 0.3300460
42 0.82123961          0.2661040 0.2116041 0.3287868
43 0.84126984          0.2647008 0.2102001 0.3274734
44 0.86130008          0.2632272 0.2087158 0.3261082
45 0.88133031          0.2616839 0.2071513 0.3246933
46 0.90136054          0.2600719 0.2055065 0.3232311
47 0.92139078          0.2583920 0.2037817 0.3217237
48 0.94142101          0.2566453 0.2019772 0.3201735
49 0.96145125          0.2548326 0.2000935 0.3185825
50 0.98148148          0.2529551 0.1981311 0.3169530

In [59]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_h3_pratio,
                           keep = c("ratio_fac_scientist", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   ratio\_fac\_scientist                        & 0.252$^{***}$\\
                                                & (0.069)\\
   ratio\_fac\_scientist square                 & -0.189$^{**}$\\
                                                & (0.083)\\
   lnnum\_author                                & -0.141$^{***}$\\
                                                & (0.008)\\
   internationalinternational                   & -0.038$^{***}$\\
                                                & (0.011)\\
   lnnum\_reference                             & 0.0005\\
                                                & (0.010)\\
   num\_fac                                     & 0.081$^{***}$\\
                                                & (0.008)\\
   SDGTrue                                      & 0.055$^{***}$\\
                                                & (0.010)\\
   lnmean\_career\_age                          & 0.023\\
                                                & (0.016)\\
   lnfirst\_avgimpact                           & -0.113$^{***}$\\
                                                & (0.006)\\
   lnfirst\_insthindex                          & -0.064$^{***}$\\
                                                & (0.007)\\
   first\_GlobalSouthGlobalNorth                & 0.313$^{***}$\\
                                                & (0.020)\\
   first\_SameCountrySame                       & -0.109$^{***}$\\
                                                & (0.011)\\
   knowledge\_proximity\_mean                   & -0.269$^{*}$\\
                                                & (0.160)\\
   lnfirst\_before\_year\_prod\_fac             & 0.008\\
                                                & (0.006)\\
   first\_before\_year\_with\_ih\_binTrue       & 0.169$^{***}$\\
                                                & (0.013)\\
   Agricultural.and.Biological.Sciences         & 0.808$^{***}$\\
                                                & (0.031)\\
   Arts.and.Humanities                          & 1.80$^{***}$\\
                                                & (0.086)\\
   Biochemistry..Genetics.and.Molecular.Biology & 0.639$^{***}$\\
                                                & (0.015)\\
   Business..Management.and.Accounting          & -0.388$^{***}$\\
                                                & (0.099)\\
   Chemical.Engineering                         & 0.210$^{***}$\\
                                                & (0.026)\\
   Chemistry                                    & 0.485$^{***}$\\
                                                & (0.014)\\
   Computer.Science                             & 0.906$^{***}$\\
                                                & (0.049)\\
   Decision.Sciences                            & 1.36$^{***}$\\
                                                & (0.222)\\
   Dentistry                                    & 2.08$^{***}$\\
                                                & (0.176)\\
   Earth.and.Planetary.Sciences                 & 0.783$^{***}$\\
                                                & (0.018)\\
   Economics..Econometrics.and.Finance          & -0.137\\
                                                & (0.384)\\
   Energy                                       & 0.261$^{***}$\\
                                                & (0.022)\\
   Engineering                                  & 0.338$^{***}$\\
                                                & (0.013)\\
   Immunology.and.Microbiology                  & 0.219$^{***}$\\
                                                & (0.036)\\
   Materials.Science                            & 0.063$^{***}$\\
                                                & (0.012)\\
   Mathematics                                  & 0.402$^{***}$\\
                                                & (0.148)\\
   Medicine                                     & 0.891$^{***}$\\
                                                & (0.019)\\
   Neuroscience                                 & 0.517$^{***}$\\
                                                & (0.042)\\
   Nursing                                      & 1.18$^{***}$\\
                                                & (0.063)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 0.834$^{***}$\\
                                                & (0.065)\\
   Physics.and.Astronomy                        & -0.258$^{***}$\\
                                                & (0.014)\\
   Psychology                                   & 0.288\\
                                                & (0.184)\\
   Social.Sciences                              & 0.335$^{*}$\\
                                                & (0.187)\\
   Veterinary                                   & 0.646$^{**}$\\
                                                & (0.303)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 209,290\\
   Squared Correlation                          & 0.07390\\
   Pseudo R$^2$                                 & 0.05966\\
   BIC                                          & 252,002.5\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# H3b: Lead too much not good

In [60]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ fac_scientist_lead_ratio + I(fac_scientist_lead_ratio^2) +  ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_h3_lratio <- feglm(fml, data = data[(data$paper_type =='article')&(data$CoType_Service==0)&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_h3_lratio)

NOTE: 28,316 observations removed because of NA values (LHS: 28,316, RHS: 28,316, Fixed-effects: 28,316).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 62,738
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
fac_scientist_lead_ratio                      0.253844   0.097991   2.590478
I(fac_scientist_lead_ratio^2)                -0.221903   0.101047  -2.196034
lnnum_author                                 -0.291021   0.015685 -18.554193
internationalinternational                   -0.040789   0.024530  -1.662785
lnnum_reference                               0.071592   0.019613   3.650239
num_fac                                       0.116161   0.011670   9.953413
SDGTrue                                       0.068212   0.018831   3.622335
lnmean_career_age                            -0.127315   0.033492  -3.801356
lnfirst_avgimpact                            -0.092884   0.011310  -8.212916
lnfirst_insthindex                           -0.047784   0.012673  -3.770405
first_GlobalSouthGlobalNorth                  0.425786   0.038644  11.018063
first_SameCountrySame                        -0.139689   0.022465  -6.217939
knowledge_proximity_mean                      0.348792   0.301663   1.156232
lnfirst_before_year_prod_fac                  0.039854   0.010545   3.779468
first_before_year_with_ih_binTrue            -0.039014   0.025924  -1.504939
Agricultural.and.Biological.Sciences          0.522121   0.062563   8.345490
Arts.and.Humanities                           2.120003   0.138921  15.260544
Biochemistry..Genetics.and.Molecular.Biology  0.880755   0.030731  28.659829
Business..Management.and.Accounting          -0.741943   0.173328  -4.280562
Chemical.Engineering                          0.254626   0.052994   4.804777
Chemistry                                     0.443425   0.026710  16.601327
Computer.Science                              0.839472   0.105618   7.948166
Decision.Sciences                             1.075637   0.349033   3.081762
Dentistry                                     2.117290   0.316617   6.687228
Earth.and.Planetary.Sciences                  0.978120   0.031143  31.407337
Economics..Econometrics.and.Finance          -0.382486   0.653538  -0.585254
Energy                                        0.338466   0.043094   7.854078
Engineering                                   0.327699   0.023111  14.179169
Environmental.Science                         0.703453   0.047898  14.686544
Health.Professions                            1.575384   0.254558   6.188698
Immunology.and.Microbiology                   0.161690   0.134766   1.199780
Materials.Science                            -0.106545   0.022241  -4.790489
Mathematics                                   0.180363   0.239517   0.753028
Medicine                                      1.375334   0.048336  28.453892
Neuroscience                                  0.594279   0.103944   5.717289
Nursing                                       2.155777   0.208726  10.328257
Pharmacology..Toxicology.and.Pharmaceutics    1.116655   0.180170   6.197769
Physics.and.Astronomy                        -0.383250   0.023390 -16.385373
Psychology                                   -0.332754   0.352673  -0.943519
Social.Sciences                              -0.097192   0.275839  -0.352351
Veterinary                                    0.513914   0.707554   0.726325
                                               Pr(>|z|)
fac_scientist_lead_ratio                     9.5843e-03 **
I(fac_scientist_lead_ratio^2)                2.8090e-02 *
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   9.6356e-02 .
lnnum_reference                              2.6200e-04 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                      2.9196e-04 ***
lnmean_career_age                            1.4391e-04 ***
lnfirst_avgimpact                             < 2.2e-16 ***
lnfirst_insthindex                           1.6298e-04 ***
first_GlobalSouthGlobalNorth                  < 2.2e-16 ***
first_SameCountrySame                        5.0373e-10 ***
knowledge_proximity_mean                     2.4759e-01
lnfirst_before_year_prod_fac                 1.5716e-04 ***
first_before_year_with_ih_binTrue            1.3234e-01
Agricultural.and.Biological.Sciences          < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          1.8642e-05 ***
Chemical.Engineering                         1.5492e-06 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                             1.8929e-15 ***
Decision.Sciences                            2.0578e-03 **
Dentistry                                    2.2744e-11 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          5.5838e-01
Energy                                       4.0272e-15 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                           6.0663e-10 ***
Immunology.and.Microbiology                  2.3022e-01
Materials.Science                            1.6638e-06 ***
Mathematics                                  4.5143e-01
Medicine                                      < 2.2e-16 ***
Neuroscience                                 1.0824e-08 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics   5.7269e-10 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   3.4542e-01
Social.Sciences                              7.2457e-01
Veterinary                                   4.6764e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -35,726.0   Adj. Pseudo R2: 0.097003
           BIC:  72,468.2     Squared Cor.: 0.121264

In [56]:
# library(marginaleffects)
# # 设置 draw = FALSE，直接拦截绘图数据
# plot_data <- plot_predictions(model_h3_lratio, condition = "fac_scientist_lead_ratio", draw = FALSE)
# # 选出我们最需要的几列：x轴变量、预测值(estimate)、置信区间下限(conf.low)、上限(conf.high)
# export_data <- plot_data[, c("fac_scientist_lead_ratio", "estimate", "conf.low", "conf.high")]
# # # 导出为 CSV 文件，给 Python 准备
# write.csv(export_data, "R_ex_ld_h3_pred_lratio.csv", row.names = FALSE)
# export_data
# # print("数据已成功导出！")
# # head(export_data)

   fac_scientist_lead_ratio estimate  conf.low  conf.high
1  0.00000000               0.2359182 0.1454126 0.3590855
2  0.01992225               0.2367804 0.1460109 0.3601789
3  0.03984451               0.2375872 0.1465681 0.3612065
4  0.05976676               0.2383381 0.1470844 0.3621670
5  0.07968902               0.2390328 0.1475599 0.3630593
6  0.09961127               0.2396709 0.1479948 0.3638823
7  0.11953353               0.2402522 0.1483892 0.3646349
8  0.13945578               0.2407763 0.1487431 0.3653162
9  0.15937804               0.2412429 0.1490569 0.3659254
10 0.17930029               0.2416519 0.1493304 0.3664618
11 0.19922255               0.2420031 0.1495639 0.3669247
12 0.21914480               0.2422962 0.1497575 0.3673136
13 0.23906706               0.2425311 0.1499111 0.3676279
14 0.25898931               0.2427077 0.1500249 0.3678674
15 0.27891156               0.2428260 0.1500988 0.3680317
16 0.29883382               0.2428858 0.1501331 0.3681206
17 0.31875607               0.2428871 0.1501276 0.3681340
18 0.33867833               0.2428300 0.1500823 0.3680720
19 0.35860058               0.2427144 0.1499973 0.3679345
20 0.37852284               0.2425404 0.1498726 0.3677217
21 0.39844509               0.2423082 0.1497081 0.3674340
22 0.41836735               0.2420177 0.1495038 0.3670717
23 0.43828960               0.2416692 0.1492596 0.3666351
24 0.45821186               0.2412629 0.1489755 0.3661249
25 0.47813411               0.2407988 0.1486513 0.3655416
26 0.49805637               0.2402774 0.1482871 0.3648860
27 0.51797862               0.2396987 0.1478826 0.3641589
28 0.53790087               0.2390632 0.1474378 0.3633611
29 0.55782313               0.2383710 0.1469526 0.3624936
30 0.57774538               0.2376227 0.1464269 0.3615575
31 0.59766764               0.2368185 0.1458605 0.3605540
32 0.61758989               0.2359588 0.1452534 0.3594842
33 0.63751215               0.2350441 0.1446053 0.3583495
34 0.65743440               0.2340749 0.1439162 0.3571513
35 0.67735666               0.2330516 0.1431859 0.3558911
36 0.69727891               0.2319747 0.1424144 0.3545704
37 0.71720117               0.2308449 0.1416016 0.3531910
38 0.73712342               0.2296626 0.1407472 0.3517544
39 0.75704568               0.2284286 0.1398514 0.3502624
40 0.77696793               0.2271434 0.1389139 0.3487170
41 0.79689018               0.2258078 0.1379348 0.3471201
42 0.81681244               0.2244223 0.1369141 0.3454736
43 0.83673469               0.2229879 0.1358517 0.3437795
44 0.85665695               0.2215051 0.1347477 0.3420400
45 0.87657920               0.2199748 0.1336021 0.3402572
46 0.89650146               0.2183979 0.1324152 0.3384333
47 0.91642371               0.2167751 0.1311870 0.3365704
48 0.93634597               0.2151073 0.1299178 0.3346709
49 0.95626822               0.2133956 0.1286079 0.3327370
50 0.97619048               0.2116407 0.1272575 0.3307710

In [61]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_h3_lratio,
                           keep = c("fac_scientist_lead_ratio", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                          & novel\_uzzi\_bin\\
   Model:                                       & (1)\\
   \midrule
   \emph{Variables}\\
   fac\_scientist\_lead\_ratio                  & 0.254$^{***}$\\
                                                & (0.098)\\
   fac\_scientist\_lead\_ratio square           & -0.222$^{**}$\\
                                                & (0.101)\\
   lnnum\_author                                & -0.291$^{***}$\\
                                                & (0.016)\\
   internationalinternational                   & -0.041$^{*}$\\
                                                & (0.025)\\
   lnnum\_reference                             & 0.072$^{***}$\\
                                                & (0.020)\\
   num\_fac                                     & 0.116$^{***}$\\
                                                & (0.012)\\
   SDGTrue                                      & 0.068$^{***}$\\
                                                & (0.019)\\
   lnmean\_career\_age                          & -0.127$^{***}$\\
                                                & (0.034)\\
   lnfirst\_avgimpact                           & -0.093$^{***}$\\
                                                & (0.011)\\
   lnfirst\_insthindex                          & -0.048$^{***}$\\
                                                & (0.013)\\
   first\_GlobalSouthGlobalNorth                & 0.426$^{***}$\\
                                                & (0.039)\\
   first\_SameCountrySame                       & -0.140$^{***}$\\
                                                & (0.022)\\
   knowledge\_proximity\_mean                   & 0.349\\
                                                & (0.302)\\
   lnfirst\_before\_year\_prod\_fac             & 0.040$^{***}$\\
                                                & (0.011)\\
   first\_before\_year\_with\_ih\_binTrue       & -0.039\\
                                                & (0.026)\\
   Agricultural.and.Biological.Sciences         & 0.522$^{***}$\\
                                                & (0.063)\\
   Arts.and.Humanities                          & 2.12$^{***}$\\
                                                & (0.139)\\
   Biochemistry..Genetics.and.Molecular.Biology & 0.881$^{***}$\\
                                                & (0.031)\\
   Business..Management.and.Accounting          & -0.742$^{***}$\\
                                                & (0.173)\\
   Chemical.Engineering                         & 0.255$^{***}$\\
                                                & (0.053)\\
   Chemistry                                    & 0.443$^{***}$\\
                                                & (0.027)\\
   Computer.Science                             & 0.839$^{***}$\\
                                                & (0.106)\\
   Decision.Sciences                            & 1.08$^{***}$\\
                                                & (0.349)\\
   Dentistry                                    & 2.12$^{***}$\\
                                                & (0.317)\\
   Earth.and.Planetary.Sciences                 & 0.978$^{***}$\\
                                                & (0.031)\\
   Economics..Econometrics.and.Finance          & -0.382\\
                                                & (0.654)\\
   Energy                                       & 0.338$^{***}$\\
                                                & (0.043)\\
   Engineering                                  & 0.328$^{***}$\\
                                                & (0.023)\\
   Immunology.and.Microbiology                  & 0.162\\
                                                & (0.135)\\
   Materials.Science                            & -0.107$^{***}$\\
                                                & (0.022)\\
   Mathematics                                  & 0.180\\
                                                & (0.240)\\
   Medicine                                     & 1.38$^{***}$\\
                                                & (0.048)\\
   Neuroscience                                 & 0.594$^{***}$\\
                                                & (0.104)\\
   Nursing                                      & 2.16$^{***}$\\
                                                & (0.209)\\
   Pharmacology..Toxicology.and.Pharmaceutics   & 1.12$^{***}$\\
                                                & (0.180)\\
   Physics.and.Astronomy                        & -0.383$^{***}$\\
                                                & (0.023)\\
   Psychology                                   & -0.333\\
                                                & (0.353)\\
   Social.Sciences                              & -0.097\\
                                                & (0.276)\\
   Veterinary                                   & 0.514\\
                                                & (0.708)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                 & 62,738\\
   Squared Correlation                          & 0.12126\\
   Pseudo R$^2$                                 & 0.09930\\
   BIC                                          & 72,468.2\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

# Moderating

In [62]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*lnfirst_before_year_prod_fac  + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_pre_facpub <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_facpub)

NOTE: 107,910 observations removed because of NA values (LHS: 107,910, RHS: 107,910, Fixed-effects: 107,910).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 209,290
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                  Estimate Std. Error
CoTypeCollaboration                               0.137011   0.021352
CoTypeParticipation                               0.119144   0.028024
lnfirst_before_year_prod_fac                      0.025373   0.006324
lnnum_author                                     -0.131355   0.008746
internationalinternational                       -0.041206   0.011471
lnnum_reference                                   0.001147   0.010153
num_fac                                           0.081780   0.007885
SDGTrue                                           0.053987   0.009893
lnmean_career_age                                 0.018404   0.016000
lnfirst_avgimpact                                -0.113142   0.005715
lnfirst_insthindex                               -0.064547   0.006707
first_GlobalSouthGlobalNorth                      0.313359   0.019716
first_SameCountrySame                            -0.111510   0.011319
knowledge_proximity_mean                         -0.272434   0.159412
first_before_year_with_ih_binTrue                 0.167164   0.013365
Agricultural.and.Biological.Sciences              0.804021   0.031289
Arts.and.Humanities                               1.797130   0.086242
Biochemistry..Genetics.and.Molecular.Biology      0.638487   0.015441
Business..Management.and.Accounting              -0.392149   0.098935
Chemical.Engineering                              0.211059   0.025595
Chemistry                                         0.484208   0.013594
Computer.Science                                  0.904125   0.049130
Decision.Sciences                                 1.355624   0.221495
Dentistry                                         2.082778   0.176773
Earth.and.Planetary.Sciences                      0.782289   0.018148
Economics..Econometrics.and.Finance              -0.132318   0.383827
Energy                                            0.258821   0.021754
Engineering                                       0.335784   0.012588
Environmental.Science                             0.494333   0.022258
Health.Professions                                1.603768   0.155286
Immunology.and.Microbiology                       0.217092   0.036299
Materials.Science                                 0.062281   0.011855
Mathematics                                       0.402633   0.148336
Medicine                                          0.891254   0.019130
Neuroscience                                      0.515605   0.042247
Nursing                                           1.177882   0.063074
Pharmacology..Toxicology.and.Pharmaceutics        0.835551   0.064557
Physics.and.Astronomy                            -0.258509   0.013587
Psychology                                        0.292150   0.183621
Social.Sciences                                   0.327163   0.186730
Veterinary                                        0.641749   0.302589
CoTypeCollaboration:lnfirst_before_year_prod_fac -0.034751   0.010000
CoTypeParticipation:lnfirst_before_year_prod_fac -0.091441   0.014262
                                                    z value   Pr(>|z|)
CoTypeCollaboration                                6.416871 1.3910e-10 ***
CoTypeParticipation                                4.251542 2.1230e-05 ***
lnfirst_before_year_prod_fac                       4.012251 6.0142e-05 ***
lnnum_author                                     -15.019182  < 2.2e-16 ***
internationalinternational                        -3.592104 3.2802e-04 ***
lnnum_reference                                    0.112973 9.1005e-01
num_fac                                           10.371685  < 2.2e-16 ***
SDGTrue                                            5.457060 4.8408e-08 ***
lnmean_career_age                                  1.150190 2.5007e-01
lnfirst_avgimpact                                -19.798754  < 2.2e-16 ***
lnfirst_insthindex                                -9.624468  < 2.2e-16 ***
first_GlobalSouthGlobalNorth                      15.893446  < 2.2e-16 ***
first_SameCountrySame                             -9.851603  < 2.2e-16 ***
knowledge_proximity_mean                          -1.708993 8.7452e-02 .
first_before_year_with_ih_binTrue                 12.507776  < 2.2e-16 ***
Agricultural.and.Biological.Sciences              25.696728  < 2.2e-16 ***
Arts.and.Humanities                               20.838284  < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology      41.348829  < 2.2e-16 ***
Business..Management.and.Accounting               -3.963717 7.3792e-05 ***
Chemical.Engineering                               8.246020  < 2.2e-16 ***
Chemistry                                         35.619648  < 2.2e-16 ***
Computer.Science                                  18.402538  < 2.2e-16 ***
Decision.Sciences                                  6.120327 9.3384e-10 ***
Dentistry                                         11.782212  < 2.2e-16 ***
Earth.and.Planetary.Sciences                      43.105126  < 2.2e-16 ***
Economics..Econometrics.and.Finance               -0.344734 7.3029e-01
Energy                                            11.897457  < 2.2e-16 ***
Engineering                                       26.674244  < 2.2e-16 ***
Environmental.Science                             22.208733  < 2.2e-16 ***
Health.Professions                                10.327829  < 2.2e-16 ***
Immunology.and.Microbiology                        5.980701 2.2218e-09 ***
Materials.Science                                  5.253449 1.4928e-07 ***
Mathematics                                        2.714332 6.6410e-03 **
Medicine                                          46.589828  < 2.2e-16 ***
Neuroscience                                      12.204466  < 2.2e-16 ***
Nursing                                           18.674744  < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics        12.942773  < 2.2e-16 ***
Physics.and.Astronomy                            -19.026621  < 2.2e-16 ***
Psychology                                         1.591047 1.1160e-01
Social.Sciences                                    1.752063 7.9763e-02 .
Veterinary                                         2.120861 3.3933e-02 *
CoTypeCollaboration:lnfirst_before_year_prod_fac  -3.475150 5.1057e-04 ***
CoTypeParticipation:lnfirst_before_year_prod_fac  -6.411657 1.4395e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -125,403.8   Adj. Pseudo R2: 0.059221
           BIC:  251,959.3     Squared Cor.: 0.074122

In [63]:
# # 1. 找到你这个连续变量的实际最小值和最大值（假设是 0 和 10，你需要改成你的实际极值）
# min_val <- min(data$lnex_ld_avg_before_year_prod_fac, na.rm=TRUE)
# max_val <- max(data$lnex_ld_avg_before_year_prod_fac, na.rm=TRUE)
# # 2. 运行估计
# res_pre_facpub <- avg_comparisons(
#     model_pre_facpub,
#     variables = "CoType",
#     comparison = "ratio",
#     newdata = datagrid(
#     model = model_pre_facpub,
#     lnex_ld_avg_before_year_prod_fac = seq(min_val, max_val, length.out = 50) # 这里的 10 可以改成任意你想要的数字
#   ),
#     by = "lnex_ld_avg_before_year_prod_fac"
# )
# res_pre_facpub

In [64]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_facpub.csv")
# write.csv(res_pre_facpub, fname, row.names = FALSE)

In [65]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_facpub,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

\begingroup
\centering
\begin{tabular}{lc}
   \tabularnewline \midrule \midrule
   Dependent Variable:                                                & novel\_uzzi\_bin\\
   Model:                                                             & (1)\\
   \midrule
   \emph{Variables}\\
   CoTypeCollaboration                                                & 0.137$^{***}$\\
                                                                      & (0.021)\\
   CoTypeParticipation                                                & 0.119$^{***}$\\
                                                                      & (0.028)\\
   lnfirst\_before\_year\_prod\_fac                                   & 0.025$^{***}$\\
                                                                      & (0.006)\\
   lnnum\_author                                                      & -0.131$^{***}$\\
                                                                      & (0.009)\\
   internationalinternational                                         & -0.041$^{***}$\\
                                                                      & (0.011)\\
   lnnum\_reference                                                   & 0.001\\
                                                                      & (0.010)\\
   num\_fac                                                           & 0.082$^{***}$\\
                                                                      & (0.008)\\
   SDGTrue                                                            & 0.054$^{***}$\\
                                                                      & (0.010)\\
   lnmean\_career\_age                                                & 0.018\\
                                                                      & (0.016)\\
   lnfirst\_avgimpact                                                 & -0.113$^{***}$\\
                                                                      & (0.006)\\
   lnfirst\_insthindex                                                & -0.065$^{***}$\\
                                                                      & (0.007)\\
   first\_GlobalSouthGlobalNorth                                      & 0.313$^{***}$\\
                                                                      & (0.020)\\
   first\_SameCountrySame                                             & -0.112$^{***}$\\
                                                                      & (0.011)\\
   knowledge\_proximity\_mean                                         & -0.272$^{*}$\\
                                                                      & (0.159)\\
   first\_before\_year\_with\_ih\_binTrue                             & 0.167$^{***}$\\
                                                                      & (0.013)\\
   Agricultural.and.Biological.Sciences                               & 0.804$^{***}$\\
                                                                      & (0.031)\\
   Arts.and.Humanities                                                & 1.80$^{***}$\\
                                                                      & (0.086)\\
   Biochemistry..Genetics.and.Molecular.Biology                       & 0.638$^{***}$\\
                                                                      & (0.015)\\
   Business..Management.and.Accounting                                & -0.392$^{***}$\\
                                                                      & (0.099)\\
   Chemical.Engineering                                               & 0.211$^{***}$\\
                                                                      & (0.026)\\
   Chemistry                                                          & 0.484$^{***}$\\
                                                                      & (0.014)\\
   Computer.Science                                                   & 0.904$^{***}$\\
                                                                      & (0.049)\\
   Decision.Sciences                                                  & 1.36$^{***}$\\
                                                                      & (0.221)\\
   Dentistry                                                          & 2.08$^{***}$\\
                                                                      & (0.177)\\
   Earth.and.Planetary.Sciences                                       & 0.782$^{***}$\\
                                                                      & (0.018)\\
   Economics..Econometrics.and.Finance                                & -0.132\\
                                                                      & (0.384)\\
   Energy                                                             & 0.259$^{***}$\\
                                                                      & (0.022)\\
   Engineering                                                        & 0.336$^{***}$\\
                                                                      & (0.013)\\
   Immunology.and.Microbiology                                        & 0.217$^{***}$\\
                                                                      & (0.036)\\
   Materials.Science                                                  & 0.062$^{***}$\\
                                                                      & (0.012)\\
   Mathematics                                                        & 0.403$^{***}$\\
                                                                      & (0.148)\\
   Medicine                                                           & 0.891$^{***}$\\
                                                                      & (0.019)\\
   Neuroscience                                                       & 0.516$^{***}$\\
                                                                      & (0.042)\\
   Nursing                                                            & 1.18$^{***}$\\
                                                                      & (0.063)\\
   Pharmacology..Toxicology.and.Pharmaceutics                         & 0.836$^{***}$\\
                                                                      & (0.065)\\
   Physics.and.Astronomy                                              & -0.259$^{***}$\\
                                                                      & (0.014)\\
   Psychology                                                         & 0.292\\
                                                                      & (0.184)\\
   Social.Sciences                                                    & 0.327$^{*}$\\
                                                                      & (0.187)\\
   Veterinary                                                         & 0.642$^{**}$\\
                                                                      & (0.303)\\
   CoTypeCollaboration $\times$ lnfirst\_before\_year\_prod\_fac      & -0.035$^{***}$\\
                                                                      & (0.010)\\
   CoTypeParticipation $\times$ lnfirst\_before\_year\_prod\_fac      & -0.091$^{***}$\\
                                                                      & (0.014)\\
   \midrule
   \emph{Fixed-effects}\\
   PublishedYear                                                      & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                                                       & 209,290\\
   Squared Correlation                                                & 0.07412\\
   Pseudo R$^2$                                                       & 0.05992\\
   BIC                                                                & 251,959.3\\
   \midrule \midrule
   \multicolumn{2}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\
   \multicolumn{2}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

In [66]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*first_before_year_with_ih_bin  + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model_pre_withih <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_withih)

NOTE: 107,910 observations removed because of NA values (LHS: 107,910, RHS: 107,910, Fixed-effects: 107,910).

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 209,290
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                                       Estimate Std. Error
CoTypeCollaboration                                    0.220297   0.021922
CoTypeParticipation                                    0.175689   0.028747
first_before_year_with_ih_binTrue                      0.242838   0.014955
lnnum_author                                          -0.135778   0.008470
internationalinternational                            -0.040907   0.011458
lnnum_reference                                        0.002023   0.010152
num_fac                                                0.082448   0.007873
SDGTrue                                                0.054767   0.009895
lnmean_career_age                                      0.017357   0.015997
lnfirst_avgimpact                                     -0.114864   0.005719
lnfirst_insthindex                                    -0.064743   0.006703
first_GlobalSouthGlobalNorth                           0.311540   0.019721
first_SameCountrySame                                 -0.107881   0.011316
knowledge_proximity_mean                              -0.224743   0.159529
lnfirst_before_year_prod_fac                           0.012372   0.005530
Agricultural.and.Biological.Sciences                   0.802679   0.031287
Arts.and.Humanities                                    1.792240   0.086335
Biochemistry..Genetics.and.Molecular.Biology           0.642065   0.015446
Business..Management.and.Accounting                   -0.393692   0.098955
Chemical.Engineering                                   0.212464   0.025614
Chemistry                                              0.483461   0.013601
Computer.Science                                       0.906801   0.049184
Decision.Sciences                                      1.362454   0.221384
Dentistry                                              2.082066   0.177002
Earth.and.Planetary.Sciences                           0.781997   0.018155
Economics..Econometrics.and.Finance                   -0.149519   0.384371
Energy                                                 0.258018   0.021766
Engineering                                            0.335572   0.012588
Environmental.Science                                  0.495571   0.022252
Health.Professions                                     1.608101   0.155441
Immunology.and.Microbiology                            0.220656   0.036321
Materials.Science                                      0.060750   0.011864
Mathematics                                            0.399708   0.148326
Medicine                                               0.895697   0.019145
Neuroscience                                           0.516814   0.042298
Nursing                                                1.176403   0.063018
Pharmacology..Toxicology.and.Pharmaceutics             0.837427   0.064655
Physics.and.Astronomy                                 -0.260742   0.013589
Psychology                                             0.299152   0.183324
Social.Sciences                                        0.328723   0.186988
Veterinary                                             0.649070   0.301548
CoTypeCollaboration:first_before_year_with_ih_binTrue -0.232971   0.027053
CoTypeParticipation:first_before_year_with_ih_binTrue -0.336796   0.036355
                                                         z value   Pr(>|z|)
CoTypeCollaboration                                    10.049202  < 2.2e-16 ***
CoTypeParticipation                                     6.111494 9.8703e-10 ***
first_before_year_with_ih_binTrue                      16.237378  < 2.2e-16 ***
lnnum_author                                          -16.030606  < 2.2e-16 ***
internationalinternational                             -3.570221 3.5668e-04 ***
lnnum_reference                                         0.199231 8.4208e-01
num_fac                                                10.472745  < 2.2e-16 ***
SDGTrue                                                 5.534920 3.1137e-08 ***
lnmean_career_age                                       1.084979 2.7793e-01
lnfirst_avgimpact                                     -20.085668  < 2.2e-16 ***
lnfirst_insthindex                                     -9.658310  < 2.2e-16 ***
first_GlobalSouthGlobalNorth                           15.797056  < 2.2e-16 ***
first_SameCountrySame                                  -9.533137  < 2.2e-16 ***
knowledge_proximity_mean                               -1.408794 1.5890e-01
lnfirst_before_year_prod_fac                            2.237413 2.5259e-02 *
Agricultural.and.Biological.Sciences                   25.655571  < 2.2e-16 ***
Arts.and.Humanities                                    20.759098  < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology           41.567412  < 2.2e-16 ***
Business..Management.and.Accounting                    -3.978483 6.9356e-05 ***
Chemical.Engineering                                    8.294866  < 2.2e-16 ***
Chemistry                                              35.545122  < 2.2e-16 ***
Computer.Science                                       18.436794  < 2.2e-16 ***
Decision.Sciences                                       6.154267 7.5426e-10 ***
Dentistry                                              11.762960  < 2.2e-16 ***
Earth.and.Planetary.Sciences                           43.074276  < 2.2e-16 ***
Economics..Econometrics.and.Finance                    -0.388996 6.9728e-01
Energy                                                 11.854382  < 2.2e-16 ***
Engineering                                            26.658994  < 2.2e-16 ***
Environmental.Science                                  22.271020  < 2.2e-16 ***
Health.Professions                                     10.345406  < 2.2e-16 ***
Immunology.and.Microbiology                             6.075138 1.2388e-09 ***
Materials.Science                                       5.120694 3.0441e-07 ***
Mathematics                                             2.694791 7.0433e-03 **
Medicine                                               46.783749  < 2.2e-16 ***
Neuroscience                                           12.218325  < 2.2e-16 ***
Nursing                                                18.667878  < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics             12.952170  < 2.2e-16 ***
Physics.and.Astronomy                                 -19.188098  < 2.2e-16 ***
Psychology                                              1.631822 1.0272e-01
Social.Sciences                                         1.757990 7.8749e-02 .
Veterinary                                              2.152458 3.1361e-02 *
CoTypeCollaboration:first_before_year_with_ih_binTrue  -8.611744  < 2.2e-16 ***
CoTypeParticipation:first_before_year_with_ih_binTrue  -9.264144  < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -125,359.6   Adj. Pseudo R2: 0.059552
           BIC:  251,870.8     Squared Cor.: 0.074567

In [ ]:
# 每组 reg_class 的平均预测概率
res_pre_withih <- avg_comparisons(model_pre_withih, variables = "CoType", comparison = 'ratio', by = 'ex_ld_max_before_year_with_ih_bin')
res_pre_withih

In [62]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_withih.csv")
# write.csv(res_pre_withih, fname, row.names = FALSE)

In [ ]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_withih,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

In [ ]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*first_before_year_participation_bin  + ", paper_level, "+", ex_controls, "+", moderating2, "+",disciplines, " | PublishedYear")
)
model_pre_partic <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_partic)

In [ ]:
# 每组 reg_class 的平均预测概率
res_pre_partic <- avg_comparisons(model_pre_partic, variables = "CoType", comparison = 'ratio', by = 'ex_ld_max_before_year_participation_bin')
res_pre_partic

In [ ]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_partic.csv")
# write.csv(res_pre_partic, fname, row.names = FALSE)

In [ ]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_partic,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

In [ ]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType*first_before_year_co_lead_bin  + ", paper_level, "+", ex_controls, "+", moderating3, "+",disciplines, " | PublishedYear")
)
model_pre_co_lead <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model_pre_co_lead)

In [ ]:
# 每组 reg_class 的平均预测概率
res_pre_co_lead <- avg_comparisons(model_pre_co_lead, variables = "CoType", comparison = 'ratio', by = 'ex_ld_max_before_year_co_lead_bin')
res_pre_co_lead

In [ ]:
# fname = paste0(main_path, "GraduationPaper/RevisetoJournal/R_ex_ld_h4_comp_pre_co_lead.csv")
# write.csv(res_pre_co_lead, fname, row.names = FALSE)

In [ ]:
etable_list <- vector("list", 1) 

etable_list[[1]] <- etable(model_pre_co_lead,
                           keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                           se = "hetero",
                           tex = TRUE,
                           digits = 3)
# 合并 LaTeX 代码（手动拼接）
tab_latex <- paste(unlist(etable_list), collapse = "\n")
cat(tab_latex)

# 补充一个更deep的point，曾经开展过“Co-lead”,后续合作/参与的收益受损更严重

In [88]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", disciplines, " | PublishedYear")
)
model1 <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model1)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.168124   0.010601  15.859520
CoTypeParticipation                           0.047151   0.014212   3.317634
Arts.and.Humanities                           1.837644   0.072240  25.438148
Biochemistry..Genetics.and.Molecular.Biology  0.498277   0.012207  40.818163
Business..Management.and.Accounting          -0.428431   0.087633  -4.888910
Chemical.Engineering                          0.131064   0.020722   6.324869
Chemistry                                     0.458689   0.010925  41.986380
Computer.Science                              0.896830   0.039192  22.883139
Decision.Sciences                             1.233745   0.187252   6.588695
Dentistry                                     1.993278   0.134826  14.784118
Earth.and.Planetary.Sciences                  0.736660   0.015022  49.039048
Economics..Econometrics.and.Finance          -0.125156   0.298301  -0.419561
Energy                                        0.173190   0.017787   9.737107
Engineering                                   0.339560   0.010213  33.249267
Environmental.Science                         0.570669   0.017255  33.072600
Health.Professions                            1.407273   0.128367  10.962920
Immunology.and.Microbiology                   0.100053   0.026312   3.802612
Materials.Science                             0.025108   0.009434   2.661385
Mathematics                                   0.563191   0.123799   4.549254
Medicine                                      0.768655   0.014474  53.104109
Neuroscience                                  0.459560   0.031942  14.387405
Nursing                                       1.152191   0.043429  26.530236
Pharmacology..Toxicology.and.Pharmaceutics    0.918273   0.047863  19.185553
Physics.and.Astronomy                        -0.258106   0.010956 -23.557539
Psychology                                    0.350436   0.151391   2.314773
Social.Sciences                               0.190551   0.160549   1.186869
Veterinary                                    0.572486   0.204304   2.802123
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          9.0783e-04 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          1.0140e-06 ***
Chemical.Engineering                         2.5345e-10 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            4.4371e-11 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          6.7481e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  1.4318e-04 ***
Materials.Science                            7.7820e-03 **
Mathematics                                  5.3836e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   2.0625e-02 *
Social.Sciences                              2.3528e-01
Veterinary                                   5.0767e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -183,760.0   Adj. Pseudo R2: 0.047631
           BIC:  368,502.4     Squared Cor.: 0.061434

In [89]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+",disciplines, " | PublishedYear")
)
model2 <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model2)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.176029   0.010963  16.055991
CoTypeParticipation                           0.095087   0.014820   6.416025
lnnum_author                                 -0.130941   0.007103 -18.433963
internationalinternational                   -0.007958   0.008684  -0.916399
lnnum_reference                              -0.005923   0.008397  -0.705350
num_fac                                       0.050942   0.006548   7.779950
SDGTrue                                       0.087651   0.008086  10.840337
lnmean_career_age                            -0.007336   0.012674  -0.578814
Arts.and.Humanities                           1.805187   0.072180  25.009688
Biochemistry..Genetics.and.Molecular.Biology  0.488323   0.012268  39.804343
Business..Management.and.Accounting          -0.391345   0.087633  -4.465750
Chemical.Engineering                          0.118096   0.020734   5.695810
Chemistry                                     0.444182   0.010966  40.504784
Computer.Science                              0.885696   0.039163  22.615553
Decision.Sciences                             1.238200   0.185634   6.670124
Dentistry                                     1.986729   0.134600  14.760297
Earth.and.Planetary.Sciences                  0.718174   0.015107  47.537625
Economics..Econometrics.and.Finance          -0.174566   0.297157  -0.587455
Energy                                        0.167031   0.017788   9.390262
Engineering                                   0.327907   0.010299  31.839979
Environmental.Science                         0.543065   0.017326  31.344035
Health.Professions                            1.400534   0.127912  10.949218
Immunology.and.Microbiology                   0.103796   0.026436   3.926278
Materials.Science                             0.017062   0.009536   1.789206
Mathematics                                   0.544282   0.123426   4.409785
Medicine                                      0.770899   0.014524  53.076124
Neuroscience                                  0.459724   0.032017  14.358708
Nursing                                       1.138679   0.043461  26.199802
Pharmacology..Toxicology.and.Pharmaceutics    0.897898   0.047950  18.725619
Physics.and.Astronomy                        -0.245058   0.011148 -21.982119
Psychology                                    0.333723   0.152340   2.190644
Social.Sciences                               0.199570   0.159341   1.252474
Veterinary                                    0.583049   0.205573   2.836216
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          1.3988e-10 ***
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   3.5946e-01
lnnum_reference                              4.8059e-01
num_fac                                      7.2553e-15 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            5.6271e-01
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          7.9789e-06 ***
Chemical.Engineering                         1.2279e-08 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            2.5559e-11 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          5.5690e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  8.6270e-05 ***
Materials.Science                            7.3582e-02 .
Mathematics                                  1.0347e-05 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   2.8478e-02 *
Social.Sciences                              2.1040e-01
Veterinary                                   4.5652e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -183,528.9   Adj. Pseudo R2: 0.048797
           BIC:  368,115.7     Squared Cor.: 0.062365

In [90]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+",disciplines, " | PublishedYear")
)
model3 <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model3)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.143687   0.011097  12.948869
CoTypeParticipation                           0.047011   0.014969   3.140640
lnnum_author                                 -0.068658   0.007116  -9.648419
internationalinternational                   -0.031089   0.009559  -3.252299
lnnum_reference                               0.061520   0.008603   7.150632
num_fac                                       0.059498   0.006605   9.007958
SDGTrue                                       0.092371   0.008114  11.384687
lnmean_career_age                             0.033050   0.012852   2.571617
lnex_ld_avg_avgimpact                        -0.264828   0.007259 -36.483771
lnex_ld_avg_insthindex                       -0.049529   0.007468  -6.632131
ex_ld_bin_gsGlobalNorth                       0.319559   0.017431  18.332975
ex_ld_bin_sameCSame                          -0.088044   0.009395  -9.371276
knowledge_proximity_mean                     -0.536984   0.156999  -3.420305
Arts.and.Humanities                           1.761999   0.072602  24.269151
Biochemistry..Genetics.and.Molecular.Biology  0.560437   0.012537  44.703274
Business..Management.and.Accounting          -0.344905   0.088174  -3.911635
Chemical.Engineering                          0.127998   0.020763   6.164848
Chemistry                                     0.436398   0.011069  39.426244
Computer.Science                              0.885328   0.039395  22.473379
Decision.Sciences                             1.205541   0.188256   6.403744
Dentistry                                     1.932497   0.135449  14.267307
Earth.and.Planetary.Sciences                  0.707815   0.015281  46.318485
Economics..Econometrics.and.Finance          -0.146465   0.292554  -0.500642
Energy                                        0.215856   0.017843  12.097741
Engineering                                   0.301371   0.010388  29.012331
Environmental.Science                         0.556121   0.017498  31.781864
Health.Professions                            1.376601   0.128348  10.725554
Immunology.and.Microbiology                   0.170265   0.026632   6.393299
Materials.Science                             0.001639   0.009727   0.168540
Mathematics                                   0.566115   0.123863   4.570476
Medicine                                      0.805057   0.014620  55.064785
Neuroscience                                  0.513867   0.032067  16.024855
Nursing                                       1.142418   0.043670  26.160014
Pharmacology..Toxicology.and.Pharmaceutics    0.891611   0.047942  18.597867
Physics.and.Astronomy                        -0.293480   0.011296 -25.979886
Psychology                                    0.370676   0.153231   2.419069
Social.Sciences                               0.155397   0.156885   0.990516
Veterinary                                    0.592872   0.205209   2.889114
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          1.6858e-03 **
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   1.1448e-03 **
lnnum_reference                              8.6379e-13 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            1.0122e-02 *
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       3.3087e-11 ***
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                           < 2.2e-16 ***
knowledge_proximity_mean                     6.2551e-04 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          9.1674e-05 ***
Chemical.Engineering                         7.0551e-10 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            1.5161e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          6.1662e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  1.6234e-10 ***
Materials.Science                            8.6616e-01
Mathematics                                  4.8662e-06 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.5560e-02 *
Social.Sciences                              3.2192e-01
Veterinary                                   3.8633e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -182,548.0   Adj. Pseudo R2: 0.053853
           BIC:  366,216.9     Squared Cor.: 0.068979

In [91]:
fml <- as.formula(
  paste0("novel_uzzi_bin ~ CoType + ", paper_level, "+", ex_controls, "+", moderating, "+",disciplines, " | PublishedYear")
)
model4 <- feglm(fml, data = data[(data$paper_type =='article')&(data$knowledge_proximity_mean>0), ], family = binomial("logit"), vcov = "hetero")
summary(model4)

GLM estimation, family = binomial, Dep. Var.: novel_uzzi_bin
Observations: 294,879
Fixed-effects: PublishedYear: 51
Standard-errors: Heteroskedasticity-robust
                                              Estimate Std. Error    z value
CoTypeCollaboration                           0.099926   0.011245   8.886446
CoTypeParticipation                           0.010299   0.015044   0.684582
lnnum_author                                 -0.087020   0.007328 -11.874570
internationalinternational                   -0.045118   0.009576  -4.711696
lnnum_reference                               0.059057   0.008633   6.841129
num_fac                                       0.062924   0.006715   9.369983
SDGTrue                                       0.093974   0.008128  11.561174
lnmean_career_age                             0.012005   0.013072   0.918354
lnex_ld_avg_avgimpact                        -0.269872   0.007355 -36.690437
lnex_ld_avg_insthindex                       -0.051397   0.007510  -6.844259
ex_ld_bin_gsGlobalNorth                       0.309880   0.017490  17.717256
ex_ld_bin_sameCSame                          -0.063400   0.009432  -6.721559
knowledge_proximity_mean                     -0.519050   0.159415  -3.255960
lnex_ld_avg_before_year_prod_fac             -0.049429   0.004953  -9.979480
ex_ld_max_before_year_with_ih_binTrue         0.341342   0.011341  30.097556
Arts.and.Humanities                           1.739659   0.073159  23.779227
Biochemistry..Genetics.and.Molecular.Biology  0.581832   0.012607  46.150420
Business..Management.and.Accounting          -0.356803   0.087998  -4.054647
Chemical.Engineering                          0.134750   0.020810   6.475235
Chemistry                                     0.423471   0.011105  38.132697
Computer.Science                              0.895903   0.039528  22.665211
Decision.Sciences                             1.190685   0.189362   6.287886
Dentistry                                     1.903426   0.136163  13.979002
Earth.and.Planetary.Sciences                  0.710429   0.015254  46.572210
Economics..Econometrics.and.Finance          -0.112709   0.295110  -0.381923
Energy                                        0.199571   0.017872  11.166486
Engineering                                   0.283702   0.010425  27.213022
Environmental.Science                         0.563181   0.017461  32.253949
Health.Professions                            1.369455   0.128704  10.640324
Immunology.and.Microbiology                   0.192720   0.026784   7.195428
Materials.Science                            -0.021025   0.009864  -2.131434
Mathematics                                   0.545550   0.125475   4.347874
Medicine                                      0.823541   0.014724  55.930203
Neuroscience                                  0.518029   0.032283  16.046508
Nursing                                       1.134037   0.043674  25.965997
Pharmacology..Toxicology.and.Pharmaceutics    0.892005   0.048193  18.509024
Physics.and.Astronomy                        -0.309036   0.011406 -27.095196
Psychology                                    0.395773   0.155025   2.552955
Social.Sciences                               0.123036   0.157185   0.782746
Veterinary                                    0.590046   0.206852   2.852509
                                               Pr(>|z|)
CoTypeCollaboration                           < 2.2e-16 ***
CoTypeParticipation                          4.9361e-01
lnnum_author                                  < 2.2e-16 ***
internationalinternational                   2.4566e-06 ***
lnnum_reference                              7.8571e-12 ***
num_fac                                       < 2.2e-16 ***
SDGTrue                                       < 2.2e-16 ***
lnmean_career_age                            3.5843e-01
lnex_ld_avg_avgimpact                         < 2.2e-16 ***
lnex_ld_avg_insthindex                       7.6873e-12 ***
ex_ld_bin_gsGlobalNorth                       < 2.2e-16 ***
ex_ld_bin_sameCSame                          1.7979e-11 ***
knowledge_proximity_mean                     1.1301e-03 **
lnex_ld_avg_before_year_prod_fac              < 2.2e-16 ***
ex_ld_max_before_year_with_ih_binTrue         < 2.2e-16 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          5.0210e-05 ***
Chemical.Engineering                         9.4665e-11 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            3.2182e-10 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance          7.0252e-01
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                  6.2265e-13 ***
Materials.Science                            3.3053e-02 *
Mathematics                                  1.3746e-05 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.0681e-02 *
Social.Sciences                              4.3378e-01
Veterinary                                   4.3376e-03 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -182,077.2   Adj. Pseudo R2: 0.056282
           BIC:  365,300.4     Squared Cor.: 0.072158

In [92]:
# 直接把 4 个模型并排放在一起
tab_latex <- etable(model1, model2, model3, model4,
                    keep = c("CoType", paper_vars, ex_vars, moderating_var, disciplines_vars),
                    se = "hetero",
                    tex = TRUE,
                    digits = 3,
                    fitstat = ~ n + r2 + ar2) # 可选：指定要在底部报告的统计量（如样本量、R方、调整R方）

# 打印出可以直接复制到 LaTeX 的代码
cat(tab_latex)

\begingroup \centering \begin{tabular}{lcccc}    \tabularnewline \midrule \midrule    Dependent Variable: & \multicolumn{4}{c}{novel\_uzzi\_bin}\\    Model:                                              & (1)            & (2)            & (3)            & (4)\\      \midrule    \emph{Variables}\\    CoTypeCollaboration                                 & 0.168$^{***}$  & 0.176$^{***}$  & 0.144$^{***}$  & 0.100$^{***}$\\                                                           & (0.011)        & (0.011)        & (0.011)        & (0.011)\\       CoTypeParticipation                                 & 0.047$^{***}$  & 0.095$^{***}$  & 0.047$^{***}$  & 0.010\\                                                           & (0.014)        & (0.015)        & (0.015)        & (0.015)\\       Arts.and.Humanities                                 & 1.84$^{***}$   & 1.81$^{***}$   & 1.76$^{***}$   & 1.74$^{***}$\\                                                           & (0.072)        & (0.072)        & (0.073)        & (0.073)\\       Biochemistry..Genetics.and.Molecular.Biology        & 0.498$^{***}$  & 0.488$^{***}$  & 0.560$^{***}$  & 0.582$^{***}$\\                                                           & (0.012)        & (0.012)        & (0.013)        & (0.013)\\       Business..Management.and.Accounting                 & -0.428$^{***}$ & -0.391$^{***}$ & -0.345$^{***}$ & -0.357$^{***}$\\                                                           & (0.088)        & (0.088)        & (0.088)        & (0.088)\\       Chemical.Engineering                                & 0.131$^{***}$  & 0.118$^{***}$  & 0.128$^{***}$  & 0.135$^{***}$\\                                                           & (0.021)        & (0.021)        & (0.021)        & (0.021)\\       Chemistry                                           & 0.459$^{***}$  & 0.444$^{***}$  & 0.436$^{***}$  & 0.423$^{***}$\\                                                           & (0.011)        & (0.011)        & (0.011)        & (0.011)\\       Computer.Science                                    & 0.897$^{***}$  & 0.886$^{***}$  & 0.885$^{***}$  & 0.896$^{***}$\\                                                           & (0.039)        & (0.039)        & (0.039)        & (0.040)\\       Decision.Sciences                                   & 1.23$^{***}$   & 1.24$^{***}$   & 1.21$^{***}$   & 1.19$^{***}$\\                                                           & (0.187)        & (0.186)        & (0.188)        & (0.189)\\       Dentistry                                           & 1.99$^{***}$   & 1.99$^{***}$   & 1.93$^{***}$   & 1.90$^{***}$\\                                                           & (0.135)        & (0.135)        & (0.135)        & (0.136)\\       Earth.and.Planetary.Sciences                        & 0.737$^{***}$  & 0.718$^{***}$  & 0.708$^{***}$  & 0.710$^{***}$\\                                                           & (0.015)        & (0.015)        & (0.015)        & (0.015)\\       Economics..Econometrics.and.Finance                 & -0.125         & -0.175         & -0.146         & -0.113\\                                                           & (0.298)        & (0.297)        & (0.293)        & (0.295)\\       Energy                                              & 0.173$^{***}$  & 0.167$^{***}$  & 0.216$^{***}$  & 0.200$^{***}$\\                                                           & (0.018)        & (0.018)        & (0.018)        & (0.018)\\       Engineering                                         & 0.340$^{***}$  & 0.328$^{***}$  & 0.301$^{***}$  & 0.284$^{***}$\\                                                           & (0.010)        & (0.010)        & (0.010)        & (0.010)\\       Immunology.and.Microbiology                         & 0.100$^{***}$  & 0.104$^{***}$  & 0.170$^{***}$  & 0.193$^{***}$\\                                                           & (0.026)        & (0.026)        & (0.027)        & (0.027)\\       Materials.Science                                   & 0.025$^{***}$  & 0.017$^{*}$    & 0.002          & -0.021$^{**}$\\                                                           & (0.009)        & (0.010)        & (0.010)        & (0.010)\\       Mathematics                                         & 0.563$^{***}$  & 0.544$^{***}$  & 0.566$^{***}$  & 0.546$^{***}$\\                                                           & (0.124)        & (0.123)        & (0.124)        & (0.125)\\       Medicine                                            & 0.769$^{***}$  & 0.771$^{***}$  & 0.805$^{***}$  & 0.824$^{***}$\\                                                           & (0.015)        & (0.015)        & (0.015)        & (0.015)\\       Neuroscience                                        & 0.460$^{***}$  & 0.460$^{***}$  & 0.514$^{***}$  & 0.518$^{***}$\\                                                           & (0.032)        & (0.032)        & (0.032)        & (0.032)\\       Nursing                                             & 1.15$^{***}$   & 1.14$^{***}$   & 1.14$^{***}$   & 1.13$^{***}$\\                                                           & (0.043)        & (0.043)        & (0.044)        & (0.044)\\       Pharmacology..Toxicology.and.Pharmaceutics          & 0.918$^{***}$  & 0.898$^{***}$  & 0.892$^{***}$  & 0.892$^{***}$\\                                                           & (0.048)        & (0.048)        & (0.048)        & (0.048)\\       Physics.and.Astronomy                               & -0.258$^{***}$ & -0.245$^{***}$ & -0.293$^{***}$ & -0.309$^{***}$\\                                                           & (0.011)        & (0.011)        & (0.011)        & (0.011)\\       Psychology                                          & 0.350$^{**}$   & 0.334$^{**}$   & 0.371$^{**}$   & 0.396$^{**}$\\                                                           & (0.151)        & (0.152)        & (0.153)        & (0.155)\\       Social.Sciences                                     & 0.191          & 0.200          & 0.155          & 0.123\\                                                           & (0.161)        & (0.159)        & (0.157)        & (0.157)\\       Veterinary                                          & 0.572$^{***}$  & 0.583$^{***}$  & 0.593$^{***}$  & 0.590$^{***}$\\                                                           & (0.204)        & (0.206)        & (0.205)        & (0.207)\\       lnnum\_author                                       &                & -0.131$^{***}$ & -0.069$^{***}$ & -0.087$^{***}$\\                                                           &                & (0.007)        & (0.007)        & (0.007)\\       internationalinternational                          &                & -0.008         & -0.031$^{***}$ & -0.045$^{***}$\\                                                           &                & (0.009)        & (0.010)        & (0.010)\\       lnnum\_reference                                    &                & -0.006         & 0.061$^{***}$  & 0.059$^{***}$\\                                                           &                & (0.008)        & (0.009)        & (0.009)\\       num\_fac                                            &                & 0.051$^{***}$  & 0.059$^{***}$  & 0.063$^{***}$\\                                                           &                & (0.007)        & (0.007)        & (0.007)\\       SDGTrue                                             &                & 0.088$^{***}$  & 0.092$^{***}$  & 0.094$^{***}$\\                                                           &                & (0.008)        & (0.008)        & (0.008)\\       lnmean\_career\_age                                 &                & -0.007         & 0.033$^{**}$   & 0.012\\                                                           &                & (0.013)        & (0.013)        & (0.013)\\       lnex\_ld\_avg\_avgimpact                            &                &                & -0.265$^{***}$ & -0.270$^{***}$\\                                                           &                &                & (0.007)        & (0.007)\\       lnex\_ld\_avg\_insthindex                           &                &                & -0.050$^{***}$ & -0.051$^{***}$\\                                                           &                &                & (0.007)        & (0.008)\\       ex\_ld\_bin\_gsGlobalNorth                          &                &                & 0.320$^{***}$  & 0.310$^{***}$\\                                                           &                &                & (0.017)        & (0.018)\\       ex\_ld\_bin\_sameCSame                              &                &                & -0.088$^{***}$ & -0.063$^{***}$\\                                                           &                &                & (0.009)        & (0.009)\\       knowledge\_proximity\_mean                          &                &                & -0.537$^{***}$ & -0.519$^{***}$\\                                                           &                &                & (0.157)        & (0.159)\\       lnex\_ld\_avg\_before\_year\_prod\_fac              &                &                &                & -0.049$^{***}$\\                                                           &                &                &                & (0.005)\\       ex\_ld\_max\_before\_year\_with\_ih\_binTrue        &                &                &                & 0.341$^{***}$\\                                                           &                &                &                & (0.011)\\       \midrule    \emph{Fixed-effects}\\    PublishedYear                                       & Yes            & Yes            & Yes            & Yes\\      \midrule    \emph{Fit statistics}\\    Observations                                        & 294,879        & 294,879        & 294,879        & 294,879\\      \midrule \midrule    \multicolumn{5}{l}{\emph{Heteroskedasticity-robust standard-errors in parentheses}}\\    \multicolumn{5}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\ \end{tabular} \par\endgroup